### ISSUE TITLE
DISABLE_ALIAS_SUFFIX=0 not honoured

### ISSUE THREAD

**Issue by MrMeeb** [simple-login/app#1046]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**

When setting DISABLE_ALIAS_SUFFIX=0 in simplelogin.env, I am still able to create aliases without a suffix.

**Expected behavior**

When creating an alias, it should either require me to provide a suffix, or automatically generate one (I am not exactly sure what the expected behaviour is here, since I haven't seen it working yet)

**Screenshots**

Here you can see me creating 'spam@relay-test.domain.com', which it then allows me to do without a suffix:

![image](https://user-images.githubusercontent.com/16963756/171997970-2fccc49a-039e-4857-abe0-8d258431a8a9.png)

![image](https://user-images.githubusercontent.com/16963756/171997973-7dd9e3bd-20bb-4812-8e5f-6a882d4cb76b.png)

**Environment (If applicable):**
 - OS: Ubuntu 20.04.4 LTS, Docker version 20.10.16, build aa7e414
 - Browser: Chrome
 - Version: 3.4.0, according to `docker compose images`

**Additional context**
My simplelogin.env:

```# WebApp URL
URL=https://app.relay-test.domain.com

# domain used to create alias
EMAIL_DOMAIN=relay-test.domain.com

# transactional email is sent from this email address
SUPPORT_EMAIL=support@relay-test.domain.com

# custom domain needs to point to these MX servers
EMAIL_SERVERS_WITH_PRIORITY=[(10, "app.relay-test.domain.com.")]

# By default, new aliases must end with ".{random_word}". This is to avoid a person taking all "nice" aliases.
# this option doesn't make sense in self-hosted. Set this variable to disable this option.
DISABLE_ALIAS_SUFFIX=0

# the DKIM private key used to compute DKIM-Signature
DKIM_PRIVATE_KEY_PATH=/dkim.key

# DB Connection
DB_URI=redacted

FLASK_SECRET=redacted

GNUPGHOME=/sl/pgp

LOCAL_FILE_UPLOAD=1

POSTFIX_SERVER=postfix
```

**Comment by nguyenkims** [comment]
DISABLE_ALIAS_SUFFIX  is enabled when it's **present** in env variables, so `DISABLE_ALIAS_SUFFIX=0` is actually the same as `DISABLE_ALIAS_SUFFIX=1` or `DISABLE_ALIAS_SUFFIX=true`. To disable this behavior, you can just remove this variable from the env file.

**Comment by MrMeeb** [comment]
Thanks for the clarification, confirmed that it is now working as expected. Little bit confusing, but no bother. Thank you!
