### ISSUE TITLE
mentioning the name of the alias somewhere in the mail for checking if sender and alias match

### ISSUE THREAD

**Issue by HelpfulRock** [simple-login/app#105]
Hey,

mentioned my issue on reddit for anonaddy and since someone in simplelogins sub spoilered that pgp is comming i wanted to mention it here, too:
https://www.reddit.com/r/AnonAddy/comments/ffryws/how_do_you_use_anonaddy_relativly_new_and_not/

only sent some testmails on simplelogin, yet since using it with pgp wasn't there yet but i'm not bound to anonaddy, yet (only found both of you last week)

issue: when using a different alias with every website there is no easy way to check if for example i got an email from amazon if the adress it went to is the one i gave amazon or if someone else lost my mail and i got a fake phishingmail. 

not sure how to solve this for simplelogin but perhaps put the name of the alias in front of the original subject? or if you add the same "replace subjectline" that anonaddy has replace it with aliasname?

as i said i'm not sure which one of you i will ultimatly go to( - or just have both for comparison :P) but that might be a quality of life feature ;)

**Comment by nguyenkims** [comment]
Hey when you receive a forwarded email, the "To" email header is the alias so you know what alias has been used right?

**Comment by HelpfulRock** [comment]
i know which alias was used, sure but since i can't keep all my aliases in my head i can't see with a glance that its the right alias for amazon.com for example and not the one from whateverothersite.com.
I just checked and i did use 90 random alias on my domain before ever finding your service so thats way to much to keep in mind.

currently i have to solve this by creating inbox rules tagging each incomming mail to slap the servicename i have in my list to it. so if i get an email with label github.com and the mail tells me its from amazon or my bank then i can see at a glance that this can not be and that github must have lost my mail.

in this regard simplelogin just acts as cheap "i can stuff more domains, catchall and aliases to answer from" under the hood of my mail provider. it does "nothing" for comfortable use in regards to the identification since i still need the same inbox rules to find out if someone leaked my mailadress and if i get faked mail. in terms of security i'll wait for the update with pgp, then simplelogin can highten security in the setup.

**Comment by nguyenkims** [comment]
I see, in this case I think "alias note" can be useful: you can add a note to an alias to know why it's been created, where it should be used, etc. 

The problem with modifying the email subject is this will be visible to the sender when you reply. For this reason, SimpleLogin never modifies email subject or email content (as opposed to other email forwarders).

**Comment by HelpfulRock** [comment]
Hey,
problem is: i only see the alias note on the simple login website, not where i have my mails. and simplelogin is not where i can see my mails. so if i try it with notes or anything in the mailclient its the same as with inbox rules. same amount of work.

yeah i know what you mean. perhaps the solution is since the asnwer goes over your server again to strip it there? if the format ist something like !/!note!/! it can be found by rules even if the answer gets prefixes like "Re:"
it would have to be symbols that don't break anything in clients so not sure about "/".

**Comment by nguyenkims** [comment]
Modifying email content is not compatible with PGP signing unfortunately as the signature is based on the original email content. 

My trick to keep track of alias is to prefix it with the service name, for example amazon.random@simplelogin.co for Amazon or reddit.random2@simplelogin.co for Reddit. 

For existing alias, I'm thinking about adding a custom alert in SimpleLogin that notifies you whenever your alias receives emails from unknown address. For example you can set rules like this alias should only receive emails from *amazon* address and if the alias receives emails from unknown sender, you'll receive an alert. How does that sound?

**Comment by HelpfulRock** [comment]
hey,
yeah not the easiest topic.
the name of the service might be an idea for new alias but got its own pitfalls since like the version with the +alias and the service name its a pattern that can be used. and if you use catchall someone can quite easily get a new alias going that you won't recognise.

the alert is a good idea! espeacially with a customisable ruleset! Sounds great

**Comment by nguyenkims** [comment]
I usually use the same of the service as prefix and as the suffix is a totally random string so there's no pattern.

The catch-all can be a risk indeed if falling in hands of a spammer ... so this feature should be used with care. For this reason the catch-all option is also disabled by default.

**Comment by nguyenkims** [comment]
@HelpfulRock should I close this issue?

**Comment by HelpfulRock** [comment]
yep, thanks
