### ISSUE TITLE
Error i've regularly been getting from SES

### ISSUE THREAD

**Issue by havedill** [simple-login/app#106]
Seems like more recently, Simple login is attempting to forward to email to me AS the original sender.

With Amazon SES, this leads to message rejects, because I'm only authorized to send the email under my domain

Can we add something that maybe can disable this spoofing, if desired?
![image](https://user-images.githubusercontent.com/34009509/76550727-98b72980-6460-11ea-937a-d487cdeb2577.png)

MESSAGE:
https://pastebin.com/rEzw5yrB

**Comment by nguyenkims** [comment]
Hi I think the problem comes from the "Sender" header which is "notifications@care.onemedical.com". The "From" header is OK as it's reply+lbfkscngrltseqfukcpxyrhrgjvbgj@XXXXX.info so comes from your domain. I'll create a PR to address this issue.

**Comment by nguyenkims** [comment]
@havedill the image 2.0.0 has been pushed that should fix this issue. This is a major version so it requires a manual data migration though: https://github.com/simple-login/app/blob/master/docs/upgrade.md#upgrade-to-200-from-105

**Comment by havedill** [comment]
Getting errors with the DB migration

`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: column "mailbox_id" contains null values

sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) column "mailbox_id" contains null values

[SQL: ALTER TABLE gen_email ALTER COLUMN mailbox_id SET NOT NULL]


`

**Comment by nguyenkims** [comment]
@havedill this is the error from running the script on https://github.com/simple-login/app/blob/master/docs/upgrade.md#upgrade-to-200-from-105 ?

This script is to be run before running "sl-migration" actually.

**Comment by havedill** [comment]
I see. I was reading that page in order.

So should i be pulling the sl-app 2.0.0 first before running that script? Because i get an error if i run that against my current sl-app (:latest)

```
In [1]: """This ad-hoc script is to be run when upgrading from 1.0.5 to 2.0.0
   ...: """
   ...: from app.extensions import db
   ...: from app.log import LOG
   ...: from app.models import Mailbox, GenEmail, User
   ...:
   ...: for user in User.query.all():
   ...:     if user.default_mailbox_id:
   ...:         # already run the migration on this user
   ...:         continue
   ...:
   ...:     # create a default mailbox
   ...:     default_mb = Mailbox.get_by(user_id=user.id, email=user.email)
   ...:     if not default_mb:
   ...:         LOG.d("create default mailbox for user %s", user)
   ...:         default_mb = Mailbox.create(user_id=user.id, email=user.email, verified=True)
   ...:         db.session.commit()
   ...:
   ...:     # assign existing alias to this mailbox
   ...:     for gen_email in GenEmail.query.filter_by(user_id=user.id):
   ...:         if not gen_email.mailbox_id:
   ...:             LOG.d("Set alias  %s mailbox to default mailbox", gen_email)
   ...:             gen_email.mailbox_id = default_mb.id
   ...:
   ...:     # finally set user to full_mailbox
   ...:     user.full_mailbox = True
   ...:     user.default_mailbox_id = default_mb.id
   ...:     db.session.commit()
   ...:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/code/shell.py in <module>
      6
      7 for user in User.query.all():
----> 8     if user.default_mailbox_id:
      9         # already run the migration on this user
     10         continue

AttributeError: 'User' object has no attribute 'default_mailbox_id'

```

**Comment by nguyenkims** [comment]
Do you know what is the current version you're using? You can check that by running 

`docker run -it sl-app cat CHANGELOG
`

The current version is the top line on CHANGELOG file.

If it's inferior to 1.0.5 then you'd need to upgrade to 1.0.5 which is the latest version before 2.0.0 first. I just updated the README to add that.

**Comment by havedill** [comment]
Trying now. I wrote a script that automatically updates my container to the :latest branch each week. Looks like the current one topped out at 1.0.4

```
docker rm -f sl-app sl-email
sudo docker run --rm \
    --name sl-migration \
    -v $(pwd)/dkim.key:/dkim.key \
    -v $(pwd)/dkim.pub.key:/dkim.pub.key \
    -v $(pwd)/simplelogin.env:/code/.env \
    --network="sl-network" \
    simplelogin/app-ci:latest flask db upgrade
sudo docker run -d \
    --name sl-app \
    -v $(pwd)/simplelogin.env:/code/.env \
    -v $(pwd)/dkim.key:/dkim.key \
    -v $(pwd)/dkim.pub.key:/dkim.pub.key \
    -p 7777:7777 \
    --restart always \
    --network="sl-network" \
    simplelogin/app-ci:latest
sudo docker run -d \
    --name sl-email \
    -v $(pwd)/simplelogin.env:/code/.env \
    -v $(pwd)/dkim.key:/dkim.key \
    -v $(pwd)/dkim.pub.key:/dkim.pub.key \
    -p 20381:20381 \
    --restart always \
    --network="sl-network" \
    simplelogin/app-ci:latest python email_handler.py
docker ps -a
docker ps -a > docker_status
echo y | docker system prune -a
mail -s "SimpleLogin Updated" -r "Dave<XXXXX@XXXXXXXX>" XXXXXXXXXX < docker_status
```

**Comment by havedill** [comment]
Ok it went through fine that time.

Thanks for the help!

**Comment by nguyenkims** [comment]
Cool, glad that this works!

To make sure new versions don't break existing installations I release new versions manually now.
