### ISSUE TITLE
[Feature Request] Enable PWA + service worker support in the web app

### ISSUE THREAD

**Issue by NateyB** [simple-login/app#1072]
I'd like to see the simple web application available as a PWA with a significant amount of offline caching. I prefer using web apps when there's no real reason to use a native app (especially now that they can be installed to home screens on most smartphones). Simple Login is the ideal candidate for this upgrade because it would enable
* Loading significantly faster—for me, this is actually a pain point using Simple Login.
* Fullscreen on iOS
* Provide a more native feel
* Reduced server hits (useful for self-hosting), since already-cached assets do not need to be redownloaded
* Faster distribution & rollout times than a native app. The last update to the iOS app store was in October 2021.
* Eliminating fees associated with app stores—both membership costs & in-app purchase cuts—do not apply.

The only downside is that it could potentially increase development costs. (I would argue, though, that a single PWA is superior to maintaining any app store apps, but awareness of PWAs is virtually non-existent.)

Let me know what you think! I'm able to help contribute, though I have no experience with service workers.

**Comment by nguyenkims** [comment]
PWA indeed requires a lot of changes in our current web app. On mobile, we prefer to concentrate our effort on the mobile apps as 
1) a native app has a tighter integration with the OS and can provide a more seamless user experience.
2) a native app has access to the native SDK that provides more possibility than a PWA app. 
3) performance wise, a native app is generally faster and consumes less resources than a PWA app.
