### ISSUE TITLE
Not obvious how to stop an alias highlight

### ISSUE THREAD

**Issue by JeffersonBledsoe** [simple-login/app#1088]
Please note that this is only for bug report. 

For help on your account, please reach out to us at hi[at]simplelogin.io. Please make sure to check out [our FAQ](https://simplelogin.io/faq/) that contains  frequently asked questions.

For feature request, you can use our [forum](https://github.com/simple-login/app/discussions/categories/feature-request). 

For self-hosted question/issue, please ask in [self-hosted forum](https://github.com/simple-login/app/discussions/categories/self-hosting-question)

## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**
After creating an alias, it sets a `highlight_alias_id` querystring parameter, visually highlighting the new alias and dimming the other aliases. This is nice, but it's not clear how to stop this when I want to then continue using the alias page. Clicking outside of the alias does not de-activate the highlight, nor does pressing `ESC`. The only way I can see is to press a link and cause the query parameter to be removed.

**Expected behavior**
Clicking outside of the alias or pressing `ESCAPE` will cause the highlighting to stop, allowing me to see the other aliases more clearly again.

**Screenshots**
<img width="1210" alt="Screenshot 2022-06-14 at 11 03 02 am" src="https://user-images.githubusercontent.com/30210785/173551563-1d7a1ba9-7bf5-4b31-9432-9d44bf7f7f97.png">

**Comment by therealmrmuffin** [comment]
@nguyenkims mind taking a look at this issue?

**Comment by nguyenkims** [comment]
In the next version, we won't blur out other aliases so they remain visible.

**Comment by therealmrmuffin** [comment]
@JeffersonBledsoe this has been fixed. Mind closing this issue now?

**Comment by JeffersonBledsoe** [comment]
Looks good!
