### ISSUE TITLE
Can SL allow bulk import of aliases to builtin domain on selfhosted?

### ISSUE THREAD

**Issue by NateTheSage** [simple-login/app#1094]
I just recently started using SL on my local net to replace my old method of using PostfixAdmin to make and manage my aliases, and I have to say, this works like a dream. Being able to reach it using an Android app when I'm anywhere makes it so much more convenient than trying to remember one of my aliases that I made for some purpose or another!

My only issue is that I have 700+ aliases spread out over 6 mailboxes for family, so this becomes kind of a pain (and a lot of clicking!) to try and migrate them all with only a single domain, currently set as my builtin.

Is it possible for me to bulk import them using the template into the DB like it were a custom domain? If not, could that be made a feature that's toggleable in `simplelogin.env`?

I looked around to see if anyone asked this question/made this feature request, but I have to confess I'm not sure how the magic works on the inside, it could be I'm asking for the moon. :)

**Comment by nguyenkims** [comment]
@NateTheSage you can currently import aliases created with your custom domain into SL. This import feature also allows to set mailboxes for each alias. You just need to add the domain and mailboxes before running the import.

<img width="661" alt="image" src="https://user-images.githubusercontent.com/3167780/174027464-17b1c8de-83c3-4560-b747-40c7156e2187.png">

**Comment by NateTheSage** [comment]
This didn't solve my need though, this is meant for custom domains, and the only domain I had used for my setup was what SL considers the builtin, so I had to get creative.

I ended up solving this on my own time and I'll leave this here in case anyone has a similar situation to me on selfhosted.

What I did was I wrote a brief bash script to write a Postgres script for importing aliases on the builtin domain that you set up SimpleLogin with. I know you're not really supposed to read over a file like this in `bash`, but this ended up working for me.

```
#!/bin/bash
id=<num>
mailbox=<num2>
today=date +"%F 00:00:00.000000" 
while IFS=, read -r email note dispose; do
    echo "INSERT INTO alias (id, created_at, updated_at, user_id, email, enabled, custom_domain_id, automatic_creation, directory_id, note, mailbox_id, name, disable_pgp, cannot_be_disabled, disable_email_spoofing_check, batch_import_id, pinned, original_owner_id, transfer_token) VALUES ('$id', '$today', '$today', '$mailbox', '$email', 't', null, 'f', null, '$note', '$mailbox', '$note', 'f', 'f', 'f', null, 'f', null, null);" >> pgsql-import-aliases.pgsql; 
    ((id++));
  done < aliasimporttemplate.csv
```
Where `id` is your current alias id counter, `mailbox` is your receiving inbox id, and today is the current date with time in non-TZ format.

This creates a Postgres script that will populate the DB with your aliases and the default values based upon iteration through the import template that is provided by the Batch Import view.

Once that's done, all you have to do is run it.

`docker exec -it sl-db psql -U <DB_USER> -d simplelogin -f ./pgsql-import-aliases.pgsql`

Do a page refresh and you should see all your aliases.
