### ISSUE TITLE
Custom domain alias count incorrect

### ISSUE THREAD

**Issue by mwmason** [simple-login/app#111]
On the custom domain summary and details page, the number of aliases is woefully less than my actual count of aliases. I logged out and logged in and the count doesn't change.

thanks for a great service!

**Comment by nguyenkims** [comment]
@mwmason  Hey can you send me the email you use within SimpleLogin so I can have a look at the database? And glad that you find SimpleLogin useful!

**Comment by mwmason** [comment]
@nguyenkims - is there no way to reference my account without providing my email?

**Comment by nguyenkims** [comment]
I've found the bug :), it should be fixed in https://github.com/simple-login/app/pull/113

The count has been fixed too, now it should display the correct number of alias for each domain.
