### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by johnbrz** [simple-login/app#117]
I was reading the privacy policy at https://simplelogin.io/privacy and thought some things might be better clarified.

Example: On the dashboard, you can see the activity of an Alias and on it you can see some metadata such as the date of the email forwarding, the sender and the recipient. 

In addition to this data in the dashboard, there must surely be other data from postfix, nginx, etc.

So, [since metadata is also important data](https://www.businessinsider.com/nsa-document-metadata-2016-12), besides the content of the message itself, what is the way SimpleLogin handles this data? How is it stored? For how long? Is it deleted right after use? Who has access? Are they encrypted on your server? Is it possible to read the content of messages while they are in the postfix queue? How do the laws of the country where SimpleLogin works affect all this?

There are other things that could be detailed as well, like deleting an active account: will everything be deleted immediately? will any data still be stored? 

What is SimpleLogin's PGP/GPG key? Who are the people who maintain this service? How financially sustainable is it?

A security page could also be created, explaining more details about how data is protected, STARTTLS, PFS, DNSSEC, MTA-STS, TLS-RPT, DMARC, SPF and DKIM, Security Headers, etc.

I think a better explanation of all this can make the service much more reliable.

btw, I saw that you recently added support for PGP encryption. This is a big step!

**Comment by nguyenkims** [comment]
Thanks for the feedback, we'll surely put these informations into the Privacy Policy. A quick answers to some questions:
- The alias activity is needed to a)avoid abuse and b)helps users keep track of who contacted an alias, useful to know whether an alias has been "leaked". Its data includes sender address, alias and the timestamp. I think adding automatic deletion is a great way to balance privacy & features in this case, thanks for the idea!

- Logs (Postfix, Nginx, App) are kept for 7 days for debugging purpose. 

- We currently have STARTTLS, SPF, DKIM. DNSSEC, MTA-STS, TLS-RPT, PFS are on the way, they should be available by the end of this month.

- When user deletes their account, everything in the database linked to this user is deleted. The logs related to this user are deleted in 7 days though.

All questions will be addressed either in our privacy policy and/or FAQ.

**Comment by fabianski7** [comment]
Almost a month and I haven't seen any of it published in the privacy policy.

That's not just my concern. See the reddit speech after your request to include simplelogin in privacytools.io

https://www.reddit.com/r/privacytoolsIO/comments/g4927c/request_to_add_simpleloginio_browser_addon/
http://web.archive.org/save/https://www.reddit.com/r/privacytoolsIO/comments/g4927c/request_to_add_simpleloginio_browser_addon/

> Are IP stored upon login? Are access timestamp stored? Is something else stored about the user or the emails being forwarded? Does the server have server logs storing data? How the information can be released to authorities if they receive a question. I notice he runs it from France which is a big NO NO when it comes to spying eyes.

**Comment by nguyenkims** [comment]
@fabianski7 we are have been working on a rewrite of our privacy policy which is accurate but not detailed enough. We already sent it to our lawyer, should not take more than several days. Everything's slowed down in France since the Covic though. We are btw looking for reviewers, if you happen to be interested in reviewing it, please let me know!

**Comment by nguyenkims** [comment]
@johnbrz @fabianski7 we have published new privacy page on https://simplelogin.io/privacy/ that goes into details of how/why information are stored.

**Comment by johnbrz** [comment]
Thank you for paying due attention to that.
Just a few more questions about what was published.

> We also have access to the following records of account activity: number of messages sent, amount of storage space used, total number of messages, last login time.

Is this record from the last login accumulated (e.g., if you log 10 times in the day, all these records will be kept) or is it replaced by the most recent one?


> Native Applications: When you use our native applications such as iOS and Android apps, we (or the mobile app platform providers) may collect certain information in addition to the information mentioned elsewhere in this Policy. We may use mobile analytics software to send crash information to our developers so that we can fix bugs rapidly. Some platforms (such as the Google Play Store or the Apple App Store) may also collect aggregate, anonymous statistics governed by the privacy policy and terms and conditions of the Google Play Store or the Apple App Store. None of the software on our apps will ever access or track any location-based information from your device at any time. Any personal data acquired during this process is anonymized.

I saw that there is a plan to launch an application for android, so there is one for IOS, and the above text quotes google play and its trackers, however, these trackers are not allowed in F-DROID. So they will be removed in this particular version?


> When required under applicable law. If the appropriate law enforcement authorities have the necessary warrant, criminal subpoena, or court order requiring we share data, we have to comply. And unless we’re legally prevented from it, we’ll always inform you when such requests are made. *We have never received a such request from the government.*

It would be interesting to create a "[Canary Statement](https://en.wikipedia.org/wiki/Warrant_canary)" to keep users informed about such decisions. Similar to what [RISEUP](https://riseup.net/en/about-us/canary) and other services already offer

**Comment by nguyenkims** [comment]
@johnbrz 

> Is this record from the last login accumulated (e.g., if you log 10 times in the day, all these records will be kept) or is it replaced by the most recent one?

The last login information is actually not saved currently but we plan to add it in the future to detect suspicious activities. As the detection usually base on login time and location, we put that clause in there in advance :).

> I saw that there is a plan to launch an application for android, so there is one for IOS, and the above text quotes google play and its trackers, however, these trackers are not allowed in F-DROID. So they will be removed in this particular version?

These trackers are actually **not** in the app as they collect data like total number of installation,  total number of active users, etc that these platforms automatically collect when you install the app from their stores. There's no tracker in our app actually.

> It would be interesting to create a "Canary Statement" to keep users informed about such decisions. Similar to what RISEUP and other services already offer

That's a good idea, I just created a ticket in our roadmap to add a canary statement page on our website, feel free to vote on it to make it happen sooner :): https://trello.com/c/brgfdHWx/58-create-canary-statement-to-let-users-know-about-goverment-subpoena

**Comment by johnbrz** [comment]
> The last login information is actually not saved currently but we plan to add it in the future to detect suspicious activities. As the detection usually base on login time and location, we put that clause in there in advance :).

Okay. Then I'll rephrase my question

These last login records **WILL** either be accumulated or **WILL** be replaced by the latest?

> Example: On the dashboard, you can see the activity of an Alias and on it you can see some metadata such as the date of the email forwarding, the sender and the recipient.

And how about this?

**Comment by nguyenkims** [comment]
> These last login records WILL either be accumulated or WILL be replaced by the latest?

It will be replaced by the latest

> And how about this?

I'm not sure to understand the question. If you click on an alias activity, currently you'll see all forwards/replies/sends for this alias. We planned to add an option that allows users to remove all activities older than 1 week though: https://trello.com/c/77UTBHc9/45-option-to-automatically-delete-alias-activity-after-1-week.

**Comment by johnbrz** [comment]
Yes. That's what I meant. I think that's a necessary step for user privacy. 

Perhaps an option to disable these records and a button to clear existing ones should be considered as well.

**Comment by nguyenkims** [comment]
> Perhaps an option to disable these records and a button to clear existing ones should be considered as well.

That's a good idea indeed. I just updated https://trello.com/c/77UTBHc9/45-option-to-disable-alias-activity so the option would be **disable** alias activity.

**Comment by nguyenkims** [comment]
@johnbrz As a new privacy page is created that is much more detailed, I'll close this ticket.
