### ISSUE TITLE
slef-hosting - sl-migration not running

### ISSUE THREAD

**Issue by melbv** [simple-login/app#1208]
HI team

as i am running the selfhosted 3.4.0 version, i get the following message when running the `sl-migration` container. As a result, the container does not create and if I go through with `sl-app` and the other containers, i cannot enter the server later down the line. 

```
>>> URL: http://aaa.bbb.ccc
Paddle param not set
Upload files to local dir
>>> init logging <<<
2022-08-01 19:28:25,119 - SL - DEBUG - "/code/app/utils.py:11" - <module>() -  - load words file: /code/local_data/words_alpha.txt
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
```

Could you guide me through how to debug this one? or whether it is normal to get that behaviour?

Thanks in advance

**Comment by nguyenkims** [comment]
@melbv this doesn't seem to an error message. Btw we are about to release a new version that you can check out the doc on https://github.com/simple-login/app/tree/4.6.2-beta

**Comment by melbv** [comment]
@nguyenkims - thanks for taking the time.
When i run all the steps, i get the webserver to start and serve the `/auth` page. But i cannot do anything else. If i try to create a login, i get the popup `registration closed` (although `DISABLE_REGISTRATION=0` in the `simplelogin.env` file).
If I create a user manually, once i enter the credentials, i get the following:

```
Server error
Looks like we are having some server issues...

We are notified and will look at this issue asap!
```

Not sure where to start to debug. it looks like it could be the dialog between app & db that does not work properly but would not know why...
would you be able to point me in the right direction?

**Comment by nguyenkims** [comment]
@melbv you need to remove `DISABLE_REGISTRATION` from the configuration if you want to allow registration. In SimpleLogin, this setting is on if it's present and this doesn't depend on the value.

Can you paste the logs for `sl-app` and `sl-email` here? Maybe it can give more info on the error.

**Comment by melbv** [comment]
Works like a charm - thanks @nguyenkims for taking the time and as ever thanks for the app. this is a fantastic piece of email management
