### ISSUE TITLE
Extension shows infinite "Please wait ..." loading screen

### ISSUE THREAD

**Issue by dohlin** [simple-login/app#124]
Hey guys...I filed an issue in the extension repo but wondering if this wasn't a better place possibly for it due to being able to look through server logs or something...but I'm honestly not sure how to troubleshoot this one. The browser extension used to work, and then out of nowhere it seemingly just stopped working. I can access the SL web UI perfectly fine both internal or external.

However, generating an API key and applying the custom URL and key to the extension results in the error in the title. Oddly enough, if I click "Manage Aliases" in the lower left corner, I get directed the the https://[my_url]/dashboard/ URL but the page says:

You need to login to see this page.
We are sorry but you are not authorized to access this page.

If I then click "Login", I can log in successfully and see the dashboard. If I then re-click on the extension and re-click on "Manage Aliases", a new tab opens up to the same https://[my_url]/dashboard/ which results in the same error message and the cycle can repeat itself indefinitely. Nothing has really changed on my end configuration wise, don't know why this would have suddenly stopped working.

Having an older version of SL I tried updating to the latest, but that unfortunately didn't resolve the issue either.

I should also note that if I log in at https://[my_url]/ and then open a new tab and attempt to go to https://[my_url]/ again, it automatically shows me as logged in, etc. So it's not a new-tab related issue or anything like that. It's like the extension just stopped communicating with my instance. This also happens locally and remotely, across different browsers, in or out of incognito mode, etc.  I even tried blowing everything away - docker images, containers, volumes, etc. and recreating everything from scratch - same result. What could I be missing and how could I troubleshoot this? Any thoughts?  Thanks!

EDIT:

**Comment by nguyenkims** [comment]
Hey thanks for letting us know! This error must come from some breaking changes on the server side (new endpoints supporting pagination) that are not released yet. Please use this browser extension v1.2.0 version instead in the meantime which should be compatible.

https://github.com/simple-login/browser-extension/tree/1.2.0

In order to install the extension, please follow the README. It involves some npm stuffs. 

In the meantime we'll try to find a way to release the latest version of SimpleLogin. The new version is a bit tricky to migrate as there are some breaking changes in the data structure that requires manual checks.

**Comment by dohlin** [comment]
Yep, sure enough reverting back to v1.2.0 fixed the issue.  I'll go ahead and close this issue for now since it's a known bug and this resolves my current issue at hand.  Thanks for the prompt reply!

**Comment by nguyenkims** [comment]
@dohlin just to let you know we have found a way to upgrade to the latest version (3.0.1) from 2.1.0

The upgrade requires several steps though as you can see on https://github.com/simple-login/app/blob/master/docs/upgrade.md  . Let me know if you run into any problem during the upgrade, we have tested on our self-hosted instance and this works but our setup doesn't cover all cases.

With this 3.0.1 version, you can use the latest version of Firefox/Chrome extension.

**Comment by dohlin** [comment]
@nguyenkims Sweet, thanks for the update!  I'll put it on my list to try the upgrade out.  Thanks!
