### ISSUE TITLE
Email Headers

### ISSUE THREAD

**Issue by fabianski7** [simple-login/app#125]
Some services add the header `Content-Transfer-Encoding: quoted-printable` to email and this breaks Thunderbird + Enigmail automatic decryption.

This bug was reported here 
https://sourceforge.net/p/enigmail/forum/support/thread/47de861f44/#

Maybe SimpleLogin could remove it during forwarding?

**Comment by nguyenkims** [comment]
@fabianski7 Thanks for the report. SimpleLogin doesn't add this header `Content-Transfer-Encoding` during the encryption actually. 

The top-level MIME part of a PGP-encrypted email from SimpleLogin has the following format, that doesn't contain the `Content-Transfer-Encoding` header:

```
Content-Type: multipart/encrypted; protocol="application/pgp-encrypted";
 boundary="===============2673717580734905133=="
MIME-Version: 1.0
```

**Comment by fabianski7** [comment]
Yes, SL doesn't add. It's the other sites that do that.

**Comment by nguyenkims** [comment]
@fabianski7 do you know on what website that we can reproduce this error? So we can try to investigate.

**Comment by fabianski7** [comment]
I don't know if they are available in your country, but this bug is happening with the emails I receive from these sites:

https://www.mercadolibre.com
https://www.olx.com

**Comment by fabianski7** [comment]
I just got an email from twich with the same header

**Comment by nguyenkims** [comment]
@fabianski7 we just deployed fix, could you re-try and let us know if the problem persists?

**Comment by fabianski7** [comment]
That solved the problem. It's working now. Thank you!
