### ISSUE TITLE
[Feature Request] Bulk / mass editing of aliases

### ISSUE THREAD

**Issue by jeifour** [simple-login/app#1266]
This is something that has come up for me a number of times. Basically there are situations where I want to bulk edit the mailbox address that certain aliases are connected to, and right now it's very tedious to do it. One of the great things about SimpleLogin is the fact that it doesn't matter so much what email provider or address I'm actually using behind the scenes. All my aliases stay the same, so if I move from Yahoo to Proton, or from Proton to a self-hosted setup, etc. then I do not need update or inform anyone about that, I would just be able to change out my mailbox address where all the email ends up at and I'm done.

Right now I can either use the UI on the website and do this one by one for every alias (quite tedious if you have a couple hundreds of them) or I have to use the export/import feature with the CSV file. That one kinda works, but tbh maybe I'm just stupid but I mess up the formatting all the time and I can't figure it out really.

This was me some time ago:
![スクリーンショット 2022-09-02 15 59 31](https://user-images.githubusercontent.com/3247063/188165605-8177d27e-2fb4-485b-9b6a-09db957caba6.png)

It would be great if that was possible to do through the UI itself.

**Comment by nguyenkims** [comment]
Do you think this one is similar to this feature request https://github.com/simple-login/app/discussions/407?

**Comment by jeifour** [comment]
@nguyenkims Sorry yes seems like I forgot to search through the Discussions.
