### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by 100doses** [simple-login/app#1267]
Will this support PHP ?

**Comment by jeifour** [comment]
What is your question? SimpleLogin is not written in PHP if that is what you're wondering about. You can review the full source code here on GitHub.

**Comment by Bibkins** [comment]
If you are looking for [symfony development services](https://aristeksystems.com/technologies/php-symfony-development/#:~:text=Packed%20with%20various%20features%2C%20Symfony%20is%C2%A0your%20choice%20if%C2%A0you%20are%20looking%20to%C2%A0develop%20scalable%20web%20applications.%20It%C2%A0comes%20with%20reusable%20PHP%20components%2C%20stability%2C%20and%20database%20engine%20independence.%20Highly%20flexible%20too.%20You%20don%E2%80%99t%20have%20to%C2%A0bother%20your%20head%20about%20your%20web%20outlooks%20across%20devices.), the only one that comes to mind is Aristek Systems. This company has been dealing with similar issues for over 20 years, which shows great experience and will reflect in the quality of performance of the work for the better. I periodically use their services for my company and I recommend you to contact them.

**Comment by 100doses** [comment]
> What is your question? SimpleLogin is not written in PHP if that is what you're wondering about. You can review the full source code here on GitHub.

I would like to implement the API in PHP but i not found any libraries to do it.

**Comment by 100doses** [comment]
> 

Maybe i think i poqtsted in the wrong repo.

**Comment by jeifour** [comment]
> implement the API

If by "implementing" you mean that you want to send requests to the SimpleLogin API in your PHP app, then the answer would be yes, you can use any programming language.

Simple example:
```
$api_key = "your_api_key";
$api_root = "https://app.simplelogin.io";
$api_route = "/api/v5/alias/options";
$header = [
  "Content-Type: application/json",
  "Cache-Control: no-cache",
  "User-Agent: Name of your app",
  "Authentication: $api_key",
];

$ch = curl_init();
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2);
curl_setopt($ch, CURLOPT_POST, false);
curl_setopt($ch, CURLOPT_POSTFIELDS, null);
curl_setopt($ch, CURLOPT_HTTPGET, true);
curl_setopt($ch, CURLOPT_URL, $api_root . $api_route);
curl_setopt($ch, CURLOPT_HTTPHEADER, $header);

$result = json_decode(curl_exec($ch), true);
var_dump($result);
```

**Comment by 100doses** [comment]
Sorry for the delay, thanks for your answer, i'll try it and i will comeback to confirm if it's working or not later.
