### ISSUE TITLE
Blacklisted SL domains

### ISSUE THREAD

**Issue by git70** [simple-login/app#1274]
Hi
Your domain aleeas.com has been placed on the block list :(
https://github.com/unkn0w/disposable-email-domain-list
You have to take action and check other domains!
Best Regards!

**Comment by nguyenkims** [comment]
@git70 thanks for letting us know. Can you please create a PR on this repo to remove aleeas.com ? We have seen similar issue in the past and unfortunately people still mistakenly consider SimpleLogin aliases the same as disposable email address.

**Comment by nguyenkims** [comment]
@git70 I just created this PR https://github.com/unkn0w/disposable-email-domain-list/pull/2
