### ISSUE TITLE
Bypass for PGP

### ISSUE THREAD

**Issue by fabianski7** [simple-login/app#130]
A few sites offer the option to encrypt emails with your public key, such as Github, so encryption in SimpleLogin is not required.

Creating a new mailbox in SL, adding the github alias to it (or moving the existing one) and not enabling encryption would be a solution, but it is not possible to create a mailbox with an email address that is already in use. So it would be necessary to create another one with a different email address, and also create a new key pair. Well, I don't think that would be the best way to solve this.

So, something like a bypass for some aliases in a mailbox that has public key encryption enabled would be an option to solve this. What do you think? Is that possible to implement? Any other suggestions?

**Comment by nguyenkims** [comment]
@fabianski7 Good point! We'll add the possibility to disable PGP on a specific alias if its owning mailbox has PGP enabled.

**Comment by nguyenkims** [comment]
@fabianski7 https://github.com/simple-login/app/pull/194 adds support for this feature :).

**Comment by fabianski7** [comment]
cool!
