### ISSUE TITLE
I lost my 2FA info, and recovery codes. How to disable 2FA?

### ISSUE THREAD

**Issue by noutsiderirl** [simple-login/app#1311]
Recently I changed to a new phone, I forgot to backup.

I lost my 2FA info and recovery codes. 

How to disable 2FA? I can't log in...

**Comment by ledgeri** [comment]
> Recently I changed to a new phone, I forgot to backup.
> 
> I lost my 2FA info and recovery codes.
> 
> How to disable 2FA? I can't log in...

Any -not in detail- update? (Final resolution is enough when it finished if not already, i am just interested) @noutsiderirl
