### ISSUE TITLE
Whitelist a sender for a given alias

### ISSUE THREAD

**Issue by ploum** [simple-login/app#1353]
For some reasons, some mails sent by a provider to one of my alias are sometimes failing DMARC check. It’s not always the case and I’m pretty sure this provider simply has a bad mail infrastructure.

This is annoying as I should regularly check on SL if I’ve received a mail from them (then download the eml and try to read it which is nearly impossible).

It would be nice if I could just whitelist a given sender address for a given alias.

**Comment by nguyenkims** [comment]
@ploum If a message is quarantined, this means that the sender explicitly states their emails should respect DMARC and any email that violates this should either be quarantined or rejected. SimpleLogin follows the email protocol and unfortunately the only solution is the sender fixing their DNS setup ... If possible, please contact the sender so they can update their DMARC setting or fix their SPF/DKIM that cause the DMARC failure. Their emails are probably being rejected or end up in spam at other email providers as well.

**Comment by ploum** [comment]
do you mean that the sender received an error regardless of the ignore/reject setting?

Thanks for the explanation, this bug could be closed.
