### ISSUE TITLE
Few mistakes

### ISSUE THREAD

**Issue by ghost** [simple-login/app#1485]
Hello!
I found the mistake on [your page](https://simplelogin.io/temporary-email/). There is redundant word “use”! What a bad grammar! :)

![E0DF7950-BAB2-4A87-B15A-263787FE1E36](https://user-images.githubusercontent.com/120200229/206775302-cd96ad76-b7da-4ed9-b75c-7b5cacc3c9f9.jpeg)

**Comment by nguyenkims** [comment]
Thanks for spotting the error, it has been fixed now.
