### ISSUE TITLE
Running SL behind an existing mail service

### ISSUE THREAD

**Issue by Nomarix** [simple-login/app#150]
Hi SL Team,

thanks for this great project and your high activity in supporting it.
Individual mails are a perfect thing.

I absolutely prefer your solution for login-mails to reduce spam and increased privacy.
Together with the self-hosting option to further more reduces mails which are routed over unknown server it’s a must have. 😉

However while I investigate the self-hosting option I faced some issues:
1) Mail server are hard to manage, need deep knowledge and running accessible for everybody in the internet.
Mistakes can cause ugly behavior with worst case get hacked and act as on open mail relay.
2) As a private person which has usually a dynamic IP its tricky to get mails sent out without dieing in spam filters directly.
3) To host SL on a provider you need a bigger package to install everything what’s needed and risks are the same like 1)

For me and probably for a lot more people it would be a great option to run in a more secure and less offense environment. I also guess, that the majority will use a selfhosted SL server only for themselves.

My idea is, if a package is providable to run SL behind an existing mail server/service which comes together with your own domain. In this case SL could fetch the mails, progress it and send out over the according smtp to the final mailbox. 

For this solution the important and critical stuff will be managed by professionals on the hoster site and the smart logic behind will be done by SL.

Do you think Is this possible and realizable? 

However there are points and questions which I could not answer by myself:
If a (spam) mail receives SL server and the alias is blocked will it be "not accepted", "bounced" or "discarded"?

Thanks a lot an keep this project alive.

**Comment by nguyenkims** [comment]
Thanks for your kind words! We do help running the server in the Enterprise tier (cf our pricing page https://simplelogin.io/pricing/), this is targeted towards companies who want to have their own server but individuals (or rather a group of individuals) can also opt to use this option.

Here are the answers to your questions:

1. The configuration that we recommend in Postfix is quite strict and avoids the server from becoming an open relay. You're absolutely right that running a mail server is not easy. Running one for personal use is not too difficult though as you will be less a target for attacks.

2. The mail server requires a static IP as IP plays an important role in email delivery score. The delivery score also increases with time so some initial emails might fall into the Spam/ folder. Don't worry, as long as your server is not an open relay and the IP or domain is not blacklisted, most of your emails will not be put into Spams (0% spam score doesn't exist though as how Google/Microsoft detects spams is still a mystery)

3. A small server (1-2GB of Ram) should be enough to run SimpleLogin. We are actually running several small instances in our development environment and they are running fine :).

**Comment by Nomarix** [comment]
Thanks for your quick answer. 
I will consider your points and check how my mail sending will behave over time.

Regards
