### ISSUE TITLE
[Bug ipadOS App] Cancel button in share not working

### ISSUE THREAD

**Issue by wAuner** [simple-login/app#151]
There seems to be a bug in the iOS/ipadOS app. When I try to access the app via the share function in safari on ipad, the cancel button has no effect on the "create alias" window from simplelogin. I have to swipe the window down to close it.

**Comment by ntnhon** [comment]
Hi @wAuner, thank you for pointing out. It is because the app calls the wrong dismiss function. This bug is now fixed with this [commit](https://github.com/simple-login/Simple-Login-iOS/commit/4482dd501b9b8235460f5a1430b469a54041835c)
