### ISSUE TITLE
Use minimal permissions

### ISSUE THREAD

**Issue by wrycu** [simple-login/app#1560]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**
This extension intended to preserve privacy requests "Read and change all your data on all sites".

**Expected behavior**
A privacy-focused extension should be requesting only the minimal set of permissions needed to function.

**Screenshots**

![image](https://user-images.githubusercontent.com/4709746/216208512-0b515cef-bc3f-4ac5-b680-9be3c2ef57eb.png)

https://crxcavator.io/report/dphilobhebphkdjbpfohgikllaljmgbn?platform=Chrome&new_scan=true

**Environment (If applicable):**
N/A

**Additional context**
N/A

**Comment by nguyenkims** [comment]
@wrycu This is also discussed in https://github.com/simple-login/browser-extension/issues/145

**Comment by wrycu** [comment]
Thanks! I did search; no idea how I missed it.

Closing.
