### ISSUE TITLE
WebAuthn Support

### ISSUE THREAD

**Issue by developStorm** [simple-login/app#157]
Are there any plans for supporting the WebAuthn?

**Comment by nguyenkims** [comment]
@developStorm we have this ticket in our roadmap https://trello.com/c/oWi7p2yp/55-support-other-mfa-types, feel free to vote on it to make it happen sooner :).

**Comment by developStorm** [comment]
Oh, thanks! By the way, do you accept pull requests from users? If this is not your prioritize I can probably do something on this.

**Comment by nguyenkims** [comment]
@developStorm we love PRs from users! 

For example, yesterday we had this PR https://github.com/simple-login/app/pull/154 that is created by a user who wants to have a feature more quickly. The feature is now live.

**Comment by developStorm** [comment]
Thanks! I see there is [another ticket about this](https://trello.com/c/oWi7p2yp/55-support-other-mfa-types) which has more votes than the ticket you mentioned above. Do you have an estimated time of officially starting of development of U2F? Just make sure we will not have any conflict.

**Comment by nguyenkims** [comment]
Nice spot! They are duplicated tickets indeed, I just removed the other one. 

We haven't planned for this ticket yet, a ticket is planned when it's moved to the "Nearer term" column.

**Comment by developStorm** [comment]
Thanks! Since we already have tickets now, I'll close this issue to avoid duplicates.
