### ISSUE TITLE
Wrong api key error even after using the correct one

### ISSUE THREAD

**Issue by hexclann** [simple-login/app#1571]
Hello, I have created an API key from the dashboard, but when I make a request I get:
`{"error":"Wrong api key"}` error despite copy pasting the exact key from the UI.

This is the command:
`curl -s -X GET "https://app.mydomain.com/api/v5/alias/options" -H "Authorization: Bearer gcthyhtdhffqmthrrroRedactedToken" -H "Content-Type:application/json"`

**Comment by knomdivad** [comment]
Did this never get answered? I am experiencing this exact issue. I have tried multiple API keys and variations on the header. Nothing works.

**Comment by hexclann** [comment]
I figured out the solution myself. The correct request format is 
` curl -s -X GET "https://example.com/api/v2/aliases?page_id=2" -H "Authentication: yourtoken" -H "Content-Type:application/json"`
