### ISSUE TITLE
Question: Security / Encryption, DANE support

### ISSUE THREAD

**Issue by wAuner** [simple-login/app#158]
How are emails encrypted between the sender and simplelogin and between simplelogin and the forwarded address? Do you support DANE?

**Comment by developStorm** [comment]
I think DANE is already supported
https://www.hardenize.com/report/simplelogin.io/1585823060#email_dane

**Comment by wAuner** [comment]
My email service (posteo.de) checks and shows if DANE is available. And when I try to send an email to my alias, it‘s not available.

**Comment by nguyenkims** [comment]
@wAuner The emails are encrypted using TLS between the sender and SimpleLogin. Please note SMTP protocol dictates that this encryption is **optional** as the sender can choose to not use TLS. DANE intervene here as it prevents the sender from using a plaintext connection. SimpleLogin does fully support DANE.

TLS encryption is used by default between SimpleLogin and your mailbox if you use a popular mailbox like Gmail, Protonmail, etc as they all support TLS now. 

You can go a step further by enabling PGP on your mailbox: your email is encrypted using your public key by SimpleLogin before being forwarded to your mailbox.

**Comment by nguyenkims** [comment]
@wAuner should I close this issue?

**Comment by wAuner** [comment]
thanks, can be closed.
