### ISSUE TITLE
Sender address format?

### ISSUE THREAD

**Issue by developStorm** [simple-login/app#160]
That modification to the title is quite annoying. As you probably know, Gmail, Outlook, and some self-hosting mail servers such as [mailcow](https://mailcow.github.io/mailcow-dockerized-docs/) support to forward their email to another address, which is pretty similar to how SL works. `(Sender->Relay Addr->Actual Receiver)`. 
  
However, they neither change the title of the email nor the displayed sender (i.e. they keep the original `John Wick <john@wick.com>` instead of doing  `John Wick via Gmail Forwarding <reply+gmxxxxxxx@gmail.com>`). Why SL consider this modification is required?

**Comment by nguyenkims** [comment]
In order to respect the SPF, SimpleLogin must modify the email "From" header to an email address that's from SimpleLogin domain, i.e. something@simplelogin.co. 

The forwardings that you mentioned actually don't respect SPF for email services that have a strict SPF policy.

**Comment by developStorm** [comment]
Thanks. I did a bit more research and I think implementing [SRS](https://en.wikipedia.org/wiki/Sender_Rewriting_Scheme) will be a better choice. 

Office 365 seems [is doing this](https://docs.microsoft.com/en-us/office365/troubleshoot/antispam/sender-rewriting-scheme)

**Comment by developStorm** [comment]
Namesilo's mail forwarding service also has it, and it's working good with Gmail.

![image](https://user-images.githubusercontent.com/59678453/81344683-1b78f100-906c-11ea-9f95-eaedeec802c1.png)

![image](https://user-images.githubusercontent.com/59678453/81344900-74e12000-906c-11ea-8102-bf93a228e941.png)

**Comment by developStorm** [comment]
Just found a python lib for SRS: https://github.com/jichu4n/srslib

There is also an issue: how we make sure the reply goes to SL rather than the original address. If SRS is implemented, the actual receiver will check the DKIM record in the original address, which makes the change of `From` header impossible. 

An alternative of this, luckily, is to using `Reply-To` header instead. I've checked some senders such as Gmail, Apple, etc, and they are not signing this header, which means we can possibly change that without broke the original DKIM. Unfortunately, I don't think we will have a way to perform PGP encryption while keeping original DKIM. So for those senders who DO sign `Reply-To` header, or for users who enabled PGP ENC, we can fall down to the current solution.

**Comment by developStorm** [comment]
Some pseudocode and explanation.

``` python
if not mailbox.pgp_finger_print:
  if 'reply-to' not in msg["DKIM-Signature"]["h"]:
    # This is the best situation.
    # SRS replace
    # Reply-to replace
  elif mailbox.enforce_srs_do_not_change_reply_to_addr or 'no-reply' in contact:
    # This situation is a bit worse. If we want SRS, we have no way to make the user directly reply to SL address. Thus, we give user choice for each alias for how they wish to handle it.  
    # User should activate this feature when this alias rarely reply mail
    # In lots of cases, users don't need to reply to incoming mails. Emails are more likely to be notification tools rather than a communication method.
    # We can also arbitrarily use SRS when no-reply, noreply, or such keyword appears in the sender address. This is indicating the user will never need to reply, so it is safe to do not have reply-to.
    
    # Only SRS replace in this case.


# Fallback to current method
```

**Comment by nguyenkims** [comment]
Hey besides SPF, SRS will fail DMARC if a domain uses a strict alignment policy.

In addition, it's almost impossible to support the "reply all" case with SRS: if an email is sent to several people that includes an alias and if the user wants to reply to all, his original email address will be visible.

The very first version of SimpleLogin actually uses SRS. SRS is quite easy to setup as Postfix already supports it. However due to the mentioned downsides, I decided SRS is not enough and then `email_handler` is born :).

**Comment by developStorm** [comment]
This is a nice discussion about SRS and issues you pointed out: https://github.com/forwardemail/free-email-forwarding/issues/137. We definitely don't want to completely drop `email_handler`, but just add some special case to comply with SRS.

**Comment by nguyenkims** [comment]
Thanks for the link, that's a very interesting read indeed! 

I think SRS is **not** the solution (so contrary to what forwardemail's guy thinks :) ) as more and more domains will set a strict DMARC. The only thing that stops them from doing so now is they want to support some legacy applications that are going to be gone little by little. 

ARC is in my opinion the **true** solution. Implementing it is not easy though as libraries that support it are still scarce. ARC is also not supported (yet) by some email services. Having an option to enable ARC is indeed interesting, I just created this ticket in the roadmap https://trello.com/c/YWv8WOL5/70-support-arc-authenticated-received-chain

Apart from protecting email addresses, another goal of SimpleLogin is to become a "light" business email solution, and having to think before clicking "reply all" is not adapted for non-tech people :).  Business emails usually include multiple destinations so "reply all" is almost a must.

**Comment by nguyenkims** [comment]
@developStorm unrelated but there are some feedbacks about WebAuthn that I'd like to send to you, how can I contact you :)?

**Comment by developStorm** [comment]
> @developStorm unrelated but there are some feedbacks about WebAuthn that I'd like to send to you, how can I contact you :)? 


invt_unroots@simplelogin.co

**Comment by developStorm** [comment]
> Thanks for the link, that's a very interesting read indeed! 
> 
> 
> 
> I think SRS is **not** the solution (so contrary to what forwardemail's guy thinks :) ) as more and more domains will set a strict DMARC. The only thing that stops them from doing so now is they want to support some legacy applications that are going to be gone little by little. 
> 
> 
> 
> ARC is in my opinion the **true** solution. Implementing it is not easy though as libraries that support it are still scarce. ARC is also not supported (yet) by some email services. Having an option to enable ARC is indeed interesting, I just created this ticket in the roadmap https://trello.com/c/YWv8WOL5/70-support-arc-authenticated-received-chain
> 
> 
> 
> Apart from protecting email addresses, another goal of SimpleLogin is to become a "light" business email solution, and having to think before clicking "reply all" is not adapted for non-tech people :).  Business emails usually include multiple destinations so "reply all" is almost a must.
> 
> 
> 
> 
> 
> 

Thanks for the reply. I am confusing that how you can implement ARC along without SRS? If you re-sign and send with SL domains there is no ARC needed if my understanding is correct.

**Comment by developStorm** [comment]
@nguyenkims Could you consider to make MX record optional for custom domains? I know it sounds ridiculous but I can't actually use SL to receive mail before SRS / ARC are implemented...

**Comment by nguyenkims** [comment]
@developStorm Hey without MX record, the recipient could not answer your emails ...

**Comment by developStorm** [comment]
> @developStorm Hey without MX record, the recipient could not answer your emails ... 

I can have other MX servers to take care it,only use SL to send mail

**Comment by nguyenkims** [comment]
@developStorm ah ok I see. Can you tell me a bit about your usecase :)? That can be quite interesting as initially the custom domain's main goal is to create aliases and receive emails.

**Comment by developStorm** [comment]
@nguyenkims The mail forwarding service I'm using is good enough for me and since SL is not supported SRS&ARC I have to keep on that service. However, this service doesn't allow me to send out email. So I want to use SL just as a sending service for now.

**Comment by nguyenkims** [comment]
@developStorm that's an interesting usecase indeed 🤔. For now I don't see any downside of allowing it except that it's a bit manual for you (having to create the alias on the 2 services).

It would take a bit of time to fully support this usecase though, in the meantime if you want you can send me the domain that you want to enable and I can mark it as "verified" in the database. This is of course a workaround until a complete solution is implemented :) .

**Comment by developStorm** [comment]
@nguyenkims I found that Sl will not re-check MX record so it's currently verified and works well!

**Comment by nguyenkims** [comment]
@developStorm glad that it works :).

**Comment by nguyenkims** [comment]
I created this ticket for the SRS feature https://trello.com/c/ue8iAqI3/77-support-srs, I close this issue then.

**Comment by developStorm** [comment]
I am thinking about re-starting support for SRS, any input? Looks this lib is very neat to work with:  https://github.com/jichu4n/srslib

**Comment by nguyenkims** [comment]
@developStorm Hey the main downside of SRS is we have to use Reply-To and it doesn't support multiple recipient emails (i.e. when there are several addresses in To: and CC:). 

For email bouncing, currently SimpleLogin is using VERP (https://en.wikipedia.org/wiki/Variable_envelope_return_path) for tracking bounces and this is done by using the envelope mail_from, which then conflicts with SRS.

**Comment by klinki** [comment]
Hello @nguyenkims, I have a question related to this issue.

I'm using SimpleLogin and I'm quite happy with it, thanks for great service! But there is a problem with it modifying the sender header. When someone sends signed email, email client will report broken signature - since the sender in signature is not the same as one in Sender header, because it was modified by SimpleLogin.

I can understand it might be problematic in situations like you described with multiple addresses in To: and CC:  - maybe, would it be possible to switch to Reply-To: header for specific alias? For example bank communication is very unlikely to contain multiple emails in To: and CC: but on the other hand, it is more likely to be digitally signed.

**Comment by nguyenkims** [comment]
@klinki ARC can be indeed useful in this case. There's a page that @developStorm created to keep track of resources to implement ARC at https://github.com/simple-login/app/discussions/504

**Comment by nguyenkims** [comment]
We haven't had a chance to test out Cloudflare email routing yet but it seems to be either based on the "classic" email forwarding or ARC. Either way, people can't reply to a forwarded email or send emails from an alias.

**Comment by FWest98** [comment]
From my findings, Cloudflare is using ARC. I am personally also running into this issue - I would really like to see the availability of ARC/SRS in SimpleLogin. The reply-to option would be interesting for managing replies (at the cost of CCs), but it might also be interesting to enable setting an alias to "receive-only". For me, this is a major usecase, and having SRS/ARC in those cases would be very helpful as to not mess up all my email contacts.
