### ISSUE TITLE
One-click unsubscribe preservation no longer working

### ISSUE THREAD

**Issue by AdmiralShinysides** [simple-login/app#1616]
I have the "One-click unsubscribe" feature set to "Preserve the original unsubscribe policy" because certain sieve rules I have are expecting emails from a single sender address but either including or not including a "list-unsubscribe" header.

Since January of 2023, I have noticed that all emails I receive that are forwarded through SimpleLogin are no longer including the "list-unsubscribe" header even though my setting/preference hasn't changed. 

This feature was working for me at one point, prior to January.  

I also have quite a lot of emails by this point from the same sender, where one goes through SimpleLogin and the other directly to my real email address, in which the email going through SimpleLogin has no "list-unsubscribe" header but the email going to my real email address does contain the "list-unsubscribe" header.  I have examples from multiple senders so I know it's not just that a particular sender updated their unsubscribe policy or anything like that.

I had opened up a ticket with support back in January but, after not finding anything, they advised me to open an issue here.

Please let me know if any additional information is needed to help resolve this.

**Comment by Ftftftctftf** [comment]
Hello!
Try to write here **hi[at]simplelogin.io**. This is the main channel of support. Do not forget to attach link to this issue

**Comment by acasajus** [comment]
Hey, do you have an example of site that sends the header that SL doesn't forward to you? I'm trying to repro but I haven't been able to.

**Comment by AdmiralShinysides** [comment]
At least one of the mailing lists from Dropbox (sourcing from no-reply@em-s.dropbox.com) appear to be the same way. Emails not forwarded by SL come through with the list-unsubscribe, emails forwarded by SL do not come through with the list-unsubscribe, even though it should be getting preserved.

**Comment by xyxzxyz** [comment]
I can confirm this. I have two emails from Google Store, one to my Gmail directly, one to my alias then forwarded to same Gmail account. List-unsubscribe and List-Id have been stripped from the header. Not just Google. I can name a few here: Bestbuy, Microsoft, Preservation did not work.

**Comment by xyxzxyz** [comment]
> Hey, do you have an example of site that sends the header that SL doesn't forward to you? I'm trying to repro but I haven't been able to.

Here are a few sites you can sign up without creating an account to compare the two emails:
Google: https://about.google/intl/ALL_us/email-newsletter-sign-up/
Macy's homepage, bottom right
Bestbuy's homepage, bottom right
Nordstrom's homepage, at the bottom

**Comment by acasajus** [comment]
I just registered to all of those to see if we can get to the bottom of this.

**Comment by xyxzxyz** [comment]
> I just registered to all of those to see if we can get to the bottom of this..
> 
> SPAM come to me!

Today's update fixed it! Thank you!

**Comment by acasajus** [comment]
:tada:

**Comment by hwaterke** [comment]
There seems to be a regression as it is no longer working for me (with the preserve option set in settings)

**Comment by bruceleerabbit** [comment]
Bug #2180 is related to this.
