### ISSUE TITLE
Logging out does not log out of Proton account

### ISSUE THREAD

**Issue by jbabyhacker** [simple-login/app#1655]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**
1. Login to SimpleLogin with a Proton account by the `Log in with Proton` on the login screen. After logging in, you are automatically redirect to the SimpleLogin dashboard.
2. Then log out of SimpleLogin by clicking your initials on the top right, then clicking "Sign out"
3. Browse to https://account.proton.me/login?product=generic&language=en , which will automatically log you into your Proton account without authenticating.
4. Browse to https://app.simplelogin.io/auth/proton/login , which will log you into SimpleLogin without authenticating.

**Expected behavior**
- At step 3, you should not be able to access the Proton account without authenticating, since you logged out on step 2.
- At step 4, you should not be able to access your SimpleLogin account without authenticating, since you logged out on step 2.

**Environment (If applicable):**
 - OS: Linux, Mac
 - Browser: Brave
 - Version 1.49.120

**Additional context**
This could allow someone else other than yourself access to your Proton account even though you only accessed SimpleLogin.

**Comment by nguyenkims** [comment]
@jbabyhacker this is actually the expected behavior as SimpleLogin and Proton authentication sessions are separated. It's like for ex if you log in on a website with "Login with Twitter" and if you stay logged in in Twitter, you can always re-login to the website with your Twitter session.
