### ISSUE TITLE
Deleted Alias resulting in Epic Games locking the account, (Need to be recovered)

### ISSUE THREAD

**Issue by fluxsystem** [simple-login/app#1674]
Support suggested to contact via github

Hi guys!

This may not be the right place to write a post about this, but unfortunately I have no choice.
A while back I deleted my simplelogin account aliases etc. Assuming I had adjusted all accounts their emails.
However, this turned out not to be the case and I forgot this one from Epic Games. After having several support tickets with Epic Games, they advised me to contact Simplelogin.
Simplelogin support says unfortunately they can't help me restore the alias because it has been removed. I showed the conversation with the Simplelogin to the employee of Epic Games. Unfortunately Epic Games says they can't verify me because I can't receive an email with the code in it. I have always secured my account with two-step verification. I have even told support purchases, linked accounts, ip addresses etc and still they refuse to help me. I myself have put a lot of time and money into my account and due to the shutdown of support, I can't play their games. Not even on my consoles. The only way I can get access is by getting the alias active

I hope you developers can help me with this. You guys can really save me with this situation.

Thanks!!

**Comment by VividLemon** [comment]
If someone could simply take back a deleted email, what would prevent anyone else from taking a disposed email?

There is no ability for anyone to do this. 

The prompt suggests:

> Maybe you want to disable the alias instead? Please note once deleted, it can't be restored.

Assuming you have a recovery key in addition to whatever multi factor authentication method you have, I'd say if you had a recovery key, it would be very dumb for them to deny such a request imo. But nobody can make up for their poor support. Especially if you have other details in addition, (credit card transactions etc)

From a technical perspective, it would be impossible for the development team to do anything. Anyone willing to contribute to this project would not have the ability to overturn a fundamental aspect of it's design. And if they did, it would go against what the service is supposed to be used for. I'd say that most people contributing to this project are just regular people like either of us and wouldn't have access to such information. -- TDLR It would be impossible for any person working on this project to have the information you're asking for. 

Perhaps you can attempt to put more pressure on Epic Games with additional information. But if you were in anyone's shoes here, it could be hazardous to do what you're asking for. If you are not the real account owner, and your entire story was made up, then someone may lose their real account to "social engineering".   

It's disappointing to say, but sometimes things just don't go well and sometimes work is lost. You should take them as learning experiences and educate yourself to never make the same mistake twice. Life goes on and in a few months you will likely not feel the same emotional devastation that you may feel now. The root of unconscious trauma is your body feeling insecure that the issue may happen again. The best way to work through that is to confront the pain and learn from your experience to secure yourself from the possibility of making the same mistake again. 

Sorry, but nobody here can do anything to help you. Things will get better, I'm sure of it.

**Comment by nguyenkims** [comment]
@fluxsystem sorry for the late response but as mentioned by @VividLemon , technically we can't recover a deleted alias: when an alias is deleted, all its associating data, including who owned it, the contacts (reverse aliases), etc are all hard deleted making the alias recovery impossible. The only exception is alias created with custom domain for which we can allow user to re-create it but even in that case, all its past data can't be recovered.

**Comment by fluxsystem** [comment]
> @fluxsystem sorry for the late response but as mentioned by @VividLemon , technically we can't recover a deleted alias: when an alias is deleted, all its associating data, including who owned it, the contacts (reverse aliases), etc are all hard deleted making the alias recovery impossible. The only exception is alias created with custom domain for which we can allow user to re-create it but even in that case, all its past data can't be recovered.

Hi the alias was ending with .duin5@simplelogin.com
All i need is to get the email one time activated for the 6 digit code for changing the email. Because they deactivated my account right now.
Its so hard to get my account back with Epic Games because they can't verify now due to the email thats going to be send

**Comment by VividLemon** [comment]
> Hi the alias was ending with [.duin5@simplelogin.com](mailto:.duin5@simplelogin.com) All i need is to get the email one time activated for the 6 digit code for changing the email. Because they deactivated my account right now. Its so hard to get my account back with Epic Games because they can't verify now due to the email thats going to be send

When an alias is deleted, it's put into a global trash and we make sure that it can't be reused. All historic information on the alias (the account that creates the alias, alias contacts, etc) are deleted to respect your privacy. 

It will **never** be available again. You will never recover this email, you will never gain access to the information here. You will certainly not be able to get this information from any contributor to the project. You should have understood when the message prompted that you were about to permanently delete an alias. There was no ambiguity with the message. You made a mistake and now it's time to move on. 

I have already explained this https://github.com/simple-login/app/issues/1674#issuecomment-1495106113

_It will **never** happen_

**Comment by fluxsystem** [comment]
Hey!

Just an update! After 2 months i finally managed to get my account back.
It was a journey but its finally fixed!

**Comment by VividLemon** [comment]
Congratulations 🥳
