### ISSUE TITLE
Link in onboarding email are not right

### ISSUE THREAD

**Issue by bestlibre** [simple-login/app#173]
I have installed an instance of simplelogin and I have realized that the links in the onboarding messages point to app.simplelogin.io and not my own instance.

Is it possible to change that ? And is it possible to add a parameter to deactivate completely onboarding email?

Thank you for this great project!

**Comment by nguyenkims** [comment]
@bestlibre we just released the version 3.1.0 with a new option `DISABLE_ONBOARDING` that, when set, will disable the onboarding emails.
https://github.com/simple-login/app/blob/master/example.env#L136
