### ISSUE TITLE
Email is None

### ISSUE THREAD

**Issue by SibrenVasse** [simple-login/app#179]
1. **Receive email from '<sender@remote.tld>' on alias (without name)**
```
From: none via SimpleLogin
 <reply+ucpwbdmjixjvdcvuhukqqhfjpvfrsi@sl.local>
```
![image](https://user-images.githubusercontent.com/5833571/81552227-6b64fa00-9383-11ea-865a-6af3cd0dcb0f.png)
(Maybe also display the email here)
2. **Reply to reverse alias from mailbox**
3. **Resulting email to '<sender@remote.tld>' will not contain a 'To:' header**
```
Mon, 11 May 2020 12:29:42 +0200 (CEST)
Subject: Test2
From: test@ab.cd

test
```

**Comment by nguyenkims** [comment]
Thanks for the report. How do you reproduce the 1. that is having a sender without email? The `From header` is created using https://github.com/simple-login/app/blob/92cd75f14a3c3d1afca687b63253bf5ab77424cb/app/models.py#L865 and `contact.website_email` is non-nullable 🤔

**Comment by SibrenVasse** [comment]
If the email does not contain a From: header, None is converted into a string.
https://github.com/simple-login/app/blob/54ce1dc9644be92517ef25d512e0ead835f4810a/email_handler.py#L125

**Comment by nguyenkims** [comment]
@SibrenVasse this issue should be fixed with https://github.com/simple-login/app/pull/184
