### ISSUE TITLE
Using directories as sub-domains in self-hosted scenario

### ISSUE THREAD

**Issue by springcomp** [simple-login/app#1803]
Reading [this post](https://simplelogin.io/blog/email-alias-vs-plus-sign/) I stumbled upon this paragraph:

> For email aliases created via **directory**, […] in the future, you can also use directory as a subdomain (i.e. `newsletter.simplelogin.fr`). You can then either use `newsletter/python@simplelogin.fr`, `newsletter#python@simplelogin.fr` or `python@newsletter.simplelogin.fr` as email address.

Is this supported in self-hosting scenarios ?
Is there anything to do at the DNS level ?

**Comment by springcomp** [comment]
@nguyenkims  Thanks a lot for your feedback.

I have been able to setup wildcard certificate issueing and renewal using [acme.sh](https://github.com/acmesh-official/acme.sh) which supports my DNS provider and creating a **TXT record** for `*.mydomain.com` with value `10 app.mydomain.com`.

However, I struggle to make sense and update the `pgsql-transport-maps.cf` query.

From the original configuration, with the assumption that the `custom_domain` table is empty, I assumed the `%s` input key was the domain. So I tried something like:

```patch
  # forward to smtp:127.0.0.1:20381 for custom domain AND email domain
  query = SELECT 'smtp:127.0.0.1:20381' FROM custom_domain WHERE domain = '%s' AND verified=true
-    UNION SELECT 'smtp:127.0.0.1:20381' WHERE '%s' = 'mydomain.com' LIMIT 1;
+    UNION SELECT 'smtp:127.0.0.1:20381' WHERE '%s' = 'mydomain.com' LIMIT 1
+    UNION SELECT 'smtp:127.0.0.1:20381' WHERE '%s' = '%%.mydomain.com' LIMIT 1;
```

However, this breaks postfix with a bunch of _lookup failure_ errors.
I can see that it tries multiple lookups, with `*`, `*` again, then the recipient and finally the sender, obviously without success.

I‘m not able to understand how to change the query to support wildcard subdomains.

I assume that once postfix configuration is correct, SimpleLogin will correctly map the incoming email to a directory, although I do not understand how SimpleLogin chooses between one the three `/`, `+` or `#` separators 🤔…


Would you be so kind as to point me in the right direction?

**Comment by nguyenkims** [comment]
@springcomp hey to enable subdomain, you can go to the database and can set the `public_domain.can_use_subdomain` column to true for the domain that has wildcard DNS enabled.

**Comment by springcomp** [comment]
@nguyenkims thanks a lot, that did the trick.

For the record, here are the queries that still MUST be modified in the Postfix configuration.

**pgsql-relay-domains.cf**

```patch
  # forward to smtp:127.0.0.1:20381 for custom domain AND email domain
  query = SELECT 'smtp:127.0.0.1:20381' FROM custom_domain WHERE domain = '%s' AND verified=true
-    UNION SELECT 'smtp:127.0.0.1:20381' WHERE '%s' = 'mydomain.com' LIMIT 1;
+    UNION SELECT '%s' WHERE '%s' = 'mydomain.com'
+    UNION SELECT '%s' WHERE '%s' LIKE '%%.mydomain.com' LIMIT 1;
```

**pgsql-transport-maps.cf**

```patch
  # forward to smtp:127.0.0.1:20381 for custom domain AND email domain
  query = SELECT 'smtp:127.0.0.1:20381' FROM custom_domain WHERE domain = '%s' AND verified=true
-    UNION SELECT 'smtp:127.0.0.1:20381' WHERE '%s' = 'mydomain.com' LIMIT 1;
+    UNION SELECT 'smtp:127.0.0.1:20381' WHERE '%s' = 'mydomain.com'
+    UNION SELECT 'smtp:127.0.0.1:20381' WHERE '%s' LIKE '%%.mydomain.com' LIMIT 1;
```
