### ISSUE TITLE
Changing your email address doesn't remove the old one

### ISSUE THREAD

**Issue by ContentPersonality2** [simple-login/app#182]
When you change your email address in your account settings the old one will still be registered as an active account however you can't sign in to it.

I encountered this issue when I was trying to change my email address back after mistakenly changing it to the wrong one. I'm just told that the email address I'm trying to change to is already registered with an account however when I go to reset the password to that account I don't receive any emails.

**Comment by SibrenVasse** [comment]
In email_already_used() a check is done if a mailbox or user email already exists.
In mailbox_already_used() a check is done if the current user already has a mailbox with that email address.

This means that currently:
- A user cannot change his email address to a currently existing Mailbox or User email address (this last one would conflict for authentication)
- A user **can** create a mailbox using a currently existing mailbox or user email address.
- Two users **can** have the same Mailbox (This means all calls to Mailbox.get_by(email=email) can result in the wrong mailbox!)
- 

So these constraints are not consistent with each other. What do you want to do @nguyenkims?

I think: (all reversed arguments also true)
- Two users **cannot** have the same email address (of course)
- A user **can** have a mailbox that is the email address of different user
- Two users **can** have the same mailbox, but we need to fix all Mailbox.get_by(email) calls

**Comment by nguyenkims** [comment]
@ContentPersonality2 I try to reproduce the issue by following these steps:

1. update my email address in the settings page
2. logout 
3. I can still login with my current (old) email address

Does this flow correspond to what you have experienced?

**Comment by SibrenVasse** [comment]
I managed to reproduce:

1. Change email address
2. Validate
(original mailbox still exists)
3. try to change back to original email

**Comment by nguyenkims** [comment]
@SibrenVasse thanks, I see the problem now. 

@ContentPersonality2  Should be fixed in https://github.com/simple-login/app/pull/192, this fix should be available by tomorrow.

**Comment by nguyenkims** [comment]
The fix is now available, I close the issue then.
