### ISSUE TITLE
Should return address be some special patterns rather than a key?

### ISSUE THREAD

**Issue by developStorm** [simple-login/app#185]
i.e. instead of store contact information on the server (which could be riskful), what about use some special patterns to translate the reply address(s) to the actual contact address?

For example, let's say `a-mail-box@example.com` -> `test@simplelogin.co`, instead of store `a-mail-box@example.com` in DB and create a key for it, we may use: `reply-to={a-mail-box#example.com}.test@simplelogin.co`as reply address and just parse original address from it. 

By doing that, we don't need to store contacts anymore, and users may create a reply addresses on-the-fly (just construct an address according to the format).

**Comment by nguyenkims** [comment]
@developStorm that's a very good idea indeed! I also thought about using a special format for the reverse-alias when I started working on SimpleLogin but finally went with using a randomized reverse-alias to reduce the chance of it being used by a malicious user (a hacker sends an email to `reply-to={a-mail-box#example.com}.test@simplelogin.co` to pretend this email is sent by the alias). This risk is now mostly 0 with the enforced-SPF check that @SibrenVasse  has done (https://github.com/simple-login/app/pull/164) so I think we can reconsider using a special format for reverse-alias.

I just created this ticket in the roadmap https://trello.com/c/bXxgiDBI/80-use-a-special-format-for-reverse-alias-that-can-be-created-on-the-fly

**Comment by vwxyzjn** [comment]
I also think this is an important feature. Another way to prevent the malicious user might be to set up a white list for the senders who can actually use the reverse aliases.

**Comment by nguyenkims** [comment]
@vwxyzjn actually only mailboxes that own an alias can send emails to the reverse-alias. The problem is email spoofing (https://en.wikipedia.org/wiki/Email_spoofing) is really easy and currently SimpleLogin relies on SPF check as a form of authentication. As the reverse-alias is currently impossible to guess, the chance of this attack is almost 0.  Using a formula-based reverse-alias opens the attack possibilities.
