### ISSUE TITLE
Service findthatlead.com indexes your domain

### ISSUE THREAD

**Issue by C0d3r-h1dd3n** [simple-login/app#1871]
Hello!
Service findthatlead.com indexes your domain ([screenshot](https://github.com/simple-login/app/assets/144337341/bd7d87b4-3fbc-4df1-b89d-d61909e14e53)).

Please contact the findthatlead.com team with a request to exclude your domains from the search as well. They exclude all domains that are using to create personal addresses (but they need an official request).

Also they are indexing ALL SimpleLogin and ProtonPass domains. Here is the list of indexed domains:

```
protonmail.ch
proton.me
pm.me
simplelogin.com
silomails.com
slmails.com
simplelogin.fr
aleeas.com
slmail.me
8shield.net
dralias.com
passinbox.com
passfwd.com
passmail.com
passmail.net
simplelogin.co
simplelogin.io
```

Test login information (you can use it whatever you like, it is disposable):
[Link](https://drive.proton.me/urls/BVMKAQ1B4W#m2czNJ32E8CG) (Password: simplelogin)

Please contact them to resolve this as soon as possible!
Thank you for your reply!

@nguyenkims, can you please take a look?

**Comment by acasajus** [comment]
We've requested to stop the indexing. Thanks for pinging us :+1:
