### ISSUE TITLE
[Self-Hosted] Bounced Emails at Microsoft

### ISSUE THREAD

**Issue by springcomp** [simple-login/app#1875]
Sorry for off-topic issue but I’m trying my luck.

I’m self-hosting SimpleLogin and uses a custom domain.

I have been hosting my own email server for more than ten years now – and only recently switched to SimpleLogin – and have found myself needing to change domain every so often as Microsoft puts my own domain in its block list. This is like a cat and mouse game that has been going on seemingly forever. 

The error message is :

> 550 5.7.1 Unfortunately, messages from [IP.IP.IP.IP] weren't sent. Please contact your Internet service provider since part of their network is on our block list (S3150). You can also refer your provider to http://mail.live.com/mail/troubleshooting.aspx#errors.

Is there any way to understand what I’m doing wrong ?

**Comment by nguyenkims** [comment]
This error means your email has been bounced by outlook server. You can create a ticket with them to unblock it by using the link mentioned on https://discourse.mailinabox.email/t/guide-how-to-unblock-from-microsoft-hotmail-live/7779

**Comment by springcomp** [comment]
Thanks tons.

That looks like it will help solve this issue for me.
