### ISSUE TITLE
[Feature request] Make it easy to block sender

### ISSUE THREAD

**Issue by wAuner** [simple-login/app#188]
Maybe I'm missing something, but I was expecting something like a block button to no longer forward emails from that address. 

When I see the list of emails that have been forwarded for that alias (web and app) I'd like to be able to click that email and get options for this sender, especially the option to block further mails (e.g. newsletters).

At the moment it is not clear to me how any emails can be blocked or what would increase the Email blocked counter.

**Comment by nguyenkims** [comment]
That's a good idea indeed! I just created https://trello.com/c/qvx1JGq6/74-able-to-block-a-specific-sender in our roadmap.

> At the moment it is not clear to me how any emails can be blocked or what would increase the Email blocked counter.

Currently an email is blocked when the alias is blocked.
