### ISSUE TITLE
[Feature request] Ability to clear the logs / privacy improvement

### ISSUE THREAD

**Issue by wAuner** [simple-login/app#189]
I'd like to be able to (automatically) clear the logs of all the emails that have been forwarded. 
Ideally I'd be able to do it both manually (for example the flush logs function in pihole) and automatically, such as delete all logs that are older than 7 days.

**Comment by wAuner** [comment]
also, given that this is primarily a privacy enhancing service, there should be an option to don't log anything in the firstplace as well.

**Comment by nguyenkims** [comment]
@wAuner I just created this ticket in our roadmap https://trello.com/c/pFEvTjMt/73-able-to-disable-email-log, feel free to vote on it to make it happen sooner.

The email log system is also used to prevent abuses/spambots so it can't be disabled entirely.
