### ISSUE TITLE
You published private key!

### ISSUE THREAD

**Issue by QW21WQ** [simple-login/app#1904]
Hello!

You had published the private key:
https://github.com/simple-login/app/blob/master/local_data/private-pgp.asc

It can cause a lot of security problems!

@acasajus and @nguyenkims

**Comment by nguyenkims** [comment]
@QW21WQ this is actually a test key used in https://github.com/simple-login/app/blob/bcc/tests/test_pgp_utils.py#L47 

We don't use it in production :)

**Comment by QW21WQ** [comment]
Oh, I’m sorry :(

Thank you!
