### ISSUE TITLE
Some “bad” words

### ISSUE THREAD

**Issue by ghost** [simple-login/app#1905]
Hello!

I think you should remove this words as they can trigger someone. It is not a best idea to pick the topic of them:

First:
https://github.com/simple-login/app/blob/master/local_data/words.txt#L92C9-L92C9

https://github.com/simple-login/app/blob/master/local_data/words.txt#L378 - an insult

https://github.com/simple-login/app/blob/master/local_data/words.txt#L379 - an insult

https://github.com/simple-login/app/blob/master/local_data/words.txt#L449 - an insult

https://github.com/simple-login/app/blob/master/local_data/words.txt#L3343 - insult

https://github.com/simple-login/app/blob/master/local_data/words.txt#L3360 - insult

@acasajus and @nguyenkims

**Comment by nguyenkims** [comment]
Thanks, can you please make a PR to remove these words?

**Comment by Tctxtvu** [comment]
@nguyenkims

**Comment by nguyenkims** [comment]
Thanks, the PR has been merged.
