### ISSUE TITLE
Can not creating more then 5 subdomains even if the MAX_NB_SUBDOMAIN has been set.

### ISSUE THREAD

**Issue by thelittlerocket** [simple-login/app#1920]
Hi there,

I am not sure if this is a bug or not, but after changing the ```MAX_NB_SUBDOMAIN``` from 5 to 50 in the environment file, alter the value "Subdomain Quota" in the database, pull down containers, do migration, init, then start up all containers, but the limit still in place, the section of creating new subdomain are gray out, thus creating new subdomain is not possible,

would like to know if there is any way that I can create more than 5 subdomains. 
I found ```current_user.subdomain_quota```, but not found where the value has been given.
Thanks,

**Comment by nguyenkims** [comment]
Currently the `MAX_NB_SUBDOMAIN` is hardcoded and can't be changed using the env file:
https://github.com/simple-login/app/blob/new-self-host-version/app/config.py#L102
