### ISSUE TITLE
SimpleLogin websites problems report

### ISSUE THREAD

**Issue by ghost** [simple-login/app#1996]
Hi!

Your website is somewhat crooked.

For example:
On this page https://simplelogin.io/ you have link “Why SimpleLogin is not disposable mail” ([screenshot](https://github.com/simple-login/app/assets/155532221/87f8631c-4c1c-446e-9faa-56855dcade07)
) but on this page https://simplelogin.io/temporary-email/ you wrote that SL is disposable mail ([screenshot](https://github.com/simple-login/app/assets/155532221/6a4c6695-719b-43cd-9e7c-8f7d98ed0f74))

I don’t think it is good.

Also footers are way too difficult on https://simplelogin.io/temporary-email/ and https://simplelogin.io/

Screenshots:
1. [First screenshot](https://github.com/simple-login/app/assets/155532221/bdd89200-ed71-4925-874b-273d8e14bef0)
2. [Second screenshot](https://github.com/simple-login/app/assets/155532221/6f915afd-a232-4448-9230-f7a8ee106e95)

Can you fix this?

**Comment by Gycuvuvuctxhv** [comment]
@acasajus @nguyenkims @cquintana92

**Comment by nguyenkims** [comment]
https://simplelogin.io/temporary-email/ should be removed now

**Comment by Ueri780** [comment]
@nguyenkims 
I can confirm fixing. You can close this issue
