### ISSUE TITLE
Gmail doesn't receive simple login emails

### ISSUE THREAD

**Issue by azhinu** [simple-login/app#210]
I tried to use  simplelogin.io and self-hosted version and got the same result. I can receive email confirmation message but not emails from simple login aliases. Everything works well if I use yandex mail as mailbox for simple login. Also I tried to setup email forwarding from yandex mail to Gmail and this way I cannot receive emails from simple login alias at my Gmail inbox.

**Comment by nguyenkims** [comment]
@azhinu Does your setup look like the following?

- mailbox used on SimpleLoign: Yandex
- all emails arrived at the Yandex are forwarded to Gmail

SimpleLogin enforces the SPF, DKIM, DMARC that is not compatible with "old" forwarding technics like the one used to automatically forward emails between different email services.

Any reason that you don't want to use your original mailbox Gmail in SimpleLogin?

**Comment by azhinu** [comment]
I tried to use Gmail and emails doesn't arrive at Gmail inbox. I tried to use forwarding from Yandex to Gmail just for testing purposes.

**Comment by nguyenkims** [comment]
That's strange as we never had an issue with Gmail 🤔
Can you use your Gmail to receive/send emails? Sometimes the emails are bounced if your Gmail is full or receive too many emails.
In any case using email service auto-forwarding is not compatible with SimpleLogin (and probably other services that enforce email security standards).

**Comment by azhinu** [comment]
Tried simplelogin.io again. Forwarded emails counter displays that email has been forwarded but I didn't receive it at Gmail. When I tried to remove Gmail from simple login mailboxes and add it again, I successfully received a confirmation email.
In self-hosted version I got the same result. I can receive a confirmation email but when I try to receive email from alias it doesn't arrive.
Postfix logs show that email has been sent.

postfix/qmgr[12660]: 57BC824389: from=<my-testing-email>, size=3287, nrcpt=1 (queue active)
postfix/smtpd[18835]: disconnect from forward103o.mail.yandex.net[37.140.190.177] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
postfix/smtpd[18835]: connect from unknown[240.0.0.4]
postfix/smtpd[18835]: 326A324739: client=unknown[240.0.0.4]
postfix/cleanup[18829]: 326A324739: message-id=<CAGKfJLteXbSE1RAkSCXvzDoruWN5Lh+OmdNFmDj1ikX62042Eg@mail.gmail.com>
opendkim[12826]: 326A324739: s=dkim d=scribable.ml SSL 
postfix/qmgr[12660]: 326A324739: from=<reply+phmmntkileoszamuolxrreryxoaqlz@my-server-domain>, size=3879, nrcpt=1 (queue active)
postfix/smtp[18833]: 57BC824389: to=<cannonier_sophene@my-server-domain>, relay=127.0.0.1[127.0.0.1]:20381, delay=1.7, delays=0.65/0.11/0.02/0.93, dsn=2.0.0, status=sent (250 Message accepted for delivery)
postfix/smtpd[18835]: disconnect from unknown[240.0.0.4] ehlo=1 mail=1 rcpt=1 data=1 commands=4
postfix/qmgr[12660]: 57BC824389: removed
postfix/smtp[18833]: Trusted TLS connection established to gmail-smtp-in.l.google.com[74.125.140.26]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (P-256)
postfix/smtp[18833]: 326A324739: to=<my-gmail-email>, relay=gmail-smtp-in.l.google.com[74.125.140.26]:25, delay=1.2, delays=0.29/0.07/0.49/0.36, dsn=2.0.0, status=sent (250 2.0.0 OK  1590479012 71si13999379wmb.184 - gsmtp)
postfix/qmgr[12660]: 326A324739: removed

**Comment by nguyenkims** [comment]
@azhinu that's strange indeed ... if Gmail returns 250, the email should show up in your inbox. 

Emails sometimes have delays though (due to the greylisting used by some email services).

Do you use the latest SimpleLogin version which is `3.1.0`?

**Comment by azhinu** [comment]
@nguyenkims for some reason I didn't try to use another Gmail account. I just tried another Gmail and everything works well. Sorry for the trouble.
