### ISSUE TITLE
Default Random Alias Domain

### ISSUE THREAD

**Issue by FozzieHi** [simple-login/app#213]
Hello,

Great app but how do I set it so that when a random alias is created it uses my domain by default?

**Comment by nguyenkims** [comment]
Currently the random alias is created using the default SimpleLogin domain indeed. You can follow this ticket https://trello.com/c/yjKnAuuq/31-able-to-use-random-alias-generator-on-custom-domain to know when the feature is available. Feel free to vote on it to  make it happen sooner :)
