### ISSUE TITLE
Remove strict MX priority requirement.

### ISSUE THREAD

**Issue by FozzieHi** [simple-login/app#217]
Currently there's a strict MX priority requirement for:
mx1.simplelogin.co - 10
mx2.simplelogin.co - 20

I don't think it matters what priorities these are, only that mx1 has a lower priority than mx2, this priority requirement should be removed.

**Comment by nguyenkims** [comment]
Using 10 and 20 as priorities seems to be an implicit convention in mail services use these numbers. Can you tell me more about your scenario in which you don't want to set the priority to 10 or 20? For info, the MX records can only point to the same email service.

**Comment by FozzieHi** [comment]
I don't think it matters if it's 10, 20 or 1, 2 it both achieves the same goal.

I don't have a specific scenario but people may try to just add MX records with whatever priority they want and it might be a brief annoyance that they have to use 10 or 20.

**Comment by nguyenkims** [comment]
@FozzieHi I see, I just added this ticket on the open roadmap https://trello.com/c/7Gl1KXst/84-allow-other-priorities-in-mx-record, feel free to vote on it to make it happen sooner :).
I close this Github issue then.
