### ISSUE TITLE
SMIME support

### ISSUE THREAD

**Issue by celogeek** [simple-login/app#2174]
Hi,

First, thanks a lot of this product. It's fantastic.

I was looking for a way to secure the mail between the server and the mail provider. I see PGP support, which works nicely with ProtonVPN and if we have a client like Thunderbird on desktop.

I use Apple Mail, which support SMIME as encryption/sign. It's an alternative to PGP to secure mail: https://fr.wikipedia.org/wiki/S/MIME

Do you think it's possible to add the support for SMIME into SimpleLogin ?

**Comment by nguyenkims** [comment]
For info we have a pending pull request to add support for S/MIME https://github.com/simple-login/app/pull/1946

**Comment by celogeek** [comment]
oh yes, see it, closing

**Comment by 1inh** [comment]
can we get some support for the PR please? It's been untouched for almost 2 years now
