### ISSUE TITLE
Clarifying CONTRIBUTING instructions: rye dependencies

### ISSUE THREAD

**Issue by springcomp** [simple-login/app#2186]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**

First-time contributors MAY have a difficult time setting up their development environments.

I have made sure to install all the prerequisite software (seems Docker is not listed as a prerequisite).
After a fresh clone, the following command fails:

```bash
rye sync
```

With error:

```
Initializing new virtualenv in /root/app/.venv
Python version: cpython@3.12.4
Generating production lockfile: /root/app/requirements.lock
error: could not write production lockfile for project

Caused by:
    project from '/root/app' has no name
```

I then modified `pyproject.toml` and added a leading section:

```patch
+ [project]
+ name = 'app'
```

But re-running the `rye sync` command still fails:

```
Reusing already existing virtualenv
Generating production lockfile: /root/app/requirements.lock
error: Failed to download and build: `app @ file:///root/app`
  Caused by: Failed to build: `app @ file:///root/app`
  Caused by: Build backend failed to build wheel through `build_editable()` with exit status: 1
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 11, in <module>
AttributeError: module 'poetry.masonry.api' has no attribute 'build_editable'
---
error: could not write production lockfile for project

Caused by:
    Failed to run uv compile /tmp/.tmpExrMcQ/requirements.txt. uv exited with status: exit status: 2
```

**Expected behavior**

The `CONTRIBUTING.md` file should have clarifying instructions.
I’m happy to submit pull requests to that effect.

**Comment by nguyenkims** [comment]
We have reverted rye for now as we also experience some issues with this tool.
