### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by BeecherNetworks** [simple-login/app#220]
When I register a new user, the `created_at` time in `account_activation` is set to an hour back from current, and the expired time is set to current, so I can never get activated (without updating `activated` manually). I've tried setting `TZ` on all of the containers, changing the timezone in the VPS to `UTC`, all to no avail. Where are these times coming from?

Oh, and what's `is_admin` in the user table? Is there an admin interface?

You've made incredible progress on SL BTW, well done. [I first came across it](https://www.reddit.com/r/selfhosted/comments/eqlrbz/simplelogin_a_selfhosted_solution_to_protect_your/feza8iy/) when you announced it on r/selfhosted, and it's come along by leaps and bounds since.

Please consider adding PayPal to your Sponsor button so I can add a once-off donation. I'm not ready to commit to monthly. :)

**Comment by nguyenkims** [comment]
@BeecherNetworks SimpleLogin uses UTC timezone so I guess your server timezone is UTC+1. Do you have the correct time on the server? Some servers require setting up `NTP` to correctly sync time. 

And thanks for the kind words! I have just updated the Sponsor to add the Paypal option :).

**Comment by BeecherNetworks** [comment]
I changed the timezone in the VPS to UTC though, and I've just rebooted to check again, no go:

```
root@yy:~$ date
Mon Jun  1 11:46:46 UTC 2020
root@yy:~$ cat /etc/timezone
Etc/UTC
```

```
simplelogin=# select * from activation_code;
 id |         created_at         | updated_at | user_id |              code              |          expired
----+----------------------------+------------+---------+--------------------------------+----------------------------
  1 | 2020-05-31 23:36:45.356688 |            |       1 | niejumgjmuduyyuxmfnzdwhjuzegeh | 2020-06-01 00:36:45.356726
  2 | 2020-06-01 11:46:09.266881 |            |       2 | jhddfoqamnkejcyghpercunapcoonl | 2020-06-01 12:46:09.266927
```


Thanks, I'll make a donation later.

**Comment by BeecherNetworks** [comment]
Sorry, I should have added that the time now here is 12:48:33. I'm in Irish Standard time, which is currently Summertime, GMT+1. Is the browser time being detected perhaps?

**Comment by nguyenkims** [comment]
@BeecherNetworks I just made a test and the `activation_code.expired` is indeed in UTC. It should be `created_at + 1h`.

The browser time zone is not used here. If ever the timezone comes into play (which shouldn't be the case given all times in SimpleLogin are in UTC ..), this comes from the server. Could you please retry on another server and let me know how this goes?

**Comment by BeecherNetworks** [comment]
I'm afraid I don't have time to set up another server right now, however I've tried setting the VPS to UTC, and the Docker containers to Europe/Dublin, all to no avail. No matter what I do, the created time is set to an hour in the past, and the expired time to the current time.

**Comment by nguyenkims** [comment]
@BeecherNetworks I haven't been able to reproduce that on my VPS (AWS and UpCloud). I suspect the timezone issue comes either from the database or the host. What cloud provider are you using?

**Comment by BeecherNetworks** [comment]
The database container has the same TZ as everything else though. This is my own server in a data centre. Here's the dates from the top down, V4 is the server, YY is the VPS. IST is Irish Standard Time, which comes from the Europe/Dublin TZ.

```
root@v4:~$ date
Sun  7 Jun 14:54:04 IST 2020
root@yy:~$ date
Sun Jun  7 14:54:16 IST 2020
root@yy:~$ docker exec -it sl-db date
Sun 07 Jun 2020 02:54:25 PM IST
root@yy:~$ docker exec -it sl-app date
Sun Jun  7 14:54:28 IST 2020
root@yy:~$ docker exec -it sl-email date
Sun Jun  7 14:54:32 IST 2020
```

I wouldn't know where to start looking for this, can you get me started by telling me where the date comes from, i.e. is it generated by a script and fed to the database, or is it generated by the database using the PG equivalent of NOW() and NOW()+1? (I don't know PG.)

**Comment by BeecherNetworks** [comment]
Also, OT but how do you change "Son from SimpleLogin" in the notification emails?

**Comment by nguyenkims** [comment]
> Also, OT but how do you change "Son from SimpleLogin" in the notification emails?

You can set the variable `SUPPORT_NAME` to change that. By default, it's set to `Son from SimpleLogin` :)

**Comment by nguyenkims** [comment]
> The database container has the same TZ as everything else though. This is my own server in a data centre. Here's the dates from the top down, V4 is the server, YY is the VPS. IST is Irish Standard Time, which comes from the Europe/Dublin TZ.
> 
> ```
> root@v4:~$ date
> Sun  7 Jun 14:54:04 IST 2020
> root@yy:~$ date
> Sun Jun  7 14:54:16 IST 2020
> root@yy:~$ docker exec -it sl-db date
> Sun 07 Jun 2020 02:54:25 PM IST
> root@yy:~$ docker exec -it sl-app date
> Sun Jun  7 14:54:28 IST 2020
> root@yy:~$ docker exec -it sl-email date
> Sun Jun  7 14:54:32 IST 2020
> ```
> 
> I wouldn't know where to start looking for this, can you get me started by telling me where the date comes from, i.e. is it generated by a script and fed to the database, or is it generated by the database using the PG equivalent of NOW() and NOW()+1? (I don't know PG.)

The `created_at` time is set by default to `arrow.now()` https://github.com/simple-login/app/blob/6cccb450b027a7f8d56a5b45f664a8fe0ad0ce45/app/models.py#L40 with `arrow` being https://arrow.readthedocs.io/en/latest/

Can you run this command and compare the output time to the actual time?

```
docker exec -it sl-email python -c "import arrow; print(arrow.now())"
```

It should return something like `2020-06-07T22:08:40.176390+00:00` which is the current time of this comment.

**Comment by BeecherNetworks** [comment]
> You can set the variable `SUPPORT_NAME` to change that. By default, it's set to `Son from SimpleLogin` :)

Thanks for this. I'll reply to your other message tomorrow.

**Comment by BeecherNetworks** [comment]
Upgrading to the latest version has resolved this. Thanks for your time.

**Comment by nguyenkims** [comment]
@BeecherNetworks Glad that it works!

**Comment by BeecherNetworks** [comment]
Actually it doesn't, it worked the first time I logged in, and in the Firefox plugin, but when I tried to login with another browser today it told me the account wasn't activated. I'm the only one using it so I just activated it manually, but there's definitely something wrong there, I assume with the way I'm running it. I'll have another go off it next week.

**Comment by nguyenkims** [comment]
That's indeed a curious issue 🤔. Please let me know if you find some info!
