### ISSUE TITLE
Can't login to paid account

### ISSUE THREAD

**Issue by V8Qxdvixstjg3n7afA** [simple-login/app#227]
My password is indicated as incorrect, though I have not changed it recently. I logged in yesterday with no issues and sent several emails using my aliases. I submitted a request to reset the password and have not received any email to do so even though it has been a few hours.

**Comment by nguyenkims** [comment]
@V8Qxdvixstjg3n7afA can you please send your account email to hi@simplelogin.io so we can investigate?

**Comment by V8Qxdvixstjg3n7afA** [comment]
Thanks very much for the quick reply. Great service so far. Better than Blur in a lot of ways.

**Comment by V8Qxdvixstjg3n7afA** [comment]
Sent email.

**Comment by nguyenkims** [comment]
@V8Qxdvixstjg3n7afA I guess the issue is fixed now, should I close this issue?
