### ISSUE TITLE
Relay access denied (in reply to RCPT TO command)

### ISSUE THREAD

**Issue by pajd** [simple-login/app#229]
Hello,
I have SimpleLogin installed on my instance. Whenever I try to write to one alias, the server refuses to send the message with the following error: Relay access denied (in
   reply to RCPT TO command)

Did I miss something?

Thanks in advance for your help.

**Comment by mzch** [comment]
Do you set `relay_domains` and `transport_maps` to postfix/main.cf?

**Comment by nguyenkims** [comment]
@pajd can you paste here the Postfix and `sl-email` logs when you send an email to the alias? You can see the logs by `tail -f /var/log/mail.log` for Postfix and `docker logs -f sl-email` for `sl-email` container.

**Comment by pajd** [comment]
> @pajd can you paste here the Postfix and `sl-email` logs when you send an email to the alias? You can see the logs by `tail -f /var/log/mail.log` for Postfix and `docker logs -f sl-email` for `sl-email` container.

Thanks for your feedback. Here it is:

tail -f /var/log/mail.log:

Jun 17 17:22:21 pajd-simplelogin postfix/smtpd[23307]: connect from mout-p-101.mailbox.org[80.241.56.151]
Jun 17 17:22:21 pajd-simplelogin postfix/smtpd[23307]: NOQUEUE: reject: RCPT from mout-p-101.mailbox.org[80.241.56.151]: 554 5.7.1 <redirect@***.***l>: Relay access denied; from=<contact@pajd.info> to=<redirect@pajd.email> proto=ESMTP helo=<mout-p-101.mailbox.org>
Jun 17 17:22:21 pajd-simplelogin postfix/smtpd[23307]: disconnect from mout-p-101.mailbox.org[80.241.56.151] ehlo=2 starttls=1 mail=1 rcpt=0/1 data=0/1 rset=1 quit=1 commands=6/8

docker logs -f sl-email:
>>> URL: http://app.***.***
MAX_NB_EMAIL_FREE_PLAN is not set, use 5 as default value
Paddle param not set
>>> init logging <<<
2020-06-16 16:54:48,546 - sl - DEBUG - 1 - utils:11 - <module> - load words file: /code/local_data/words_alpha.txt
2020-06-16 16:54:49,208 - sl - DEBUG - 1 - email_handler:1118 - <module> - Start mail controller 0.0.0.0 20381

**Comment by nguyenkims** [comment]
From the log it seems the email has not reached the `sl-email` container that's the email handler. 

Have you setup the `/etc/postfix/pgsql-relay-domains.cf` and `/etc/postfix/pgsql-transport-maps.cf` https://github.com/simple-login/app/blob/3d0d42c8b3269e9922819cc04761ec7ffffe1838/README.md#L394 ?

**Comment by pajd** [comment]
Apologies for the delay in the answer. I had made a small mistake indeed in my domain name. It now works. Many thanks and sorry for not figuring this out myself!

**Comment by nguyenkims** [comment]
@pajd no worries, glad that everything is working now!
