### ISSUE TITLE
Spam emails not found when using docker and LOCAL_FILE_UPLOAD

### ISSUE THREAD

**Issue by inonio** [simple-login/app#231]
Because the email is saved by sl-email container, it's not accessible by sl-app, and so a 404 is returned when access the quarantine using the app and trying to download the email.

I was able to remedy it by adding this to the docker run commands for both containers:
```-v $(pwd)/sl-upload:/code/static/upload \```

**Comment by nguyenkims** [comment]
@inonio thanks for the info, this is indeed an issue! I have fixed this issue in this PR https://github.com/simple-login/app/pull/232
