### ISSUE TITLE
SQL "is_admin" entry 

### ISSUE THREAD

**Issue by dducted** [simple-login/app#241]
Hi,

I've seen the `is_admin` in the `users` table. I was just wondering what it does?

**Comment by nguyenkims** [comment]
@dducted this column is used to set a user to `admin`. As admin, you can login into the `{your SimpleLogin url}/admin` page. This page hasn't received any updates since long time though and I plan to remove it in future versions.

**Comment by dducted** [comment]
Oh OK, I see it now. Looks quite useful to me. Thanks.
