### ISSUE TITLE
Guide how to upgrade from 2.1.2->3.2.2

### ISSUE THREAD

**Issue by havedill** [simple-login/app#242]
Is there any guide how to move from version 2 up to version 3 without losing my database of emails?

**Comment by nguyenkims** [comment]
@havedill we have a doc on how to upgrade SimpleLogin here 
https://github.com/simple-login/app/blob/master/docs/upgrade.md

If you are running a version interior to 2.1.0, it's necessary upgrade first to 2.1.0, then to the latest version which is 3.2.2

**Comment by havedill** [comment]
Didn't see that, thank you very much
