### ISSUE TITLE
Bug: Global alias domains must not be allowed to be added as custom domains under users account

### ISSUE THREAD

**Issue by subhamagr** [simple-login/app#250]
Hi - I was just playing around with self-hosted simplelogin. So far - loving it! Thank you for this wonderful service!

I noticed one bug that users shouldn't be allowed to add domains which are already added as global alias domains.

Here's what I was able to do on my self hosted instance:

![image](https://user-images.githubusercontent.com/7915409/89312475-ec871100-d694-11ea-826c-1f6d02b47ef8.png)

As you see `ftmail.me` already exists as a global alias domain but still I was able to add the domain as custom domain. This would defeat the purpose as the global domains would already contain the correct records and hence anybody (using the selfhosted version) would be able to add the domain as their own and create alias with nice "usernames" even when `DISABLE_ALIAS_SUFFIX=0` .

I wonder if adding all the global domains into the admin account would be a work around so that other users are unable to add as their own?

**Comment by nguyenkims** [comment]
@subhamagr thanks for reporting this error! It should be fixed in https://github.com/simple-login/app/pull/252

This fix will be included in our next Docker image release (v3.3.0) :)

**Comment by subhamagr** [comment]
@nguyenkims Any estimation as to by when we can expect v3.3.0?

**Comment by nguyenkims** [comment]
@subhamagr we plan to release v3.3.0 when the number of features/bugs are more important or when a critical bug happens.
In the meantime, I'd suggest you adding this default domain as a custom domain as that would prevent someone else from adding this domain :).

**Comment by subhamagr** [comment]
Yup I did that already. Thanks, Son!
