### ISSUE TITLE
Documentation for enabling the crontab

### ISSUE THREAD

**Issue by subhamagr** [simple-login/app#253]
I see there are no documentation as to how to enable the cron jobs. I have set the `ADMIN_EMAIL` environment variable but haven't received any emails (stats) since 4 days. 

How to enable the cron jobs?

**Comment by nguyenkims** [comment]
@subhamagr the cronjob is rather for us as they send information about how well the business is doing :). It doesn't contain much useful information for a self-hosted instance I think :).

**Comment by subhamagr** [comment]
Yeah it makes sense. Thanks!
