### ISSUE TITLE
Improving the name of emails from Chrome/Mozilla Extension

### ISSUE THREAD

**Issue by marreromarco** [simple-login/app#255]
Dear Friends,

Recently this was published on a Human Right's website:
https://www.debito.org/?p=16201

There seems to be a way to reduce the name of emails already on SimpleLogin. However, would it be possible from the Chrome/Mozilla app to create permanente address that are also shorter ?

In this case, the following email was used:

debitoorg.classaction.petrographers@simplelogin.co

It would have been better shorter but the word "petrographers" was not possible to change it. Could we improve that "issue" ?

Thanks ! Good luck in your project !

**Comment by nguyenkims** [comment]
@marreromarco the `petrographers` is an alias *suffix* that is generated automatically for aliases created on the common domains (simplelogin.co/simplelogin.fr/...) and its goal is to avoid a user from having all the "nice" aliases :). You can remove this limit by using `directory` feature (so you can create aliases like `{my-directory}+{anything}@simplelogin.co with `{my-directory}` replaced by your directory and `{anything}` can be anything :).

If you have your own domain, this automatic suffix is also automatically removed.

**Comment by marreromarco** [comment]
Thanks for the explanation. Some people in Japan have opened new accounts ! :D 

This "Issue" can be closed. In the future, some short videos might be done to make it easier for users !

Thank you very much ! Keep up your good work !

**Comment by nguyenkims** [comment]
@marreromarco yes making the product easier to use is definitely in the pipeline!
