### ISSUE TITLE
Ed25519 DKIM

### ISSUE THREAD

**Issue by FozzieHi** [simple-login/app#256]
I notice in the documentation RSA 1024 is used, is there support for Ed25519?

**Comment by nguyenkims** [comment]
The library we're using to generate the DKIM signature https://pypi.org/project/dkimpy/ seems to have support for Ed25519, we never tried it before though. The code that creates the DKIM signature is https://github.com/simple-login/app/blob/38a6bcc4619b3359988b7965f5870cce2598e432/app/email_utils.py#L289 and it seems that if the key is Ed25519, we can just set the `signature_algorithm` argument to `b'ed25519-sha256'`.
