### ISSUE TITLE
reset password no email send

### ISSUE THREAD

**Issue by LagSeeN** [simple-login/app#257]
someone foud problem on [reddit](https://www.reddit.com/r/Simplelogin/comments/i6t2y7/how_long_does_it_take_to_get_a_password_reset_in/)
and i try to reset password and wait 10 min no email reset password to me

**Comment by nguyenkims** [comment]
We have discovered recently a bug that prevents the email component (`email-handler`) from starting properly, leading to some delayed emails. The bug has been fixed now, could you please retry?

**Comment by LagSeeN** [comment]
i try again now but no mail again

**Comment by nguyenkims** [comment]
@LagSeeN can you retry now please? I just tested and received the reset password email.

**Comment by LagSeeN** [comment]
@nguyenkims Ok i test again it work. I received the reset password email
