### ISSUE TITLE
Update Postfix Config File

### ISSUE THREAD

**Issue by FabioWidmer** [simple-login/app#261]
I recently tried self hosting SimpleLogin. Everything worked perfectly after following your guide.

After a few emails sent I noticed that TLS encryption is not getting used when sending emails. After replacing the line it worked but not for the internal TLS:
`smtpd_use_tls=yes`
with
`smtpd_tls_security_level=may`

Postfix updated their config. Could you please post your current configuration and update the guide? I assume there are more things that changed. Thank you!

**Comment by FabioWidmer** [comment]
@nguyenkims I just noticed that with the self hosting guide provided an alias domain is not getting accepted by Postfix (Relay access denied). In the `.env` file I added `OTHER_ALIAS_DOMAINS`with one more domain but I haven't changed anything in the Postfix `main.cf` file. I assume something has to be changed there too. If possible I would really appreciate to see your Postfix config file to compare and see what has to be updated to work with the latest Postfix version. Thank you!

**Comment by subhamagr** [comment]
@FabioWidmer Even I faced the issue with other alias domains. Check my comment on this issue: https://github.com/simple-login/app/issues/249

**Comment by nguyenkims** [comment]
@FabioWidmer ah we use the same postfix files that contains a single domain. When adding new domains to `OTHER_ALIAS_DOMAINS`, we made sure to add these domains as custom domains as well so Postfix regconize them in `SELECT domain FROM custom_domain` part of the query.

**Comment by nguyenkims** [comment]
@FabioWidmer you're right about the TLS config, I've updated the README to use `smtpd_tls_security_level` instead of `smtpd_use_tls` and also add `smtp_tls_security_level`:

https://github.com/simple-login/app/commit/2a38d7c5fa6d3a97e2053dbf4b0c5c2b864d7aaf

**Comment by FabioWidmer** [comment]
@subhamagr @nguyenkims Thank you very much for the solutions! Is it possible to use TLS between the Docker container and local Postfix? I found this env config: `POSTFIX_SUBMISSION_TLS` But when set to `true` all emails get rejected.

**Comment by FabioWidmer** [comment]
Was able to also use TLS for internal communication too ([Website](https://www.faqforge.com/linux/how-to-enable-port-587-submission-in-postfix/)). Probably the guide should be extended with enabling port `587` for submission and setting `POSTFIX_SUBMISSION_TLS` to `true`.

**Comment by nguyenkims** [comment]
@FabioWidmer the emails are sent in cleartext from Postfix to `email_handler` and currently `email_handler` doesn't have TLS enabled. 

The `POSTFIX_SUBMISSION_TLS` option is rather for debugging when `email_handler` is run locally whereas Postfix is run on a server: the port 25 is usually blocked by ISP so we use this option as a workaround when developing :).

**Comment by FabioWidmer** [comment]
@nguyenkims Okay, I would still suggest to remove the `#` in front of `submission inet n - n - - smtpd` in the file `/etc/postfix/master.cf`. This enabled port `587` as submission port and `POSTFIX_SUBMISSION_TLS` can be used perfectly. This makes the Thunderbird Add-on [Paranioa](https://addons.thunderbird.net/thunderbird/addon/paranoia/) happy :smile:.

**Comment by nguyenkims** [comment]
@FabioWidmer I just created this PR https://github.com/simple-login/app/pull/271 :)

**Comment by nguyenkims** [comment]
Solved in https://github.com/simple-login/app/pull/271
