### ISSUE TITLE
Question - How to prevent fowarded mails to end up in SPAM

### ISSUE THREAD

**Issue by Stinosko** [simple-login/app#265]
Hello,

I have a question on how to prevent my email that arrive from simple login server to end up in my spam folder? 
I have custom domain maybe it's to with that? How would i improve to get it trusted by my email carrier? 

Tried setting up custom rules when email arrive from my custom domain to not flag as spam but it still does.

Kind regards,

Stinosko

**Comment by nguyenkims** [comment]
Sometimes an email service can put an email into Spam folder even if the email respects all email delivery standard and its content is legitimate. This happens especially for a new domain. The false positive spam rate is going to decrease over time (i.e. less emails sent to your domain are put into Spam folder). 

You can create filters to whitelist emails from SimpleLogin server to avoid them being classified as spam https://simplelogin.io/help/

Apart from that; there's not much you can do here except making sure to block aliases that receive too many spammy emails.

**Comment by Stinosko** [comment]
Thank you for the info!
I do still have a question: when using a custom domain, does the filter need to be on the @mydomain.com of also still on the @simplelogin.co and @simplelogin.io?

**Comment by nguyenkims** [comment]
@Stinosko the emails are sent from the `reverse-alias` which uses simplelogin.co domain so the filter should use simplelogin.co domain indeed.

**Comment by Stinosko** [comment]
I'll edit the email-rules and hope it is sufficient!

I'll close the issue 🙂
