### ISSUE TITLE
Not receiving signup confirmation emails

### ISSUE THREAD

**Issue by pojhm91c7iwk** [simple-login/app#267]
I have a fresh self-hosted simple-login instance on aws (followed steps on https://github.com/simple-login/app). After the installation step, I was greeted by the login screen on my domain (https://app.mydomain.com/).

I signed-up using few different emails but none of the email received sign-up confirmation (so I can not use my hosted instance at all). How can I even troubleshoot this issue?

**Comment by pojhm91c7iwk** [comment]
Update: After my manually updated db to "verify" my email, I am still not receiving any emails to my signed-up email. The dashboard shows:

Aliases - 1
Forwards - 2

But I have received no emails.

**Comment by nguyenkims** [comment]
@pojhm91c7iwk is this issue still there? Please feel free to start from scratch the self-hosting instructions to make sure no step is missed.

**Comment by pojhm91c7iwk** [comment]
I started completely from scratch self-hosting it and running again the same issue of connection time out. Please help.

**Comment by nguyenkims** [comment]
From the other issue, I suspect that your cloud provider or ISP blocks the port 25. Some ISP do that to avoid a computer from becoming a [open relay](https://en.wikipedia.org/wiki/Open_mail_relay) (due to a virus for example).

**Comment by pojhm91c7iwk** [comment]
This is on AWS and Port 25 is Open. 

Can anyone replicate this on AWS and see if they are able to replicate the issue?

**Comment by Jared0430** [comment]
I was having the same issue on AWS, turns out they block all outbound traffic on port 25 unless you request they open it for you https://aws.amazon.com/premiumsupport/knowledge-center/ec2-port-25-throttle/
