### ISSUE TITLE
Links get changed

### ISSUE THREAD

**Issue by vlenzr** [simple-login/app#269]
Links are changed from time to time. It seems that each time a point is added at an undefined position, which makes the link invalid. I do not host the service myself and do not use PGP encryption.
An example of a link:

http://news..domain.com/u/nrd.php?p=thisisanexampledomain

I can forward an affected email if desired.

**Comment by nguyenkims** [comment]
@vlenzr What link you are referring to? Do you know how to reproduce this issue?

**Comment by vlenzr** [comment]
@nguyenkims Sorry, it was a bug in my setup so it was no problem for SimpleLogin. Thanks anyway!

**Comment by nguyenkims** [comment]
@vlenzr no worries, I'll close this issue then :)
