### ISSUE TITLE
DKIM signature is not valid

### ISSUE THREAD

**Issue by dducted** [simple-login/app#275]
Hi there,

I followed your guide and set DKIM keys as well as created DNS entries accordingly however it seems they are invalid. Any idea what might've caused it? I am using ProtonMail as my main email. SimpleMail runs on a subdomain.

DNS entries:
![img](https://i.imgur.com/bbFd1Bw.png)

Please find the results below:
![img](https://i.imgur.com/PV0HJK0.png)

**Comment by nguyenkims** [comment]
If the DKIM header is added by SimpleLogin, this means the DKIM key is taken into account by the server. I suggest however to retry the DKIM setup as it's very easy to have a typo in this step. And make sure that the DNS has propagated correctly.

**Comment by dducted** [comment]
I have done that a few times, creating new pub and priv keys. Making sure DNS entries are correct as well as propagated. 

After creating new piv and pub keys, do I have to restart docker or create new dockers? Did I miss any other step aside from creating new priv and pub keys and update DNS?

Thanks.

**Comment by nguyenkims** [comment]
> After creating new piv and pub keys, do I have to restart docker or create new dockers? Did I miss any other step aside from creating new priv and pub keys and update DNS?

I don't think it's necessary to restart the containers but just to be sure, feel free to restart the containers after any config change :).

**Comment by dducted** [comment]
I have done all of that but my DKIM certs are still not being accepted ... Odd.

**Comment by dducted** [comment]
A full container restart seems to do the trick here.
