### ISSUE TITLE
Bugged firefox extension 

### ISSUE THREAD

**Issue by bitog** [simple-login/app#276]
Hi,

I am using the firefox extension and changed my domain. I tried logging out but it seems to be glitched. I cant log out anymore. Deleting the extension isnt helping either. Any idea what I could do? I was hoping I could maybe reset the extension somehow?

Thanks.

**Comment by nguyenkims** [comment]
@dducted we have released a new version v2.2.0 that would reset all the data when you uninstalls the extension. Could you retry?

**Comment by dducted** [comment]
I tried removed as reinstalled the extension but it is still glitched and I can't log out.

**Comment by nguyenkims** [comment]
@bitog can you retry on the latest version which is 2.3.2? I have just tested and I can logout and reinstall the extension.

![image](https://user-images.githubusercontent.com/3167780/92991613-6e185d00-f4e5-11ea-9c17-4283dcf078d2.png)

**Comment by nguyenkims** [comment]
@bitog did you have a chance to try the latest extension version?
