### ISSUE TITLE
{Feature Request}

### ISSUE THREAD

**Issue by dhammel** [simple-login/app#278]
Hello,

I was thinking about the directory mode and realized that it might be a good idea to implement a method to block/unblock a directory. This way no further aliases can be created from said directory, but NOT deleting or disabling any aliases from that directoey.

As the email alias which contains directory name may be public, or breached from a company or any other cases what if someone started using your directory name in the same format  creating you a bunch of random aliases on your account? Blocking it would give a user the ability to prevent this if noticed.

Thank you :)

**Comment by nguyenkims** [comment]
I created this ticket on SimpleLogin roadmap https://trello.com/c/vOhEeR3E/115-able-to-enable-disable-a-directory that would correspond to the feature you describe. Feel free to vote on it to make it happen sooner :).

( We are using trello for feature request instead of GitHub )
