### ISSUE TITLE
Possible to run simplelogin behind a mail relay like mailgun?

### ISSUE THREAD

**Issue by ghost** [simple-login/app#279]
If it's doable for self-host, it will eliminate most of the problems of mail going into spam or getting blocked.

**Comment by nguyenkims** [comment]
You can use another SMTP server for sending emails by setting this `POSTFIX_SERVER` parameter:
https://github.com/simple-login/app/blob/637bc569eb7b70aee154b5b12035e35fd3e9a450/example.env#L63

It's btw possible to send emails via AWS SES https://github.com/simple-login/app/blob/a4d5f5aab1b2a1b732ff2d674b792ce160748314/docs/ses.md#L1-L0
