### ISSUE TITLE
Help with initiating (creating and sending) an email

### ISSUE THREAD

**Issue by zdat** [simple-login/app#280]
Just signed up and everything seems good with forwarding/receiving,
but I can't really see how I initiate an email (create and send, I send the first email, NOT reply).

Also, all emails are forwarded to an alias ON MY EMAIL PROVIDERS side. Would this cause problems? I do have the ability to send from that alias, so there shouldn't be any problems?

Thanks.

**Comment by zdat** [comment]
There's instructions on the alias page; "how to use" when you press "send mail". It's quite small so I missed it.

Also I did some self testing and it does seem possible to do what I stated, so that's great!

**Comment by nguyenkims** [comment]
@zdat glad that you found how to send emails from alias. I have made a small change to always display how to create a reverse-alias.
