### ISSUE TITLE
Inbound encryption

### ISSUE THREAD

**Issue by zdat** [simple-login/app#284]
So the email provider I am forwarding to already provides inbound encryption. I'd rather have my email providers inbound encryption so I am only managing 1 PGP key instead of 2.

Are there any drawbacks to this? Is it in any way less secure if I don't use SimpleLogins inbound encryption? Would it be better as the emails are SENT encrypted from SimpleLogin's side rather than being encrypted when RECEIVED at my email providers side (and not encrypted in transit)?

Also I had both the email provider's inbound encryption selected and SimpleLogin's selected to see what would happen and SimpleLogin's seems to take priority with no issues, so I could have them both going at once if need be.

**Comment by nguyenkims** [comment]
The end result of both options is the same: the email is stored encrypted. With SimpleLogin encrypting the email, the email is encrypted a step earlier but I'm not sure there's any real difference in practice. 

So I think the choice is up to you :).
