### ISSUE TITLE
Cannot assign requested address

### ISSUE THREAD

**Issue by cradcore** [simple-login/app#286]
Hey there,

I am trying to run the app, and am having issues. I have followed the instructions, but am running into an error. When I run the docker container for email_handler.py and try and send a test email using swaks 

`swaks --to e1@d1.localhost --from hey@google.com --server 127.0.0.1:20381`

I get the following error:
`=== Trying 127.0.0.1:20381...`
`=== Connected to 127.0.0.1.`
`<-  220 93a9342e92a9 Python SMTP 1.2+`
` -> EHLO localhost.localdomain`
`<-  250-93a9342e92a9`
`<-  250-SIZE 33554432`
`<-  250-8BITMIME`
`<-  250-SMTPUTF8`
`<-  250 HELP`
` -> MAIL FROM:<hey@google.com>`
`<-  250 OK`
` -> RCPT TO:<e1@d1.localhost>`
`<-  250 OK`
` -> DATA`
`<-  354 End data with <CR><LF>.<CR><LF>`
` -> Date: Wed, 16 Sep 2020 16:58:08 -0600`
` -> To: e1@d1.localhost`
` -> From: hey@google.com`
` -> Subject: test Wed, 16 Sep 2020 16:58:08 -0600`
` -> Message-Id: <20200916165808.029014@localhost.localdomain>`
` -> X-Mailer: swaks v20170101.0 jetmore.org/john/code/swaks/`
` -> `
` -> This is a test mailing`
` -> `
` -> .`
`<** 421 SL Retry later`
` -> QUIT`
`<-  221 Bye`
`=== Connection closed with remote host.`

In my docker logs, I see the following:

`2020-09-16 22:39:31,064 - sl - INFO - 1 - email_handler:1472 - _handle - ===>> New message, mail from <>, rctp tos ['root@<my-domain>.com'] `
`2020-09-16 22:39:31,065 - sl - ERROR - 1 - email_handler:1462 - handle_DATA - email handling fail <> -> ['root@<my-domain>.com']`
`Traceback (most recent call last):`
`  File "email_handler.py", line 1456, in handle_DATA`
`    ret = await self._handle(envelope)`
`  File "email_handler.py", line 1479, in _handle`
`    smtp = SMTP(POSTFIX_SERVER, POSTFIX_PORT or 25)`
`  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__`
`    (code, msg) = self.connect(host, port)`
`  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect`
`    self.sock = self._get_socket(host, port, self.timeout)`
`  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket`
`    self.source_address)`
`  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection`
`    raise err`
`  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection`
`    sock.connect(sa)`
`OSError: [Errno 99] Cannot assign requested address`

I noticed this because after starting up both the web client and the mail handler, when I would try to create a new user in the web app, it tells me my email is incorrect. Checking the logs, it shows that it times out

I should note: I CAN send email using swaks if I don't point the server at the simple_login container

**Comment by nguyenkims** [comment]
@cradcore from the log, it seems that the `email-handler` container can't connect to the Postfix. Can you make sure 
- Postfix is running correctly. You can try to send an email from Postfix by using something like
`swaks --from anything@my-domain.com --to your-personal-email@gmail.com --server 127.0.0.1` from the host (not inside the container): an email should be sent to your personal email address.

- 240.0.0.0/24 is allowed in /etc/postfix/main.cf `mynetworks`  https://github.com/simple-login/app/blob/0b2b653a7b9a3632a1b9dd29c4e3f16031cb958e/README.md#L357

By default email-handler connects to Postfix via 240.0.0.1 (which is the host).

If you have a doubt that a step is missing, I'd recommend to start over to be sure.

**Comment by cradcore** [comment]
@nguyenkims Thanks for the quick response.

I just ran `swaks --from test@<mydomain>.com --to <my gmail address> --server 127.0.0.1` and it correctly sent and I did receive it in my personal gmail. 

Just checked my postfix main.cf, which contains the following line:
`mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 240.0.0.0/24`

I may be confusing two things, but when I run an inspect on my docker network, my email-handler container returns the following address: 172.19.0.12/16. Would I need to include that in my main.cf as well?

**Comment by nguyenkims** [comment]
@cradcore in the README, there's a step "Prepare the Docker network" that creates the 240.0.0.0/24 network, have you run it?

**Comment by cradcore** [comment]
@nguyenkims 

You are correct. I am using docker-compose, which places all the containers in the same file into the same network, so I figured I didn't need that step. HOWEVER, I never changed the network to use 240.0.0.0/24. That would be my problem. Thank you!
