### ISSUE TITLE
Creating new alias shows @domain1.com and @domain2.com

### ISSUE THREAD

**Issue by r9isgod8** [simple-login/app#287]
Hi, I have this issue where while creating a new alias I only get @domain1.com and @domain2.com as domains and not the actual domain as you can see in the image.

![image](https://user-images.githubusercontent.com/9054411/94137632-54cbc500-fe84-11ea-8a89-031ec9340d25.png)

**Comment by nguyenkims** [comment]
@r9isgod8 it seems that your `ALIAS_DOMAINS` variable is set in your config file. Make sure to use the suggested config file in the README https://github.com/simple-login/app/blob/0b2b653a7b9a3632a1b9dd29c4e3f16031cb958e/README.md#L439, the `example.env` file is rather for advanced config https://github.com/simple-login/app/blob/637bc569eb7b70aee154b5b12035e35fd3e9a450/example.env#L28
