### ISSUE TITLE
I can receive emails to my alias but I can't send emails from my alias

### ISSUE THREAD

**Issue by r9isgod8** [simple-login/app#288]
Hi, I have setup simplelogin on debain 10 using docker and there is an issue where I can send email from my alias but I can't receive emails on my alias. While sending from alias, gmail rejects it because of ipv6 not setup as you can see from the attached images.

![image](https://user-images.githubusercontent.com/9054411/94141408-4d0f1f00-fe8a-11ea-9537-1284ef52aa3e.png)

![image](https://user-images.githubusercontent.com/9054411/94141453-60ba8580-fe8a-11ea-95a5-a60861d1083f.png)

**Comment by nguyenkims** [comment]
From the error message, you might need to set up the PTR record on your domain, both for IPv4 and IPv6.

**Comment by r9isgod8** [comment]
> 
> 
> From the error message, you might need to set up the PTR record on your domain, both for IPv4 and IPv6.

The thing is my domain provider, porkbun, doesn't have anyway to add PTR record so I tried to use ipv4 only by adding inet_protocols=ipv4 in postfix main.cf and restarted postfix but the error still persists.

**Comment by nguyenkims** [comment]
The PTR record is rather to be set on your cloud provider. They might have called it "Reverse DNS", for example this is how it's set up on SimpleLogin cloud provider UpCloud:

![image](https://user-images.githubusercontent.com/3167780/94297397-bb281480-ff64-11ea-8cf2-c8c8d8646922.png)

**Comment by r9isgod8** [comment]
I didn't want to try and tinker with reverse dns of my box since it hosts swizzin so I just went ahead and set inet_protocols=ip4 in postgresql and now everything works. However I still see some delays in receiving emails from GSuite accounts but that is not a pressing issue right now.
