### ISSUE TITLE
Not receiving signup confirmation emails #267

### ISSUE THREAD

**Issue by pojhm91c7iwk** [simple-login/app#289]
@pojhm91c7iwk is this issue still there? Please feel free to start from scratch the self-hosting instructions to make sure no step is missed.

_Originally posted by @nguyenkims in https://github.com/simple-login/app/issues/267#issuecomment-682453440_

I started completely from scratch self-hosting it and running again the same issue of connection time out. 

I also made sure that Port 25 is open for Inbound/Outbound.

Here's the log from /var/log/mail.log

Sep 25 14:23:13 ip-X.X.X.X postfix/smtp[5570]: connect to outlook-com.olc.protection.outlook.com[X.X.X.X]:25: Connection timed out
Sep 25 14:23:13 ip-X.X.X.X postfix/smtp[5572]: connect to outlook-com.olc.protection.outlook.com[X.X.X.X]:25: Connection timed out
Sep 25 14:23:13 ip-X.X.X.X postfix/smtp[5572]: B9BE181ABC: to=user01@outlook.com, relay=none, delay=44688, delays=44628/0.04/60/0, dsn=4.4.1, status=deferred (connect to outlook-com.olc.protection.outlook.com[X.X.X.X]:25: Connection timed out)
Sep 25 14:23:13 ip-X.X.X.X postfix/smtp[5570]: C954881AF7: to=user01@outlook.com, relay=none, delay=48724, delays=48663/0.04/60/0, dsn=4.4.1, status=deferred (connect to outlook-com.olc.protection.outlook.com[X.X.X.X]:25: Connection timed out)
Sep 25 14:32:13 ip-X.X.X.X postfix/qmgr[1115]: 7EBC881AFC: from=reply+randomcharacters@mydomain.com, size=2778, nrcpt=1 (queue active)
Sep 25 14:32:43 ip-X.X.X.X postfix/smtp[5604]: connect to outlook-com.olc.protection.outlook.com[X.X.X.X]:25: Connection timed out
Sep 25 14:33:13 ip-X.X.X.X postfix/smtp[5604]: connect to outlook-com.olc.protection.outlook.com[X.X.X.X]:25: Connection timed out
Sep 25 14:33:13 ip-X.X.X.X postfix/smtp[5604]: 7EBC881AFC: to=user01@outlook.com, relay=none, delay=48390, delays=48329/0.04/60/0, dsn=4.4.1, status=deferred (connect to outlook-com.olc.protection.outlook.com[X.X.X.X]:25: Connection timed out)

Please help.

**Comment by pojhm91c7iwk** [comment]
swaks --from something@your-domain.com --to your-email@outlook.com
=== Trying outlook-com.olc.protection.outlook.com:25...
*** Error connecting to outlook-com.olc.protection.outlook.com:25:
*** IO::Socket::INET6: connect: timeout

swaks --from something@your-domain.com --to your-email@protonmail.com
=== Trying mail.protonmail.ch:25...
*** Error connecting to mail.protonmail.ch:25:
***     IO::Socket::INET6: connect: timeout

**Comment by nguyenkims** [comment]
It seems that your server can't connect to the port 25 on Outlook and Protonmail. Can you try `telnet outlook.com 25` and let me know if this command succeeds?

**Comment by pojhm91c7iwk** [comment]
It's installed on AWS and Port 25 is open. Below is the output:
>telnet outlook.com 25

Trying 40.97.XXX.XXX...
Trying 40.97.XXX.XXX...
Trying 40.97.XXX.XXX...
Trying 40.97.XXX.XXX...

**Comment by nguyenkims** [comment]
That actually means that the port 25 is blocked. You should see something like this otherwise:

![image](https://user-images.githubusercontent.com/3167780/94712956-762c2580-034a-11eb-99fc-cb9f560e3a69.png)

**Comment by pojhm91c7iwk** [comment]
I understand that but Port 25 is Open. Someone will have to test deploy it on AWS and see if they can replicate the issue.

**Comment by pojhm91c7iwk** [comment]
It seems no matter what, AWS blocks your EC2 instance port even when you use SES and Elastic IP.
