### ISSUE TITLE
Please update outdated steps for SMTP Credentials

### ISSUE THREAD

**Issue by pojhm91c7iwk** [simple-login/app#290]
URL: https://github.com/simple-login/app/blob/master/docs/ses.md

"Now, in SES we need to generate SMTP Credentials to use. Go to the SMTP settings tab, and create credentials." <- the steps are outdated for creating the credentials.

**Comment by nguyenkims** [comment]
@pojhm91c7iwk thanks, can you please create a PR to update the steps for using SES?

**Comment by pojhm91c7iwk** [comment]
I am not aware of the correct steps.

**Comment by havedill** [comment]
I just checked, and steps are still accurate. Going to SMTP settings tab, I see the ability to create your credentials still. 

https://i.imgur.com/SxfILdT.png

**Comment by pojhm91c7iwk** [comment]
> I just checked, and steps are still accurate. Going to SMTP settings tab, I see the ability to create your credentials still.
> 
> https://i.imgur.com/SxfILdT.png

It’s what happens after you click Create SMTP Credentials. That’s changed drastically and I couldn’t find a way as explained

**Comment by havedill** [comment]
Their documentation shows it being the same. you just get some credentials that's it..
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-credentials.html

**Comment by pojhm91c7iwk** [comment]
> Their documentation shows it being the same. you just get some credentials that's it..have you tried clicking through the wizard?
> https://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-credentials.html

Again, please try it hands-on, their documentation isn’t updated as well. They are showing the old steps. If you perform the steps, you’ll not see any of those listed steps.

**Comment by havedill** [comment]
Ok, i just did it. I literally pressed "create a new user" and it gave me credentials. Nothing changed?https://i.imgur.com/GLbgOey.png

**Comment by pojhm91c7iwk** [comment]
> Ok, i just did it. I literally pressed "create my smtp credentials", hit continue and it gave me credentials. Nothing changed?https://i.imgur.com/GLbgOey.png

Interesting! I just redirects me to the user page. I don’t see what you see. Not sure what’s wrong but that means it’s not an issue. Please close this and thanks for your help.
