### ISSUE TITLE
Recreating deleted alias shows alias already exists

### ISSUE THREAD

**Issue by r9isgod8** [simple-login/app#291]
Hi, I am trying to re-create the alias that I already deleted but it throws up alias already exists error. Upon further investigation into the database it shows the deleted alias ends up under domain_deleted_alias table and when I remove them using sql  from the table then only they are deleted and I can recreate them. Here is the screenshot of the table and also a gif to show the error that I encounter.

Database Table
https://xbackbone.ali-rizvi.com/KeLo4/vIQeYENU80.png

Error
https://xbackbone.ali-rizvi.com/KeLo4/pAnecufa15.gif

**Comment by nguyenkims** [comment]
@r9isgod8 on the custom domain page, you can see all aliases that have been deleted. You can also restore a deleted alias so it can be re-created:

![simplelogin io deleted aliases | SimpleLogin 2020-09-28 17-05-36](https://user-images.githubusercontent.com/3167780/94449900-e309b900-01ac-11eb-9149-a6ec20eca685.png)

**Comment by r9isgod8** [comment]
Lol, my bad. Thank you so much. Closing the issue.

**Comment by GetVirtual** [comment]
Hi @nguyenkims,

I think I have a similiar issue as I´m self hosting but I´ve used my domain to setup SimpleLogin and it is now my built-in (I´m the only user anyway). If I get the documentation correctly I can´t empty the trash-bin for built-in.

1. Should I´ve used a setup domain and added my custom domain over the SimpleLogin user interface?
2. Or is there a way I can deactivate the protection to recreate alias for built-in domains?

Best regards and thanks in advance

P.S.: Looking forward for a new docker image :-)
P.P.S.: Great work! Any way where  I can donate. The Patreon Link I´ve found seems to be inactive.
