### ISSUE TITLE
default user/pass not working

### ISSUE THREAD

**Issue by Froghut** [simple-login/app#292]
I set up everything using the steps described here, but when I tried to login for the first time the connection timed out, not sure what happened. The problem is the default username + password no longer work and I have no way to log in. Can I somehow reset the DB or something lie that?

**Comment by nguyenkims** [comment]
@Froghut to reset the database, you can stop the database container  remove the folder `$(pwd)/sl/db` and re-run the database container.

```
docker rm -f sl-db
rm -rf $(pwd)/sl/db

# re-run the database
```

Otherwise to be sure no step is missing, I'd suggest re-doing all the steps from scratch.
