### ISSUE TITLE
Enabling Catch-All on Self-Hosted Instance

### ISSUE THREAD

**Issue by pojhm91c7iwk** [simple-login/app#301]
How do I enable catch-all on self-hosted instance? I self-hosted using mydomain.com and I am able to send/receive emails using newely created aliases (my-first-alias@mydomain.com).

But, how do I enable catch-all? For example, "anything"@mydomain.com?

**Comment by nguyenkims** [comment]
@pojhm91c7iwk you can add the domain as a custom domain and enable that catch-all option on this domain.

**Comment by pojhm91c7iwk** [comment]
So I am setting up and running into a conflict.

**3. DKIM**

`Record: CNAME
Domain: dkim._domainkey.mydomain.com
Value: dkim._domainkey.mydomain.com `

The domain registrar site gives below error:

'The service will be disabled


TXT | dkim._domainkey | "v=DKIM1; k=rsa; p=XXXXXXXXXXXXXXXXXXXXXXXXX'

**Comment by nguyenkims** [comment]
@pojhm91c7iwk a custom domain just needs to have the MX record set up to be "verified" actually. So you don't need to have DKIM verified to enable catch-all option on it.

**Comment by pojhm91c7iwk** [comment]
Correct, but without it the emails are going into SPAM folder.

**Comment by nguyenkims** [comment]
@pojhm91c7iwk the DKIM is added when forwarding emails to an alias or sending emails from an alias:
https://github.com/simple-login/app/blob/master/email_handler.py#L660
https://github.com/simple-login/app/blob/master/email_handler.py#L871

If your domain never sends a lot of emails before, it'd take a while for it to be whitelisted by popular email services and reduce the chance emails being ended up in Spam. You can set up a filter to avoid emails being mistakenly put to Spam folder: https://simplelogin.io/help

**Comment by tadinski** [comment]
> @pojhm91c7iwk you can add the domain as a custom domain and enable that catch-all option on this domain.

So "verifying" the MX record is enough to use catch-all?
The settings of the records in the https://github.com/simple-login/app#dns will be automatically used for the incoming/outgoing emails of the custom domain then?

**Comment by nguyenkims** [comment]
@tadinski yes :).

**Comment by haltdev** [comment]
I also cannot get catch-all to be enabled.  When I try to add my domain, it says that a custom domain cannot be a built-in domain and does not add the domain.  I only have one domain, and I used it during the setup process for the built-in domain.  Is it possible to enable catch-all on the built-in domain?
