### ISSUE TITLE
Please update docker simplelogin/app and document on selfhosting

### ISSUE THREAD

**Issue by steveclapx** [simple-login/app#303]
240.0.0.0 can cause mail-tester not be 10 , maybe we should change it to another one .
And also hope to update simplelogin/app image to support more features for selfhosting
thanks :D

**Comment by nguyenkims** [comment]
@steveclapx yes mail-tester doesn't seem to like the 240.0.0.0 :). 

Unfortunately changing this network would require existing SimpleLogin self-hosted instance to re-run almost everything ...

**Comment by steveclapx** [comment]
> @steveclapx yes mail-tester doesn't seem to like the 240.0.0.0 :).
> 
> Unfortunately changing this network would require existing SimpleLogin self-hosted instance to re-run almost everything ...

yes, which ip would u recommend me to change to as a docker network?
and is it possible to upgrade the docker image 
thanks!

**Comment by nguyenkims** [comment]
@steveclapx I think any private IPv4 range can work:
https://en.wikipedia.org/wiki/Private_network#Private_IPv4_addresses

We'll try to update the Docker image soon :). Updating the image requires some thorough testings, both on an empty and existing environment so we tend to do that only for hotfixes :).

**Comment by steveclapx** [comment]
> @steveclapx I think any private IPv4 range can work:
> https://en.wikipedia.org/wiki/Private_network#Private_IPv4_addresses
> 
> We'll try to update the Docker image soon :). Updating the image requires some thorough testings, both on an empty and existing environment so we tend to do that only for hotfixes :).

Thanks a lot !
