### ISSUE TITLE
Raspberry Pi - Does not work

### ISSUE THREAD

**Issue by Rustymage** [simple-login/app#306]
Figured I'd leave a comment stating that it doesn't work on a RPi 3B+.

```
pi@raspberrypi:~ $ sudo docker run --rm \
>     --name sl-migration \
>     -v $(pwd)/sl:/sl \
>     -v $(pwd)/sl/upload:/code/static/upload \
>     -v $(pwd)/dkim.key:/dkim.key \
>     -v $(pwd)/dkim.pub.key:/dkim.pub.key \
>     -v $(pwd)/simplelogin.env:/code/.env \
>     --network="sl-network" \
>     simplelogin/app:3.2.2 flask db upgrade
standard_init_linux.go:211: exec user process caused "exec format error"
```
I believe the error leads to a system architecture incompatability with the docker container. 

I've signed up online for a free account but would love to self-host in the future. I don't have a Linux machine to hand currently as I have greater need for Windows and thus Docker for Windows - Yuk!

Thanks 

:)

Edit: To add some context, I seached for whether it would work before installing and found no hint. Hopefully this assists others in not spinning up an RPi and trialing just yet.

**Comment by fareszr** [comment]
yup probably a compatibility issue
