### ISSUE TITLE
is it normal to show premium expires in 7 days notice even with lifetime set to true?

### ISSUE THREAD

**Issue by fareszr** [simple-login/app#307]
after editing the database and setting the default value for lifetime to true
its still show that premium expires in 7 days

if its normal, it kind of confusing and it should be fixed to show nothing and remove the upgrade button.

also please add `ALTER TABLE users ALTER COLUMN lifetime SET DEFAULT TRUE;` command to help beginners change the default value.

**Comment by nguyenkims** [comment]
This is mentioned here https://github.com/simple-login/app/blob/b90705f12ec853a78d103cb8f6afb786eb38f13f/README.md#L571 but all the subscription mechanisms are indeed not relevant for self-hosting. I just created this ticket https://github.com/simple-login/app/blob/b90705f12ec853a78d103cb8f6afb786eb38f13f/README.md#L571 in our roadmap, feel free to vote on it to make it happen sooner :)

**Comment by fareszr** [comment]
> This is mentioned here
> 
> https://github.com/simple-login/app/blob/b90705f12ec853a78d103cb8f6afb786eb38f13f/README.md#L571
> but all the subscription mechanisms are indeed not relevant for self-hosting. I just created this ticket
> https://trello.com/c/JlSUAjBf/121-able-to-disable-subscription-in-self-hosted-instance-all-accounts-are-premium-by-default
> in our roadmap, feel free to vote on it to make it happen sooner :)

i meant adding the database command.
thanks for the answer!.
