### ISSUE TITLE
Mojibake with PGP and fullwidth/multibyte characters

### ISSUE THREAD

**Issue by cyberflamingo** [simple-login/app#312]
Hello!
I've been using your tool with great success and I thank you for that!

I noticed an error with PGP and language using fullwidth/multibyte characters (Japanese, Chinese Korean...), or at least I think it's related to fullwidth characters.

When encrypted with PGP, emails coming in Japanese are "mojibake", see the screenshot:

![pgp_mojibake](https://user-images.githubusercontent.com/19971275/96330418-7dd71400-1044-11eb-96bd-6aa215754dc7.png)

English characters (URL etc) don't suffer from this problem.

I believe PGP's encryption is the cause of the problem; email subject in Japanese reads just fine.

I tried to pin down the problem and I believe it has to do with how the encryption is done on [this line](https://github.com/simple-login/app/blob/ac07c775e44135ac94f0ead70ef71596aeddca3a/email_handler.py#L400).

If I'm not mistaken and reading your code right, email message should be converted in something like quoted printable or Base64 if they are note 7bit (ASCII).

Probably not a lot of your user have this problem right now so no sweat if it's not priority!

**Comment by nguyenkims** [comment]
@cyberflamingo thanks for reporting this issue! 

I've tried sending an email with Japanese characters to an alias whose mailbox has PGP enabled and the characters seem to be correctly displayed. Here are the characters I'm using

```
片仮名

ギリギリ
```

Maybe this issue only happens with some characters? Can you send me in this case an email content that would trigger this issue? 

P.S: my knowledge is practically 0 regarding non-latin characters :)

**Comment by cyberflamingo** [comment]
Thanks for coming back to me!

I just sent an email to `hi@` with two exported emails: one with PGP enabled and the other without.

The one with PGP contains garbled text when rendered by my email provider but the other one is fine. On the former, I noticed the content is `null` and there is no `Content-Type:`.

I am going to take a longer look at it after work myself.

Don't be harsh on yourself, I work with Japanese characters everyday and I still think I understand nothing about non-latin characters haha. This will be a good challenge!

**Comment by nguyenkims** [comment]
( this is from the email I just sent - put it here so anyone who's interested in this issue can follow :) )

Sorry for the late response!

We have investigated and the issue seems to be solved now due to some changes we recently made in PGP (use bytes instead of string to handle encryption, adding a fallback encryption method) :)

Can you please retry and let me know if the issue still persists?

**Comment by cyberflamingo** [comment]
Truly sorry for the late reply. I had crazy busy weeks lately.

I just checked with ProtonMail: it works well on mobile but not on desktop. I guess it means its resolved on your end but there is something going on on PM's end.

Thank you for taking care of it although you mustn't have much fullwidth/multibyte clients yet!

Glad to be a paying user. I'll make sure to spread the word here in Japan!

**Comment by nguyenkims** [comment]
@cyberflamingo no worries, glad that it works at least on Protonmail mobile app now!
