### ISSUE TITLE
Organize aliases by category/tag

### ISSUE THREAD

**Issue by LongJohn-Silver** [simple-login/app#313]
As of writing this issue, this is the most up voted feature on Trello with 9 up votes (and you could make it 10 if you count me, who doesn't have an account and therefore can't vote), I think this could be integrated into the service without a lot of work or problems (considering, for example, that the second most up voted is adding a cryptocurrency as a payment method, which implies a lot of other economical aspects) and could improve the usability a lot. I have a lifetime, thus premium, account and I have all the features which make it really comfortable to use, but I have a ton of accounts on different web sites and it's starting to become a hassle to try and find what belongs where since the GUI is cluttered with so many aliases and no easy identification of them, the only way in which I could do that is by adding the name of the service in question at the beginning of the alias, but that kind of renders useless the UUID and random words option, and honestly it would be kind of annoying to have to change all of my almost 100 accounts just to be able to more or less sort them in a logical way, or to try and find a specific alias.

I don't care too much about the name, either category or tag is fine by me, but please don't make it so that there are predefined categories but rather than the user could create them.

**Comment by nguyenkims** [comment]
@LongJohn-Silver this ticket is indeed one of the most voted ones and will be the next one we'll work on :). 

Have you tried using alias `note` to organize aliases? When searching for an alias, the alias note is also taken into account. The note is also filled up automatically when you create an alias via the browser extension.

**Comment by LongJohn-Silver** [comment]
Originally I used notes to name the aliases, then the name box was added so I started using that to name them. I think I could use the notes while the categories are being worked on.

----

Also, what about allowing users to choose a colour from a palette to identify X or Y group? It doesn't have to be released at the same time as the bare bones of the tag system, but maybe later.

**Comment by nguyenkims** [comment]
@LongJohn-Silver the alias name is used when emails are sent from an alias, it isn't really meant to organize aliases :). 

> Also, what about allowing users to choose a colour from a palette to identify X or Y group? It doesn't have to be released at the same time as the bare bones of the tag system, but maybe later.

By color palette, you mean adding a color for each tag? I feel a textual tag is easier to manage and colors can be confusing if someone has a lot of colors.

**Comment by LongJohn-Silver** [comment]
> @LongJohn-Silver the alias name is used when emails are sent from an alias, it isn't really meant to organize aliases :).

Oh, I always thought it was used to organize aliases, weird.

> > Also, what about allowing users to choose a colour from a palette to identify X or Y group? It doesn't have to be released at the same time as the bare bones of the tag system, but maybe later.
> 
> By color palette, you mean adding a color for each tag? I feel a textual tag is easier to manage and colors can be confusing if someone has a lot of colors.

I mean adding a colour for each tag while also having the textual tag, I think it may help to visually differentiate one from another.

**Comment by udaykapur** [comment]
+1 from me to add this feature as well please - I have set up aliases for multiple mailboxes so would be good to have the ability to sort them by mailboxes and maybe action multiple aliases by mailboxes (change the redirect address etc.), if possible please.

**Comment by nguyenkims** [comment]
I close this PR as it's tracked on https://trello.com/c/aHQAjFUQ/50-organize-aliases-by-category-tag :)

**Comment by LongJohn-Silver** [comment]
> I close this as it's tracked on https://trello.com/c/aHQAjFUQ/50-organize-aliases-by-category-tag :)

Should this not be closed when the feature is added?

**Comment by nguyenkims** [comment]
@LongJohn-Silver new features are actually tracked on Trello instead of GitHub. This is indeed a bit confusing ...

**Comment by LongJohn-Silver** [comment]
> @LongJohn-Silver new features are actually tracked on Trello instead of GitHub. This is indeed a bit confusing ...

Oh, okay, I feel like still would be nice to keep issues on GitHub updated, but sure. 

Has been an update regarding this feature? Os is there a pull request or something where progress can be tracked?

**Comment by nguyenkims** [comment]
We haven't started working on this feature yet. Once we started working on something, it's moved to the "Near Term" column on the roadmap actually.

**Comment by LongJohn-Silver** [comment]
Thanks, I dont know how Trello works, sorry.
