### ISSUE TITLE
How to upgrade an exisitng user to lifetime premium?

### ISSUE THREAD

**Issue by fareszr** [simple-login/app#314]
Hi 
Even after setting lifetime to true, my account suddenly was degraded to free tier, how do I enable life time premium for my account ? Do I have to recreate the database?
It would be nice to set a user as an admin so you can manage other users and your self.

**Comment by nguyenkims** [comment]
> Even after setting lifetime to true, my account suddenly was degraded to free tier

This is indeed strange. Can you give more details?

> It would be nice to set a user as an admin so you can manage other users and your self.
There's an `is_admin` column in the table `user` that once set, allows you to manage users on the admin UI at `/admin` URL.

**Comment by fareszr** [comment]
> > Even after setting lifetime to true, my account suddenly was degraded to free tier
> 
> This is indeed strange. Can you give more details?

well,  i guess the trials ran out?
i changed the default value for life time to true, but still i don't know why it downgraded

> There's an `is_admin` column in the table `user` that once set, allows you to manage users on the admin UI at `/admin` URL.

i dont have experience with SQL commands can you give the commands for enabling lifetime premium and admin access for an existing account?
phpPGadmin image for docker doesn't work correctly maybe because 12.1 is [out of date now?](https://www.postgresql.org/support/versioning/)

**Comment by nguyenkims** [comment]
> i changed the default value for life time to true, but still i don't know why it downgraded

You need to rather set the `lifetime` value to true, setting the default value only works for users who are created after.

It can be done by this query

```
update users
set lifetime=true;
```

For the admin access, you can use the following query, make sure to replace `{your_email}` by the account email you want to set admin:

```
update users
set is_admin=true
where email='{your_email}'
```

**Comment by fareszr** [comment]
> where email='{your_email}'

thanks for the reponse!

for the premium it worked!
but for the admin command im not sure, it doesnt show UPDATE 1 like the premium command, and there is no diffrence in the dashboard, is there a secret link to the admin portal? its not mentioned anywhere, as you said the docs a general upgrade

will add the new premium command to #309

**Comment by nguyenkims** [comment]
> but for the admin command im not sure, it doesn't show UPDATE 1 like the premium command,

Have you replaced `{your_email}` by your actual email? As otherwise, all accounts will be upgraded to admin.

**Comment by fareszr** [comment]
> > but for the admin command im not sure, it doesn't show UPDATE 1 like the premium command,
> 
> Have you replaced `{your_email}` by your actual email? As otherwise, all accounts will be upgraded to admin.

yup, didn't work unfortunately 

this how i entered it:

```
simplelogin=# update users
simplelogin-# set is_admin=true
simplelogin-# where email='fareszr@myemail.com'
```
still redirects me to `/dashboard`

**Comment by nguyenkims** [comment]
@fareszr that's indeed strange. I don't recommend using `admin` UI anyway as it can be removed in the next upcoming versions. The admin UI was created at the beginning to facilitate some manual tasks but it's quite limited and we haven't added any new features since a long time.

**Comment by fareszr** [comment]
The only thing the admin ui could be useful for me is to manage premium users and check if there is unwanted accounts

Closing the issue as the admin panel is kind of deprecated

**Comment by Cshark1** [comment]
> > > but for the admin command im not sure, it doesn't show UPDATE 1 like the premium command,
> > 
> > 
> > Have you replaced `{your_email}` by your actual email? As otherwise, all accounts will be upgraded to admin.
> 
> yup, didn't work unfortunately
> 
> this how i entered it:
> 
> ```
> simplelogin=# update users
> simplelogin-# set is_admin=true
> simplelogin-# where email='fareszr@myemail.com'
> ```
> 
> still redirects me to `/dashboard`
The command doesn't work because there is no semicolumn to end the SQL command. For further reference to make yourself admin you this is what you need to write:
`update users
set is_admin=true
where email='{your_email}';`
