### ISSUE TITLE
Same alias duplicated when multiple mailboxes was set

### ISSUE THREAD

**Issue by JasonHK** [simple-login/app#316]
Just like the screenshot below, same alias entry in `/dashboard` was duplicated when multiple mailboxes were set. Fun fact: when the "more" button of the card other than the first one was pressed, the first card will expand instead of the clicked card.

![2020-10-22_00003](https://user-images.githubusercontent.com/4410086/96893238-15ad8580-14bd-11eb-8d02-95fa86efa146.png)

**Comment by nguyenkims** [comment]
@JasonHK thanks for reporting! This is on the self-hosted version or on the managed one (i.e. simplelogin.io)?

**Comment by JasonHK** [comment]
> @JasonHK thanks for reporting! This is on the self-hosted version or on the managed one (i.e. simplelogin.io)? 

@nguyenkims It's happen on simplelogin.io.

P.S. There's a typo in the fun fact, it should be “when the "more" button of the card other than the first one was pressed, the first card will expand instead of the clicked card”.

**Comment by nguyenkims** [comment]
@JasonHK this bug has been fixed now :), thanks for reporting it!
