### ISSUE TITLE
Update Infinity Search Logo

### ISSUE THREAD

**Issue by LongJohn-Silver** [simple-login/app#317]
Not so long ago Infinity Search changed their logo for a grey one with a magnifier, the website still displays the old blue one.

**Comment by nguyenkims** [comment]
@LongJohn-Silver thanks! I have contacted InfinitySearch to get the new logo :)

**Comment by LongJohn-Silver** [comment]
> @LongJohn-Silver thanks! I have contacted InfinitySearch to get the new logo :)

It's nothing! BTW, you should check thei project, there has been some great improvements.

**Comment by nguyenkims** [comment]
@LongJohn-Silver the new logo has been updated :).
