### ISSUE TITLE
alias already exists

### ISSUE THREAD

**Issue by tadinski** [simple-login/app#322]
I don't seem to create a specific alias "ikea" for one of my domains. Creating other aliases works fine.
I checked the database table "alias" for "ikea" --> does not exist, nor does it exist in the trash of any of the domains

Self hosted v3.2.2

**Comment by nguyenkims** [comment]
Can you check the table "deleted_alias" and "domain_deleted_alias" to see
if this alias is there?

**Comment by tadinski** [comment]
@nguyenkims it was in deleted_alias table like you said.

**Comment by nguyenkims** [comment]
@tadinski if you want to recreate this alias, you can remove it from this table.
