### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by LagSeeN** [simple-login/app#340]
i can't access website
![Screenshot_20201206-101756](https://user-images.githubusercontent.com/19259262/101270631-5c291c00-37ad-11eb-9176-cc09c733fcec.jpg)

**Comment by axian32** [comment]
Same here. Hope it's nothing serious. Good luck Simplelogin team!

**Comment by nguyenkims** [comment]
Hi the website is up again now. This was due to a DNS issue (CloudFlare s**ks!) 

Email delivery isn't affected but the web app and our landing page weren't accessible because of the missing DNS record.

Sorry for the issue!

**Comment by LagSeeN** [comment]
thanks
