### ISSUE TITLE
using multiable sub-domains/domains for aliases

### ISSUE THREAD

**Issue by fareszr** [simple-login/app#346]
hi i wanted to use other subdomains for aliases, since my main sub-doman has the word relay in it, and can easily be detected by a regex.

how ever when i want to setup another subdomain, i get an unknown user error in the postfix log.

how to fix this? does this have to do with any of pgsql queries ?

**Comment by nguyenkims** [comment]
@fareszr You can also add this new domain as a custom domain on the /dashboard/custom_domain page and create aliases with this domain instead.
If you want to change the root domain (the one used when setting up the server), I'd suggest following the self-hosting instruction from the beginning with the new domain.

**Comment by fareszr** [comment]
> @fareszr You can also add this new domain as a custom domain on the /dashboard/custom_domain page and create aliases with this domain instead.
> If you want to change the root domain (the one used when setting up the server), I'd suggest following the self-hosting instruction from the beginning with the new domain.

i added the second domain to simplelogin.env, in the `OTHER_ALIAS_DOMAINS` parameter but the aliases don't work, as i cant receive mail and in the postfix logs it shows unknown user error.
is there anything else to change for it to work?

**Comment by nguyenkims** [comment]
@fareszr the current SQL query used in `/etc/postfix/pgsql-relay-domains.cf` only supports 1 domain actually. 
In the next version of SimpleLogin, this script will support multiple domains, specified via `OTHER_ALIAS_DOMAINS` and `ALIAS_DOMAINS` config.

**Comment by fareszr** [comment]
When is the next vedsion going to be released ?

**Comment by nguyenkims** [comment]
@fareszr There's no defined ETA for the next version. We are working on simplifying the self-hosting instruction by:
- creating a script that handles installation and update for SimpleLogin. 
- have a single switch to enable self-hosting version. A lot of features in SimpleLogin isn't needed in a self-hosting setup.

**Comment by nguyenkims** [comment]
Just to let you know that the new version 3.3.0 has been released. If you have a running SL instance, please let me know if there's any issue with upgrade (there shouldn't but we never know for sure :) )

**Comment by fareszr** [comment]
> Just to let you know that the new version 3.3.0 has been released. If you have a running SL instance, please let me know if there's any issue with upgrade (there shouldn't but we never know for sure :) )

is there any changelog for the new update ?

**Comment by nguyenkims** [comment]
Yes the change log is here https://github.com/simple-login/app/blob/master/CHANGELOG

**Comment by fareszr** [comment]
> Yes the change log is here https://github.com/simple-login/app/blob/master/CHANGELOG

so whats the method for adding multiple domains now ?

**Comment by nguyenkims** [comment]
You can add a domain on the "Domains" page 

![image](https://user-images.githubusercontent.com/3167780/110140852-d41ad880-7dd4-11eb-81db-408b01eedbfe.png)

**Comment by fareszr** [comment]
> You can add a domain on the "Domains" page
> 
> ![image](https://user-images.githubusercontent.com/3167780/110140852-d41ad880-7dd4-11eb-81db-408b01eedbfe.png)

and it just works ?
no additional stuff to change in the database command or postfix config ?

**Comment by nguyenkims** [comment]
No this is how users use simplelogin.io :). When you add a domain, a small guide will show up to walk you through the DNS setup.
