### ISSUE TITLE
Spam Assassin

### ISSUE THREAD

**Issue by Rustymage** [simple-login/app#350]
Hey,

A great service that I;ve used for a few months prior to attempting to spin up a self hosted version.

I have it working but the only bit that confuses me is where does SpamAssassin come in? I see it mentioned in the `.env` example but that's it.

Am I missing something?

Thanks!

**Comment by nguyenkims** [comment]
Hi, for a personal usage, setting up SpamAssassin can be unnecessary as from our experiences, SpamAssassin isn't really stable and requires a lot of server resources. If you really need spam check, you can set up SpamAssassin directly with Postfix, independently of SimpleLogin.

**Comment by Rustymage** [comment]
Thanks for that. I appreciate the time you took to respond!
