### ISSUE TITLE
[Enhancement] Show the 'Alias Note' on the alias card itself

### ISSUE THREAD

**Issue by grande-mephistopheles** [simple-login/app#351]
When finding an alias at a glance, you have to click on 'More' toggle to find out what the alias is used for. Keeping it visible on the card makes assessing an alias much easier. Otherwise you have to click on "more" every time to find out the use case. This will improve user experience a lot!

**Comment by nguyenkims** [comment]
@grande-mephistopheles there's this ticket in the roadmap that'd allow to configure which fields to show by default https://trello.com/c/ne1cYJhK/144-able-to-configure-the-fields-to-show-by-default-on-the-alias-page, feel free to vote on it to make it happen sooner :)

As the roadmap is currently handled on Trello, I'll close this ticket :)
