### ISSUE TITLE
How to add new "Sender Address Format" setting

### ISSUE THREAD

**Issue by Metabaron1** [simple-login/app#356]
Hi
Some email from some official domaine (like gouv.fr) forwarded to my mailbox , are bouced by my ISP mail filters as spam. I think these filters are triggered when an official domain is contained in sender and is modified, to prevent fishing by sender spoofing.
So i'd like to add a new sender format to the existing ones to mask the domain by replacing 
wick.com domain by something like wick(dot)com.
Could you point me wich files I should update to add this new pattern please.
Thanks for help

**Comment by nguyenkims** [comment]
@Metabaron1 Hi the sender format preference is stored in `User.sender_format` column:

https://github.com/simple-login/app/blob/0df4d1a93dc58e4edfccc7e18137072b12cebdec/app/models.py#L246

and is used in the `Contact.new_addr()`:

https://github.com/simple-login/app/blob/0df4d1a93dc58e4edfccc7e18137072b12cebdec/app/models.py#L1289

If you look for `sender_format` in the project, it's also used in the settings file and tests. These codes should be more straightforward though :)

**Comment by Metabaron1** [comment]
@nguyenkims Ok thank you, I'll try

**Comment by Metabaron1** [comment]
I modified the original sender domain but it's still bounced for gouv.fr emails.

But, it was sucessfull to unblock another official domain that is  filtered if sender is spoofed.  Then it confirms that it's a valid solution to add a new sender format to replace the domain dots.
I'm not Python developer, I just replaced the current '@' by '.'  pattern to test. So I'm not skilled enougth for such PR but it may be usefull for other users that have bounced emails.

About the gouv.fr domain that's still bounced, there is anoter field that contains the full original sender adress:
X-SimpleLogin-Envelope-From:
Is it used for reply or do you keep it in database? Is it safe if I alter this one too?

**Comment by nguyenkims** [comment]
Can you forward me the email at hi(at)simplelogin.io that's put into Quarantine so I can see what's the cause? We are using SpamAssassin for scanning emails for spam but sometimes it can be too strict.

**Comment by Metabaron1** [comment]
Oh sorry I forgot to say that it's about filters at my ISP mailbox, with self hosted server, nothing wrong with your servers. That's why I have no choice but to try to alter the forwarded mail to try to bypass their filters

**Comment by nguyenkims** [comment]
@Metabaron1 I see. We just created this ticket https://trello.com/c/5ctS2mwT/146-able-to-define-a-sender-format that'd allow to define your own sender format. Feel free to vote on it to make it happen sooner :)

**Comment by Metabaron1** [comment]
Ok, it's done :)
But it's only a part of the problem, I have to do more tests to guess the other conditions that trigger the filters... Or maybe just find another provider for my mailbox :)

**Comment by Metabaron1** [comment]
When I try to guess the filters, the aliases I use are immediately blocked. Could you point me where I can increase the amount of  bounced mail allowed before blocking, or just turn off automatic alias blocking please. The simplest of course, as I am not a python developer ;)

**Comment by nguyenkims** [comment]
@Metabaron1 the automatic alias disable is a mechanism to avoid your server from being blacklisted by other email services (when there are too many bounces). To avoid an alias from being disabled, you can set the `cannot_be_disabled` column to `True`. That can be done in SQL with a query like 

```
update alias
set cannot_be_disabled=TRUE
where alias.email = '{your alias here}';
```

**Comment by Metabaron1** [comment]
Ah thanks :)
Emails are not sent directly to other email services, I use a relay_host from my ISP, from wich I can only be blacklisted for a few hour and for a  big amount of bounced emails, not for a few tests. Then that's not a big deal.
