### ISSUE TITLE
no emails being forwarded

### ISSUE THREAD

**Issue by tffy5** [simple-login/app#357]
I've set up SimpleLogin following the instructions on my own server and made all the changes to the DNS record. After i log in (i've set the activated to 't' in the database so i could log in), i see that the parameters of the DNS are set correctly, but no emails are being forwarded. 

I've tried sending an email straight from the postfix command with `echo "Test Postfix Gmail https://example.com" | mail -s "Postfix Gmail" emailaddress@domain.com` this seems to be working. 

Is there a way to determine if the problem is with the receiving part of the mailserver or the sending part of the mailserver? Any ideas on how to troubleshoot the problem?

Thanks David

**Comment by nguyenkims** [comment]
@tffy5 can you try to send an email to an alias and post Postfix log and the `email-handler` log here please? Postfix log is stored in `/var/log/mail.log` and the `email-handler` log can be obtained with `docker logs sl-email`

**Comment by tffy5** [comment]
Ok, I managed to get it working flawlessly on a separate ubuntu server. My initial problem was with the right postfix configuration. The logs showed no errors but also no processing of the emails. I’m impressed how versatile this tool is.  It will be very useful.

Originally I intended to set it up on my main server which runs a Plesk interface. This gave me all kinds of unexpected problems. For starters I can’t install postfix-pgsql normally, I tried running postfix in a docker container and making the two postfix instances talk to each other. I got the docker instance of postfix running but the two never communicated smoothly. The incoming emails were forwarded to the docker container, who then sent it to the set forward address. Problems started when replying from the forward emailaddress to the created reply address. I kept getting the error:

`to=<reply+randomchars@subdomain.domain.nl>, relay= ip.ad.dr.es[ip.ad.dr.es]:20381, delay=0.36, delays=0.04/0.01/0/0.31, dsn=5.0.0, status=bounced (host ip.ad.dr.es[ip.ad.dr.es]: said: 500 Error: (SMTPRecipientsRefused) {'forwardaddress@anotherdomain.com': (554, b'5.7.1 <forwardaddress@anotherdomain.com>: Relay access denied')} (in reply to end of DATA command))`
`to=<forwardaddress@anotherdomain.com>, relay=ip.ad.dr.es[ip.ad.dr.es]:25, delay=0.01, delays=0/0/0/0, dsn=5.7.1, status=bounced (host ip.ad.dr.es[ip.ad.dr.es] said: 554 5.7.1 < forwardaddress@anotherdomain.com>: Relay access denied (in reply to RCPT TO command))`
I can’t figure out what is keeping it from functioning properly. If anyone has any ideas what could be the cause, I’m open for suggestions.

**Comment by nguyenkims** [comment]
@tffy5 Glad that it works now! I suggest to follow the self-hosting instructions without using intermediary software as it's hard to know how they would interfere.

About the error when replying, it seems that `forwardaddress@anotherdomain.com` has bounced the email. Some email services refuse emails if they are sent from unknown or low-reputation IP address. I'd suggest testing with Gmail as Gmail  seems to be more "tolerant" and is easier to debug.
