### ISSUE TITLE
Remove Hardcoded AWS_REGION

### ISSUE THREAD

**Issue by jimmybrancaccio** [simple-login/app#358]
It appears `AWS_REGION` is hardcoded?

https://github.com/simple-login/app/blob/d161ca94f6162bdb8f305ef33de6d76d765b2531/app/config.py#L160

This is causing issues here as my bucket is in `us-east-1`. For example, the link to my profile picture on my hosted instance is referencing `eu-west-3`. I get a message like:

> The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.

**Comment by nguyenkims** [comment]
@jimmybrancaccio For a personal usage, I think s3 isn't necessary and a local storage is enough. This can be set via the variable `LOCAL_FILE_UPLOAD`:
https://github.com/simple-login/app/blob/master/example.env#L136

s3 is currently used for storing the profile images (which is only used when a website wants to integrate "Sign in with SimpleLogin" button) and Quarantine emails.

**Comment by jimmybrancaccio** [comment]
@nguyenkims The README seems to indicate otherwise. Even if it didn't I don't see any reason to not have this on a personal install. It seems as simple as fixing this hardcoded value, no?

<img width="867" alt="Screen Shot 2021-01-11 at 16 06 52" src="https://user-images.githubusercontent.com/405585/104243990-20761780-5427-11eb-830a-14dd7b39a11c.png">

**Comment by nguyenkims** [comment]
@jimmybrancaccio you're right, I just added `AWS_REGION` as an environment variable https://github.com/simple-login/app/commit/d6cc2a4bf316cf43b827d4e3e6e77358bdddca02 :). We don't have an ETA for the next release yet though.

**Comment by jimmybrancaccio** [comment]
Hey @nguyenkims Sounds great, I appreciate you giving me a listen and making that change, and for your time! I can't wait for the next release then! 😄

**Comment by luisgepeto** [comment]
I was about to open an issue regarding this. This hardcoded value is affecting also Cloudwatch logging if set to another region. Also, since the docker image is outdated as per https://github.com/simple-login/app/issues/364 following the README and looking at the environment variables makes you think that this is not hardcoded on the 3.2.2 version (current docker)

**Comment by nguyenkims** [comment]
Just to let you know that the new version 3.3.0 has been released. If you have a running SL instance, please let me know if there's any issue with upgrade (there shouldn't but we never know for sure :) )
