### ISSUE TITLE
[Feature Request] Mass enable/disable mailbox.

### ISSUE THREAD

**Issue by kevinlekiller** [simple-login/app#360]
An option to click a button on a mailbox in the Mailboxes tab to enable or disable it for all aliases (with a popup to confirm the action).

Another option would be to mass enable or disable a mailbox for a specific domain and/or enable/disabled aliases.

**Comment by nguyenkims** [comment]
@kevinlekiller Hi we have a ticket in the roadmap that would allow editing aliases in batch: https://trello.com/c/outf99Yk/63-bulk-edit-aliases-delete-change-mailbox-etc, feel free to upvote it to make it happen sooner :)
