### ISSUE TITLE
Creating competitor to SimpleLogin and charging for premium

### ISSUE THREAD

**Issue by jbzar** [simple-login/app#361]
I want to create a competitor to SimpleLogin and charge for a premium service. Is this something that I can do with your license? Can I just fork your code and follow your instructions to launch my competitor? I also want to charge customers $2.50 a month.

**Comment by nguyenkims** [comment]
@jbzar Hi good question :). Yes you can.

**Comment by jbzar** [comment]
Ok. No attribution is required? Good.
