### ISSUE TITLE
Unknown error: The data couldn't be read because it is missing

### ISSUE THREAD

**Issue by tadinski** [simple-login/app#362]
Upgraded iOS app to v1.5
Get an error when trying to login using either the API or credentials
API url is set correctly

<img src="https://user-images.githubusercontent.com/6358371/106356163-c5d12c80-62fd-11eb-85f3-9dbb12982a5e.jpg" width="100">

**Comment by tadinski** [comment]
Issue persists after deleting and reinstalling the app

**Comment by nguyenkims** [comment]
Hi I think the v1.5 isn't compatible with the current server version (3.2.2). I'd suggest downgrading the iOS version.

We are currently working on a better way of self-hosting SimpleLogin via docker-compose that's tracked in https://github.com/simple-login/app/pull/355 and the next server version will hopefully be released with this PR.

**Comment by nguyenkims** [comment]
Just to let you know that the new version 3.3.0 has been released. It's compatible with the latest iOS version.

**Comment by tadinski** [comment]
thanks, it works

**Comment by samoyed** [comment]
This issue seems to be the case again.

iOS 26 - version 2.4.4
Selfhosted SL - version 3.4.0

"Login using API Key" Set API Key after changing API URL to selfhosted URL prompts "The data couldn't be read because it is missing".
