### ISSUE TITLE
Docker Image Outdated?

### ISSUE THREAD

**Issue by FabioWidmer** [simple-login/app#364]
Currently we are self-hosting SimpleLogin with Docker. According to the documentation this is still the supported option.

I can see many commits since the last release 3.2.2 but no new release was published yet. Is this intentional? We would really appreciate regular releases with correct Git tags so that DockerHub creates new images.

**Comment by nguyenkims** [comment]
@FabioWidmer we are working on a better way of deploying SimpleLogin via docker-compose (the corresponding PR is https://github.com/simple-login/app/pull/355). The current release flow is manual and takes a lot of time (we need to test that the new version is compatible or can be upgraded from previous versions).

**Comment by FabioWidmer** [comment]
@nguyenkims Thanks for your fast reply and referencing the pull request! We are looking forward to a full Docker-Compose file. Keep up the good work and we hope we can increase our monthly donation on OpenCollective soon.

**Comment by nguyenkims** [comment]
Just to let you know that the new version 3.3.0 has been released. The work on docker-compose is still in progress and would be for the next version then.
