### ISSUE TITLE
Security configuration

### ISSUE THREAD

**Issue by havedill** [simple-login/app#367]
Hello,

I use Sentry with my simple login instance. I got an error today from Sentry showing that someone who is using a google cloud VM seems to (potentially) attempting to break into my instance.

I host on AWS. If i allow port 80 and 443 to only be accessed by my home IP address, will that break anything?

[Screenshot of the Sentry error](https://i.imgur.com/8gVz0Vy.png)

There's actually a lot of attempts to do weird stuff if i look through my ngnix access logs...

**Comment by nguyenkims** [comment]
Hi it's possible that this is a bot running on a Google Cloud VM that tries to log in. These bots are quite frequent on Internet and as long as you don't have easy to guess password, they are harmless. 

> I host on AWS. If i allow port 80 and 443 to only be accessed by my home IP address, will that break anything?

It shouldn't break anything as email protocols use 25 port.
