### ISSUE TITLE
Gmail style forwarding

### ISSUE THREAD

**Issue by tycm** [simple-login/app#368]
When enabling forwarding in Gmail (and I believe a few other email providers) The message stays pretty much the same. Even preserving the "to" address. Would there be a way to implement this in simplelogin?

Below is an example. The message was sent to a gmail address, but forwarded from Gmail to an outlook account

![image](https://user-images.githubusercontent.com/44624889/107520277-3e967b00-6b7f-11eb-8026-759e85260a0b.png)

**Comment by nguyenkims** [comment]
@tycm This forwarding technique isn't compatible with SPF (though this is changing with [ARC](https://en.wikipedia.org/wiki/Authenticated_Received_Chain)) but in any case, this forwarding doesn't allow you to reply to the sender using the alias.
