### ISSUE TITLE
PGP for reverse alias

### ISSUE THREAD

**Issue by nodecorum** [simple-login/app#369]
I'd like to be able to encrypt replies sent to my reverse aliases, have SL decrypt using a previously uploaded Private key, and forward the unencrypted mail to the final destination.

Currently, I can use SL to encrypt incoming mail to my Gmail. Excellent!

However, When I reply through the reverse alias, I have no way to encrypt that reply so the content I wanted to keep from google is now stored unencrypted in my sent mail. 

I am happy to create, manage and upload the keys myself.

**Comment by nguyenkims** [comment]
@nodecorum the described feature isn't supported in SimpleLogin indeed. How do you plan to encrypt an email sent to a reverse-alias? As far as I know, PGP softwares usually only support using the destination key (i.e. the reverse-alias in this case) to encrypt an email.

**Comment by nodecorum** [comment]
> @nodecorum the described feature isn't supported in SimpleLogin indeed. How do you plan to encrypt an email sent to a reverse-alias? As far as I know, PGP softwares usually only support using the destination key (i.e. the reverse-alias in this case) to encrypt an email.

I'd create a key pair for the reverse alias, upload the private key to SimpleLogin and use the public key to encrypt. SimpleLogin would decrypt with the private key and forward the plaintext mail to the final destination.

**Comment by nguyenkims** [comment]
Oh sorry, what I meant was what software are you planning to use? Or maybe you'll encrypt the message manually?

**Comment by nodecorum** [comment]
> Oh sorry, what I meant was what software are you planning to use? Or maybe you'll encrypt the message manually?

I would expect it to work with any client that can do PGP - Thunderbird or Outlook with the OpenPGP add in, etc.

**Comment by tadinski** [comment]
> > @nodecorum the described feature isn't supported in SimpleLogin indeed. How do you plan to encrypt an email sent to a reverse-alias? As far as I know, PGP softwares usually only support using the destination key (i.e. the reverse-alias in this case) to encrypt an email.
> 
> I'd create a key pair for the reverse alias, upload the private key to SimpleLogin and use the public key to encrypt. SimpleLogin would decrypt with the private key and forward the plaintext mail to the final destination. 

This feature is really useful for someone who is self hosting it, I would love to have it. 

Nevertheless, I believe uploading private keys to not a not self hosted simple login instance goes against the principle of the “private key”

**Comment by nodecorum** [comment]
> > > @nodecorum the described feature isn't supported in SimpleLogin indeed. How do you plan to encrypt an email sent to a reverse-alias? As far as I know, PGP softwares usually only support using the destination key (i.e. the reverse-alias in this case) to encrypt an email.
> > 
> > I'd create a key pair for the reverse alias, upload the private key to SimpleLogin and use the public key to encrypt. SimpleLogin would decrypt with the private key and forward the plaintext mail to the final destination. 
> 
> +1
> 
> This feature is really useful for someone who is self hosting simplelogin, I would love to have it!
> 
> Nevertheless, I believe uploading private keys to not a not self hosted simple login instance goes against the principle of having a “private key”.
> 
> 

I don't have a big concern about these keys which would be used only for the specific purpose of decrypting mail sent to a reverse alias so it can be forwarded decrypted. The current alternative is that mail sent via the reverse alias is never encrypted at all.

**Comment by nguyenkims** [comment]
@nodecorum when you send an email, it's usually encrypted with TLS in transit. Your email service can read the email content though.

**Comment by nodecorum** [comment]
> @nodecorum when you send an email, it's usually encrypted with TLS in transit. Your email service can read the email content though.

Of course, but that's not the issue. The issue is that I can upload the PGP for my recipient and incoming mail is encrypted by SL so Google cannot read it. When I reply, there is no way to encrypt the reply. That means the PGP feature is not much use in hiding the content from the mail service - incoming junk gets encrypted, but important conversations are not.

**Comment by nguyenkims** [comment]
We created this ticket https://trello.com/b/4d6A69I4/open-roadmap in our roadmap to keep track of this feature, feel free to upvote it to make it happen sooner :). This Trello board is currently used for new feature requests.

**Comment by ataraskov** [comment]
@nguyenkims any progress on this one?

**Comment by nguyenkims** [comment]
@ataraskov we don't have this feature planned in our roadmap yet. Using signer@simplelogin.io wouldn't work here as SL needs to know the reverse alias in order to send emails to the right contact.

**Comment by ataraskov** [comment]
@nguyenkims, any hope to get this feature on the roadmap?

**Comment by nguyenkims** [comment]
@ataraskov it's going to be tough to be honest as we have some highly requested features in the 2023 roadmap. If anyone can contribute a merge request, we'd be happy to review and add it to the code base though.

**Comment by Xynonners** [comment]
@nguyenkims has this feature been added? it seems like anonaddy has this feature by encrypting to their public key.
