### ISSUE TITLE
API documentation import/export

### ISSUE THREAD

**Issue by TheLastProject** [simple-login/app#374]
Hey,

I would like to export my stuff on a cron job so I always have a local backup, but I can't find API documentation on the import/export. Could this please be documented on https://github.com/simple-login/app/blob/master/docs/api.md? Thanks!

**Comment by nguyenkims** [comment]
@TheLastProject currently the export is done inside the settings page at 
https://github.com/simple-login/app/blob/a2dad50d204fe7f21ba18ef83cdc77ab9c729fb7/app/dashboard/views/setting.py#L268
login/app/blob/a2dad50d204fe7f21ba18ef83cdc77ab9c729fb7/app/dashboard/views/setting.py#L293

and we don't have an endpoint to return that data yet. Is there any chance you can create a PR to make that happen :) ?

**Comment by TheLastProject** [comment]
I happily would, but I am sadly blocked by #375 currently. Feel free to assign this issue to me though.

**Comment by nguyenkims** [comment]
@TheLastProject thanks very much! I have updated the repo which should solve https://github.com/simple-login/app/issues/375.
