### ISSUE TITLE
MX record verifcation bug when adding domains

### ISSUE THREAD

**Issue by fariszr** [simple-login/app#379]
![image](https://user-images.githubusercontent.com/35614734/110241237-cd20d100-7f60-11eb-9624-dba192a830cc.png)

latest SL self hosted with docker

**Comment by nguyenkims** [comment]
@fareszr is domain.com your domain?

**Comment by fareszr** [comment]
> @fareszr is domain.com your domain?

of course not 😅, i just hidden the domain with Firefox dev tools

**Comment by fareszr** [comment]
Fixed it !
the issue was i didnt add a `.` in simplelogin.env 

changing from 

`EMAIL_SERVERS_WITH_PRIORITY=[(5, "mail.domain.com")]`
to
`EMAIL_SERVERS_WITH_PRIORITY=[(5, "mail.domain.com.")]`
fixed it

**Comment by nguyenkims** [comment]
Oh I see, the server does indeed expect a trailing dot. I usually copy the README and replace the `mydomain.com` everywhere by the actual domain as this can avoid typo like this. We can also modify the code to add the dot if needed, do you want to create a PR for that :) ?

**Comment by fareszr** [comment]
> Oh I see, the server does indeed expect a trailing dot. I usually copy the README and replace the `mydomain.com` everywhere by the actual domain as this can avoid typo like this. We can also modify the code to add the dot if needed, do you want to create a PR for that :) ?

Im not really a developer 😅,  so I'm afraid I can't really help

**Comment by glqejgoeqj** [comment]
Hi,
I am having the same issue as above.
When verificating MX records I get in return the following message:

__Your DNS is not correctly set. The MX record we obtain is:
20 mx2.simplelogin.co.
10 mx1.simplelogin.co.
0 mail.my.domain.com.__ 

CAn someone comment what am I doing wrong? I tried to remove the trailing dot from target adress, but it's giving me the same result.
