### ISSUE TITLE
A custom domain cannot be a built-in domain

### ISSUE THREAD

**Issue by tadinski** [simple-login/app#382]
webapp hosted on app.**xxx.com**
trying to add **xxx.com** as custom domain to use catch-all feature.
get an error on frontend: "a custom domain cannot be a built-in domain"

webapp version: 3.3.0

**Comment by tadinski** [comment]
Have bypassed this by adding the desired domain to custom_domain table

**Comment by akzkak** [comment]
Do the directories feature also work with this bypass and found any drawbacks by doing this?

btw please share ALTER TABLE command you used. First time i used postgres and just editing lifetime to true was a bit of a pain to figure out.

**Comment by tadinski** [comment]
> Do the directories feature also work with this bypass and found any drawbacks by doing this?
> 
> 
> 
> btw please share ALTER TABLE command you used. First time i used postgres and just editing lifetime to true was a bit of a pain to figure out.

- So far, have not found any drawbacks.

- Have not used directories, cannot tell.

- I recommend use a GUI like Postico to access and alter the database.

**Comment by akzkak** [comment]
Managed to login, clone and edit the custom_domain table with Adminer. Works great, so hopefully easy for devs to implement native into simple-login at some time. 

Having catch-all enabled temporarily have saved me hours of manual work getting all my aliases over to this wonderful project. Thanks tadinski!

**Comment by A-Nicoladie** [comment]
For those who prefer the command line, here are the queries I used:

```sql
-- Get your user ID
SELECT id,email FROM users;

-- Add your domain
INSERT INTO custom_domain 
    (created_at,user_id,domain,verified) 
VALUES (NOW(),#YOUR_USER_ID#,'#YOUR.DOMAIN#',FALSE);
```

**Comment by CarlitoGrey** [comment]
Thanks for the SQL above, worked for me - similarly I wanted to use catch-all with a custom domain. 

Having 'forced' the custom domain I think it may have broken the disabling of prefix/suffix generation. My aliases now look like ra+sender.com+fzhkdzixzy@mydomain.com

**Comment by jeifour** [comment]
I was trying to follow the advice in #301 but running into this issue. Is catch-all usable (especially the neat new catch-all with Regex) easily when self-hosting?

**Comment by alpha-tango-kilo** [comment]
@jeifour I haven't had an issue since following [this comment](https://github.com/simple-login/app/issues/382#issuecomment-929994588). I'm self-hosting on a VPS
