### ISSUE TITLE
Move a deleted alias to trash. Trash is emptied after 30 days.

### ISSUE THREAD

**Issue by nguyenkims** [simple-login/app#388]
So user can restore a deleted alias. 

An alias in trash will have the same behavior as a disabled alias regarding receiving emails.

_Originally posted by @nguyenkims in https://github.com/simple-login/app/discussions/387_

**Comment by nguyenkims** [comment]
It turns out the main issues are: 
- users don't realize that once an alias is deleted, it can't be restored.
- most of the times what they need is to **disable** an alias

For these reasons, the website has been updated to highlight the difference between "deleting" and "disabling" 

![image](https://user-images.githubusercontent.com/3167780/112286000-2be98880-8c8b-11eb-9b60-d33fe1a32862.png)

**Comment by Alexander01998** [comment]
Does this only work with custom domains? I can't seem to find the trash for the built-in domains.

**Comment by nguyenkims** [comment]
For alias created with a built in domain, it can't be restored after deletion.
