### ISSUE TITLE
Can you host this with an external SMTP server?

### ISSUE THREAD

**Issue by Leopere** [simple-login/app#39]
I already run my own SMTP server I don't really want to have to fire up a second one when I already have one working quite well is there a way to do this where I can just use that?

**Comment by Leopere** [comment]
This is the email server I want to run https://mailinabox.email/; it's using postfix but it's installed on bare metal.

**Comment by nguyenkims** [comment]
@Leopere Currently we haven't studied installing SimpleLogin alongside with an existing email infrastructure yet. We are going to have a look at mailinabox to see if it can be compatible with SimpleLogin. 

Having a separate domain for SimpleLogin (could be a subdomain) would make things easier though, is this the setup you want to achieve?

**Comment by havedill** [comment]
I got mine to forward through amazon SES

https://github.com/simple-login/app/issues/49

**Comment by nguyenkims** [comment]
@Leopere have you had any update on this issue?

**Comment by Leopere** [comment]
Unfortunately no big progress on my end but it looks like there’s some
motion in this direction on the horizon. I would check back in like 6
months honestly.

**Comment by Leopere** [comment]
Sorry @nguyenkims I didn't realize who you were when you asked me for updates.  It's still something that I want but I haven't had the luxury of time to really give it any further progress.

**Comment by nguyenkims** [comment]
@Leopere no worries, let me know if you need any help.

**Comment by Leopere** [comment]
@nguyenkims I'm actually wondering if you'd be willing to write some kind of compatibility with MailInABox's API
```
Examples:
Try these examples. For simplicity the examples omit the --user me@example.com:yourpassword command line argument which you must fill in with your administrative email address and password.

# Gives a JSON-encoded list of all mail users
curl -X GET https://box.example.com/admin/mail/users?format=json

# Adds a new email user
curl -X POST -d "email=new_user@example.com" -d "password=s3curE_pa5Sw0rD" https://box.example.com/admin/mail/users/add

# Removes a email user
curl -X POST -d "email=new_user@example.com" https://box.example.com/admin/mail/users/remove

# Adds admin privilege to an email user
curl -X POST -d "email=new_user@example.com" -d "privilege=admin" https://box.example.com/admin/mail/users/privileges/add

# Removes admin privilege from an email user
curl -X POST -d "email=new_user@example.com" https://box.example.com/admin/mail/users/privileges/remove
```

**Comment by doanguyen** [comment]
@Leopere can you clarify your use-case? As far as I understood, you have already had an email server running mail-in-a-box and you want SimpleLogin to stay in front of your mail-in-a box server **_or_** just-another-email service to forward/drop incoming SMTP requests?

**Comment by Leopere** [comment]
Mostly just manage the aliases and routing and all of that next to the MailInABox instance so that I'm not required to manage two technologically obese complex services.

Not entirely certain if I'd really want to switch entirely but I definitely would prefer to host some part of this myself if possible I'd even keep my premium subscription for SL just to support the devs but the idea of having yet another man in the middle after going it solo on my own self-hosting setup seems counterproductive.

**Comment by nguyenkims** [comment]
@Leopere mailinabox and SimpleLogin cannot use the same domain as the arriving emails 

- are handled differently: mailinabox stores the emails whereas SimpleLogin forwards them. 
- there's no way to tell which email should be handled by mailinabox and which one handled by SimpleLogin

A suggestion would be using a different domain (or subdomain) for SimpleLogin. In this case you can use a mailinabox email as original email (or mailbox) on SimpleLogin and for SimpleLogin, mailinabox is just another email service.

The user system in SimpleLogin and mailinabox are also completely different so I don't think SimpleLogin will integrate mailinabox API in a near future.

SimpleLogin and mailinabox are both tied to Postfix so I think it's better to use a VM for each. A VM of 1GB RAM should be enough for SimpleLogin if you only use SimpleLogin for yourself (or some friends/family members).

**Comment by Leopere** [comment]
I’m currently using both simple login and mail in a box using the hosted
offering on SimpleLogin.io. That said I’m using SL’s MX record on a sub
domain like @sl.example.com then they forward’s to myemail@example.com

**Comment by nguyenkims** [comment]
I close this issue as we this is not clear what we should do ....

**Comment by chiefbrain** [comment]
> 
> 
> I already run my own SMTP server I don't really want to have to fire up a second one when I already have one working quite well is there a way to do this where I can just use that?

I understand this as running only one instance of postfix.


MailInABox lets you manage email domains, mailboxes and aliases (and stores this data in sqlite).
SimpleLogin lets you manage forwardings (and stores data in postgresql).

If a separate domain like @sl.example.com is used for SimpleLogin, only one postfix instance seems required.
MailInABox relies on virtual_mailboxes (using sqlite).
SimpleLogin relies on relay_domains (using postgresql).

If you are setting up SimpleLogin in your MailInABox instance, instead of using the SimpleLogin postfix config, adding relay_domains and transport_maps to the MailInABox's postfix config could work (besides adding the files and postgres support to postfix).

**Comment by europacafe** [comment]
> > I already run my own SMTP server I don't really want to have to fire up a second one when I already have one working quite well is there a way to do this where I can just use that?
> 
> I understand this as running only one instance of postfix.
> 
> MailInABox lets you manage email domains, mailboxes and aliases (and stores this data in sqlite). SimpleLogin lets you manage forwardings (and stores data in postgresql).
> 
> If a separate domain like @sl.example.com is used for SimpleLogin, only one postfix instance seems required. MailInABox relies on virtual_mailboxes (using sqlite). SimpleLogin relies on relay_domains (using postgresql).
> 
> If you are setting up SimpleLogin in your MailInABox instance, instead of using the SimpleLogin postfix config, adding relay_domains and transport_maps to the MailInABox's postfix config could work (besides adding the files and postgres support to postfix).

Has anyone successfully done this approach?
I have docker-mailserver running already and wish to have simplelogin on top of it. Any details how to do it?
