### ISSUE TITLE
Postgres Docker Container

### ISSUE THREAD

**Issue by andersonm66** [simple-login/app#392]
Run a Postgres Docker container as your Postgres database server. Make sure to replace myuser and mypassword with something more secret.

sudo docker run -d \
    --name sl-db \
    -e POSTGRES_PASSWORD=mypassword \
    -e POSTGRES_USER=myuser \
    -e POSTGRES_DB=simplelogin \
    -p 5432:5432 \
    -v $(pwd)/sl/db:/var/lib/postgresql/data \
    --restart always \
    --network="sl-network" \
    postgres:12.1

To test whether the database operates correctly or not, run the following command:

sudo docker exec -it sl-db psql -U myuser simplelogin

you should be logged in the postgres console. Type exit to exit postgres console

If you implement exactly as proposed you get the following error

root@localhost:~# sudo docker exec -it sl-db psql -U myuser simplelogin
psql: error: could not connect to server: FATAL:  role "myuser" does not exist

The same applies if you change the user and password.

**Comment by nguyenkims** [comment]
@andersonm66 hi it seems that your docker command doesn't have the back slash character (`\`) for multiline command. Have you created the docker network first by running the following command?

```
sudo docker network create -d bridge \
    --subnet=240.0.0.0/24 \
    --gateway=240.0.0.1 \
    sl-network
```
