### ISSUE TITLE
Customize self-hosted environment

### ISSUE THREAD

**Issue by rajaseg** [simple-login/app#428]
@nguyenkims is there a way to modify self hosted environment?

1. Upload custom logo
2. Modify mail templates to include custom logo and footer notes
3. Include custom terms page and enable Captiva in registration page

**Comment by nguyenkims** [comment]
@rajaseg hey the self-hosted version is meant for a personal use so I don't think features like custom logo or custom footer notes are necessary. This might be wrong though, can you tell me more about what do you want do with your self-hosted SimpleLogin instance?

**Comment by rajaseg** [comment]
> @rajaseg hey the self-hosted version is meant for a personal use so I don't think features like custom logo or custom footer notes are necessary. This might be wrong though, can you tell me more about what do you want do with your self-hosted SimpleLogin instance?

@nguyenkims I wanted to self host. But some how if I want to offer service like Simplelogin, like asked in https://github.com/simple-login/app/issues/361

**Comment by nguyenkims** [comment]
@rajaseg feel free to fork SimpleLogin in this case to be able to fully customize SimpleLogin :). We might change our license from MIT to AGPL in the future though that'd require you contributing back to the project. But as the licence is currently MIT, there should be no limit.
