### ISSUE TITLE
More documentation for custom docker networks

### ISSUE THREAD

**Issue by AzuritBadger** [simple-login/app#446]
Hi,

I recently got SimpleLogin to run on my own server. During the process, I discovered some things one could improve in the self hosting instructions. 

As mentioned in #44, SpamAssasin doesn't like the `240.0.0.0/24` network. Therefore a different subset should be used, like `10.0.0.1/24` or something similar. 

When I chose said subnet, SimpleLogin wasn't able to send or recive emails. After some trial and error I figured out that `POSTFIX_SERVER` inside the env file needs to point to the gateway of the docker network for SimpleLogin to function correctly.

Therefore, my suggestion is to add some more documentation about custom docker networks. For example, in the _Run SimpleLogin Docker containers_ section, one could add: If your docker network has a different subnet than the one used above, you need to set `POSTFIX_SERVER` to the gateway of your docker network. Otherwise SimpleLogin will not be able to send or recive emails.

Or SimpleLogin could use the gateway of the network as the default postfix server IP. 

So far I really enjoy SimpleLogin and hope this project can continue to grow. Thank you for this awsome service 💯

**Comment by nguyenkims** [comment]
@AzuritBadger that's a good idea to have a section for a custom Docker network. Do you want to create a PR to include this doc :)?

We wanted to change the 240.0.0.0 network to 10.0.0.0 but as this network is already used in some installations, this change would break these installations ...
