### ISSUE TITLE
Email not received on a specific provider

### ISSUE THREAD

**Issue by IwishIcanFLighT** [simple-login/app#447]
Hi there,

I just finished installing a self-hosted instance, but it seems like I can't receive the sign-up confirmation email from the app on my main email address.
After reading through #319, I tested the `send_email("abc@xyz.com, "Title", "Body")` command to make sure my server was able to send anything and sure enough I can receive the test email on my gmail account and on a custom domain email address I own. But the email address (finishing with `@gmx.fr`) that I actually want to protect with SimpleLogin won't receive anything from my server...

Any help is appreciated, thanks!

**Comment by nguyenkims** [comment]
Hey can you look at the content of Postfix log (usually located at `/var/log/mail.log`) that might contain information about why the email can't reach @gmx.fr address. Some email services have a pretty strict anti spam rule which is based on your IP address and your domain (among other things).
