### ISSUE TITLE
Firefox extension not using the current website name

### ISSUE THREAD

**Issue by OmiCron07** [simple-login/app#465]
I'm using the Firefox extension, but I would like that the SL icon beside the email input, when clicked, insert the "websitedomain@mydomain.com" instead of "ramdom@random.com". I know I can create exactly that email format in the extension's panel, but I would like to use the button directly beside the input box.

**Comment by nguyenkims** [comment]
You can choose the default domain used when generating an alias by setting the "default domain for aliases." option on the Settings page at https://app.simplelogin.io/dashboard/setting

![default-alias-domain](https://user-images.githubusercontent.com/3167780/118050420-834cd080-b37f-11eb-94c1-6ed52c9382a6.png)

**Comment by OmiCron07** [comment]
Ok, now I need the first part of the email matching the website I'm currently on. The extension already supports that, but just in the extension's panel, not from the button.

![image](https://user-images.githubusercontent.com/31325575/118051843-b2e3e480-b34f-11eb-9af1-6272d70b6680.png)

**Comment by nguyenkims** [comment]
@OmiCron07 hey this feature is requested in https://github.com/simple-login/app/discussions/471, feel free to upvote it to make it happen sooner :).
