### ISSUE TITLE
Unable to login with MFA "Incorrect Token"

### ISSUE THREAD

**Issue by gp1019** [simple-login/app#487]
## Bug report

**Describe the bug**

Any attempt to login with 2FA fails. No matter the browser or account being logged in.

**Expected behavior**

Allow me to login to account.

**Comment by nguyenkims** [comment]
Do you know if the same problem happens on other browser?

**Comment by gp1019** [comment]
Yep, and I wrote it in the report.

**Comment by nguyenkims** [comment]
Ah sorry, I have skimmed too quickly ... By 2FA, you mean the 6 number code right (and not the security key)? Can you check if your computer clock is synced? The 2FA (TOTP) depends on time and doesn't work if the clock doesn't match.

**Comment by gp1019** [comment]
Oh you're fine, sorry for it sounding condescending. Yes, the 6 number code for 2FA (TOTP). It seems to be almost an entire minute behind, I'll see if that's the problem.

**Comment by nguyenkims** [comment]
@gp1019 no worries, it's actually my fault :). Please let me know if the problem is solved after the clock is synced.

**Comment by gp1019** [comment]
It works! It _was_ the clock, and now I can login on either browser and/or account. Thank you!
