### ISSUE TITLE
No MX Domain for gmail.com

### ISSUE THREAD

**Issue by Rustymage** [simple-login/app#488]
Hi,

I've noticed that some aliases on my self hosted instance are not coming through.

I can recieve messages to my alias from some businesses but not others. Facebook doesn't appear to send to my domain alias.

I've done some debugging and found that sending an email to the alias via Gmail does not go through, whereas Outlook works. Gmail does not seem to send me delivery failure reports. I've also found I do not get a Simplelogin template email when I send an email to my alias from the linked mailbox.

Any suggestions? Do you see this with the serivce you offer?

Thanks in advance!

👍

**Comment by Rustymage** [comment]
Fixed - it appears that my Cloudflare instance was proxying and deferring my emails. After switching it oof, the deferred messages are now delivering.

**Comment by Rustymage** [comment]
It seems this is rearing its head again. I have may undelivered emails and upon exporting and trying to reinstall, I cannot get past the register screen:

```

2021-05-31 17:29:45,522 - SL - DEBUG - "/code/app/email_utils.py:499" - email_can_be_used_as_mailbox() -  - No MX record for domain mydomain.com


2021-05-31 17:29:45,530 - SL - DEBUG - "/code/server.py:444" - after_request() -  - IPADDRESS POST /auth/register ImmutableMultiDict([]) 200
```

Help please.

**Comment by Rustymage** [comment]
```
ubuntu@ubuntu:~$ dig gmail.com mx

; <<>> DiG 9.16.1-Ubuntu <<>> gmail.com mx
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41246
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;gmail.com.                     IN      MX

;; ANSWER SECTION:
gmail.com.              3593    IN      MX      5 gmail-smtp-in.l.google.com.
gmail.com.              3593    IN      MX      20 alt2.gmail-smtp-in.l.google.com.
gmail.com.              3593    IN      MX      10 alt1.gmail-smtp-in.l.google.com.
gmail.com.              3593    IN      MX      30 alt3.gmail-smtp-in.l.google.com.
gmail.com.              3593    IN      MX      40 alt4.gmail-smtp-in.l.google.com.

;; Query time: 27 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Tue Jun 01 16:18:05 BST 2021
;; MSG SIZE  rcvd: 161
```

When the container performs an MX check, does it specify a DNS IP? My system is set to re-route to its own DOH with PiHole.

:)

**Comment by nguyenkims** [comment]
> When the container performs an MX check, does it specify a DNS IP?

I think by default the container uses the same DNS server as the host but I'm not a DNS expert ... I think you can try to disable the routing to PiHole to see if the problem is solved and debug from there.

**Comment by Rustymage** [comment]
So I followed this tutorial for my USG & Pihole setup: https://scotthelme.co.uk/catching-naughty-devices-on-my-home-network/

Basically, any DNS request that didn't used the DHCP allocated DNS server, was 'rerouted' to it. This causes issues when using `dig @1.1.1.1` with unexpected source responses. 

I turned this feature off and SL no longer reported `MX` issues with `gmail.com`.

I'll see how this goes but the odd thing is, I had the DNS 'reroute' present months ago when I first setup SL and it never caused an issue. I can only think that something had crept in the code from the initial `3.2.2` I had and caused me issues.

I'll close this again and reopen, if the error occurs again.

**Comment by 0xspade** [comment]
Hi,

Did you already fix this one? I'm having the same issue where I can't receive any emails from GMAIL. Tried from different SMTP servers or email providers (protonmail,ctemplar, etc.) and I can receive their emails.

**Comment by Rustymage** [comment]
> Hi,
> 
> Did you already fix this one? I'm having the same issue where I can't receive any emails from GMAIL. Tried from different SMTP servers or email providers (protonmail,ctemplar, etc.) and I can receive their emails.

No, I'm not having these issue again.

**Comment by teeruku-github** [comment]
I have the same issue. Interestingly running dig from the container does yeild results. not sure what is wrong.
