### ISSUE TITLE
Import/Export aliases and data.

### ISSUE THREAD

**Issue by pluja** [simple-login/app#491]
I want to leave my self-hosted instance and migrate to your paid solution. Is there any possibility to migrate all my aliases there? I have a lot of aliases so doing it manually is a bit of a headache.

**Comment by nguyenkims** [comment]
Yes you can import aliases to SimpleLogin SaaS version. The export/import can be done on the Settings page :).

**Comment by pluja** [comment]
True, I was not using the latest version and I couldn't see the export option. Thanks.
