### ISSUE TITLE
Office365 Calendar Invites Not Coming Through

### ISSUE THREAD

**Issue by BadCo-NZ** [simple-login/app#492]
Hi,

Since moving to SimpleLogin with my ProtonMail account, I am having issues with receiving calendar invites from MS Office365 accounts. I have tested this with both my work email and the wife's work email, both are Office365 but from different companies.

Previously the invites would come through as an attachment and in the email itself, now it is completely blank.

I have also tested with gmail, which worked fine.

Before and after screenshots attached.

Before:
![Screenshot from 2021-05-28 18 42 45](https://user-images.githubusercontent.com/50016048/119949041-fdd53d00-bf88-11eb-97a3-6c3e2bcfdb1c.png)

After:
![Screenshot from 2021-05-28 18 43 12](https://user-images.githubusercontent.com/50016048/119949090-0f1e4980-bf89-11eb-8354-527366dc51a8.png)

Anyone have any ideas?

**Comment by Scr0nch** [comment]
I am also having this issue. Someone sent me an invite to a Microsoft Teams meeting and the calendar invite information was stripped out.

@BadCo-NZ did you find a solution?

**Comment by BadCo-NZ** [comment]
Hi @Scr0nch, unfortunately I have not found a solution :(

**Comment by BadCo-NZ** [comment]
@nguyenkims you have closed this with no comment or solution?

**Comment by nguyenkims** [comment]
@BadCo-NZ I run though all issues and close the ones that we don't have any new update.

Do you know if the issue is still there? Can you see the attachment on other clients (ios, android)?

**Comment by BadCo-NZ** [comment]
> Do you know if the issue is still there? Can you see the attachment on other clients (ios, android)?

Thanks for the reply.

Yeah the issue still exists, and on the Protonmail Android app as well.

**Comment by nguyenkims** [comment]
@BadCo-NZ I just tested with an outlook invite and the calendar invite arrives to my mailboxes. I created an invite via this UI on outlook:

<img width="730" alt="image" src="https://user-images.githubusercontent.com/3167780/165053673-73194b45-0207-4150-9032-93cfea32fecc.png">

Please note that SimpleLogin doesn't send emails sent from a mailbox to its own alias so if you want to test, please make sure your Outlook address isn't one of your mailboxes (or any of the "authorized addresses").

**Comment by BadCo-NZ** [comment]
@nguyenkims is that using Protonmail as the receiver?

**Comment by nguyenkims** [comment]
@BadCo-NZ yes I tested with both my Proton and Gmail mailbox.
