### ISSUE TITLE
Feature Request: Block incoming emails.

### ISSUE THREAD

**Issue by houtknots** [simple-login/app#493]
For some of my domains, I'm using an info@ address because I've registered these in the past. The problem I'm facing now is that I get daily emails from 1 specific email address that I would like to block.

At this time, it is only possible to disable the info @ alias. What I would really like to see is that you can turn off certain contacts just like you can with aliases.

(Example picture below)

![contacts](https://jhcsmedia.com/?f=2021-05-28_5P9j5bVesj8AqZ2g.png)

**Comment by nguyenkims** [comment]
@houtknots I wonder if this feature is similar to https://github.com/simple-login/app/discussions/406 ?

**Comment by houtknots** [comment]
@nguyenkims It indeed is, I will close this issue.
