### ISSUE TITLE
Rejected email by spamcop not shown in quarantine

### ISSUE THREAD

**Issue by luisgepeto** [simple-login/app#497]
## Prerequisites
- [x ] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**
One of my alias is not receiving an email from expressvpn. After looking at the quarantine page, the email is also not found.
After looking at the `/var/log/mail.log` file I get the following exception

> Jun  1 01:06:27 myselfhosteddomain postfix/smtpd[2376668]: connect from o2.outbound-email.expressvpn.com[167.89.94.22]
> Jun  1 01:06:28 myselfhosteddomain postfix/smtpd[2376668]: NOQUEUE: reject: RCPT from o2.outbound-email.expressvpn.com[167.89.94.22]: 554 5.7.1 Service unavailable; Client host [167.89.94.22] blocked using bl.spamcop.net; Blocked - see https://www.spamcop.net/bl.shtml?167.89.94.22; from=<bounces+13588-a3ea-my_alias=myselfhosteddomain.com@email.expressvpn.com> to=<my_alias@myselfhosteddomain.com> proto=ESMTP helo=<o2.outbound-email.expressvpn.com>
> Jun  1 01:06:28 myselfhosteddomain postfix/smtpd[2376668]: lost connection after RCPT from o2.outbound-email.expressvpn.com[167.89.94.22]
Jun  1 01:06:28 myselfhosteddomain postfix/smtpd[2376668]: disconnect from o2.outbound-email.expressvpn.com[167.89.94.22] ehlo=2 starttls=1 mail=1 rcpt=0/1 commands=4/5

**Expected behavior**
The email is either received by my alias or shown in the quarantine box

**Environment (If applicable):**
 - OS: Linux

**Additional context**
Other email are shown in the quarantine box

**Comment by nguyenkims** [comment]
From the log, it seems that expressvpn.com is blocked because it's listed in SpamCop blocklist. As a workaround, you can explicitly whitelist expressvpn.com or remove SpamCop from your Postfix config. The real solution is rather expressvpn solving this issue as being listed by SpamCop affects their email delivery.

**Comment by luisgepeto** [comment]
Hi @nguyenkims thanks for the answer, shouldn't this email be stored under the quarantine folder? 
As a user, I feel like I need to see whether any email directed to my aliases was marked as spam. Such as a regular mailbox has access to its spam folder. 
Maybe I am misunderstanding the purpose of the Quarantine folder?
Thanks!

**Comment by nguyenkims** [comment]
@luisgepeto in the above case, the email is blocked by Postfix before actually reaching SimpleLogin ... The Quarantine is rather for temporarily storing forwarded emails that are refused/bounced by your mailbox.

**Comment by luisgepeto** [comment]
Should simple login users have a way of knowing this happened? Isn't this the way the spam folder behaves in a regular mailbox?

**Comment by nguyenkims** [comment]
@luisgepeto currently, the only way to know is to look at Postfix log unfortunately. In the future, it might be interesting that SimpleLogin also receives Postfix notification about emails being refused. This might create a lot of noise though as an email server receives a lot of spams and Postfix is doing a great job of filtering them out.

**Comment by luisgepeto** [comment]
Thanks, I will add this as a feature request
