### ISSUE TITLE
Can't receive emails from mailbox

### ISSUE THREAD

**Issue by dario617** [simple-login/app#498]
## Prerequisites
- [ x ] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**
I have an alias like alias@sl.com with a mailbox like example@gmail.com
If I send an email to that alias from example@gmail.com I don't receive my email 😢 

I sent another email to the alias and I got through so I'm guessing that the system doesn't allow you to send emails to yourself from the respective alias mailbox. Is this a bug or a feature?

**Expected behavior**
I expected to receive my email on my mailbox fowarded from simplelogin

**Aditional info**
The experiment was done using a protonmail account and a gmail account

**Comment by fily1212** [comment]
I have the same issue, it seems that we can't receive and send email because all is down....

**Comment by dario617** [comment]
Apparently this is a feature as I received an email later :)
![Screenshot from 2021-06-01 20-13-35](https://user-images.githubusercontent.com/7097907/120405204-0c6b7d80-c316-11eb-9b71-ff8250085702.png)
