### ISSUE TITLE
How can you prevent new sign ups?

### ISSUE THREAD

**Issue by havedill** [simple-login/app#50]
I'd like to disable registration

**Comment by nguyenkims** [comment]
@havedill that's a relevant feature for self-hosting indeed. Just added into our roadmap here https://trello.com/c/NxNFTHwI/24-setting-to-disable-registration. We will work on it next week.

**Comment by nguyenkims** [comment]
@havedill once this PR https://github.com/simple-login/app/pull/57 is deployed, you could disable registration anytime by setting `DISABLE_REGISTRATION` param and restart the `webapp` docker container.

**Comment by havedill** [comment]
Works great, thank you.
