### ISSUE TITLE
Recommended backup method

### ISSUE THREAD

**Issue by pluja** [simple-login/app#500]
How should I backup my simplelogin instance? I can't seem to find any info about this on the documentation.

**Comment by Metabaron1** [comment]
The main data to  backup is the database. I rsync the whole ~/sl and config files (env / yml).
I lose my instance once after an OS update, but I was able to restore/install everything in a new VM within an hour from this backup without losing any aliases.
But I run everything from docker, postfix/nginx included so nothing else than docker to install...

**Comment by pluja** [comment]
Thanks!
