### ISSUE TITLE
After changing your password, it does not ask for 2FA

### ISSUE THREAD

**Issue by LongJohn-Silver** [simple-login/app#503]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**

If you forget your password, and go through the process of changing it by going to your e-mail, after you select your new password, it does not ask for your 2FA token, which can be used to gain access to your account.

**Expected behavior**

After changing your password, it still should ask your 2FA token, if you have also lost access to this, it should let you use one of your back up codes as a last resort.

**Screenshots**

N/A

**Environment (If applicable):**

 - OS: N/A
 - Browser: Firefox
 - Version: Nightly 91.0a1

**Additional context**

N/A

**Comment by nguyenkims** [comment]
@LongJohn-Silver thanks for reporting this bug! It has been fixed now :)

**Comment by LongJohn-Silver** [comment]
It is nothing, I'll be closing it then!
