### ISSUE TITLE
Option to remember 2FA for longer than one month

### ISSUE THREAD

**Issue by Elaborendum** [simple-login/app#505]
There's already a "remember me for a month" option, but it would be nice to have an extra option for SimpleLogin not to ask on for an indefinite amount of time. It's a bit annoying to have to set it up every month at the computer that never leaves my house.

Maybe it has been discussed before, that for security reasons a month will be the maximum. It would be understandable nonetheless.

**Comment by nguyenkims** [comment]
@Elaborendum are you referring to the web app or mobile app? On the web, the cookie is saved for 7 days so you don't have to login again if you often open SimpleLogin web app.

**Comment by Elaborendum** [comment]
The web app. I was referring to the 2FA cookie (?), which, if I remember correctly, had an option for it to last for about a month. As in, my request was asking for a way to extend that time for longer than a month.

On the other hand, thank you, that explains some of my confusion. I was under the impression that I would stay logged in for about a month the same way I wouldn't need to input a 2FA code for about a month. I always thought that it was a bug on my end.

**Comment by nguyenkims** [comment]
@Elaborendum I think extending the MFA over 30 days isn't ideal from a security standpoint and is a good tradeoff between convenience and security. It seems to be used by other services as well.

**Comment by Elaborendum** [comment]
Thank you, I understand. The earlier explanation helped my problem regardless.
