### ISSUE TITLE
DKIM DNS record contradicting instructions

### ISSUE THREAD

**Issue by mshavliuk** [simple-login/app#506]
There are two different ways to set up the DKIM record in the DNS configurations, proposed in this repo.

### 1. From domain page (CNAME)
> Add the following CNAME DNS record to your domain.
> ```
> Record: CNAME
> Domain: dkim._domainkey
> Value: dkim._domainkey. mydomain.com.
> ```

<details>
<summary>Source</summary>

https://github.com/simple-login/app/blob/45b0acc1c46e22d7fd4ff3ce885724db9b2dc3c4/app/dashboard/templates/dashboard/domain_detail/dns.html#L176-L191

</details>

### 1. From Readme (TXT)
> Set up DKIM by adding a TXT record for `dkim._domainkey.mydomain.com.` with the following value:
>
> ```
> v=DKIM1; k=rsa; p=PUBLIC_KEY
> ```
> with `PUBLIC_KEY` being your `dkim.pub.key`

<details>
<summary>Source</summary>

https://github.com/simple-login/app/blob/8262d3559daa126d9e8f6db5ea61feb2ec2e0f09/README.md#L120-L126

</details>

I did manage to pass the validation and get `SPF Verified ✅` badge in the **DKIM** section of my domain page (https://app.mydomain.com/dashboard/domains/1/dns) only by using the **first** option with CNAME, but still I'm not sure if omitting the public key is a good idea 🤔

So at the end of the day, which method should be preferred?

**Comment by developStorm** [comment]
If you are hosting SL on your own server then I'd say put PK directly in your TXT record would be better as it saves a DNS query for others. However `CNAME` means to redirect all type of queries of this domain to another domain and use their records as our responds. It basically transferred your control of that subdomain to the domain you are pointing to. The final DNS lookup result should be identical in both way.
