### ISSUE TITLE
How to block email on ios app

### ISSUE THREAD

**Issue by Samk19** [simple-login/app#507]
Cannot find any way to block the emails on simplelogin app on ios 

Is it done automatically? Or do we have to write any command or something like that to block an email address

**Comment by nguyenkims** [comment]
Do you think this ticket corresponds to what's described? https://github.com/simple-login/app/discussions/406

**Comment by corvec** [comment]
@Samk19 On iOS I see toggles that disable email forwarding addresses at the bottom left of each card. Disabling an email address blocks future emails sent to that address from being forwarded. Is that what you want?

You can also filter at the top with the "Inactive" tab to view all of those disabled addresses.

![image](https://user-images.githubusercontent.com/755349/123517500-545c9680-d66f-11eb-8a37-1a7cbb6199cf.jpeg)

On the other hand if you want to block a sender then #406 covers that functionality. Right now, on the client end (e.g., in GMail or ProtonMail) you can create a filter based off of the sender name ("spammer at spam.com") and immediately delete it - just make sure to not mark such emails as spam. You'll also need to set the sender address format up to match in SL.
