### ISSUE TITLE
Export Alias lacks email id on which forward 

### ISSUE THREAD

**Issue by mycal123** [simple-login/app#508]
I made over 200 alias  i reuse them. I forwarded them  to 2 mail id

Now i want to export them  with list of alias based on email id on which it is forwarded saparately or want to saparate them into 2 part.

But how to saparate them now?

**Comment by TheLastProject** [comment]
The "Export Aliases" option should contain the destination email address(es) in the "mailboxes" field. Is this not what you're looking for?
