### ISSUE TITLE
Not able to receive mail on my mail domain

### ISSUE THREAD

**Issue by pcdiks** [simple-login/app#510]
I followed the installation instructions and have every up and running.
I'm able to login to the web-app and to create a custom alias.

However, I'm not able to receive mail on the alias. I'm getting this in my postfix logs (i redacted the logs and changed it to mydomain.com):
```
Jun 17 17:39:36 apache03 postfix/smtpd[1488118]: connect from smtp-backup.dca.wordpress.com[192.0.97.107]
Jun 17 17:39:37 apache03 postfix/smtpd[1488118]: NOQUEUE: reject: RCPT from smtp-backup.dca.wordpress.com[192.0.97.107]: 450 4.1.2 <avd-newsletter@mydomain.com>: Recipient address rejected: Domain not found; from=<avd-newsletter=mydomain.com@b.wordpress.com> to=<avd-newsletter@mydomain.com> proto=ESMTP helo=<smtp-backup.dca.wordpress.com>
Jun 17 17:39:37 apache03 postfix/smtpd[1488118]: disconnect from smtp-backup.dca.wordpress.com[192.0.97.107] ehlo=2 starttls=1 mail=1 rcpt=0/1 data=0/1 rset=1 quit=1 commands=6/8
Jun 17 17:41:39 apache03 postfix/smtpd[1489117]: connect from smtp-backup-out2.bur.wordpress.com[192.0.123.45]
Jun 17 17:41:40 apache03 postfix/smtpd[1489117]: NOQUEUE: reject: RCPT from smtp-backup-out2.bur.wordpress.com[192.0.123.45]: 450 4.1.2 <avd-newsletter@mydomain.com>: Recipient address rejected: Domain not found; from=<avd-newsletter=mydomain.com@b.wordpress.com> to=<avd-newsletter@mydomain.com> proto=ESMTP helo=<smtp-backup-out2.bur.wordpress.com>
Jun 17 17:41:40 apache03 postfix/smtpd[1489117]: disconnect from smtp-backup-out2.bur.wordpress.com[192.0.123.45] ehlo=2 starttls=1 mail=1 rcpt=0/1 data=0/1 rset=1 quit=1 commands=6/8
```

I added the two pgsql files and replaced mydomain.com with my own domain.
There are no errors in the other logs.

I would expect to see that postfix would receive the mail on mydomain.com

**Comment by nguyenkims** [comment]
The error seems to be `Domain not found` which suggests that the pgsql files are maybe not taken into account correctly. Can you try to restart Postfix to see if the problem persists? If the issue is still there, I'd suggest to re-follow the setup instructions ...

**Comment by pcdiks** [comment]
I checked the files again and they are the same as the examples. So i tested the psql integratie with postmap:

```
postmap -q mydomain.com pgsql:/etc/postfix/pgsql-relay-domains.cf
mydomain.com
```
So that seems to work but in the logs I still get the  Recipient address rejected: Domain not found error...

**Comment by nguyenkims** [comment]
I just tested with another setup and the error when the pgsql file isn't set up is rather "Relay access denied" and not "Domain not found". I don't have any idea for now ...

**Comment by pcdiks** [comment]
I use ubuntu 20.04 to run the software. What do you use?

**Comment by nguyenkims** [comment]
@pcdiks I'm using Ubuntu 18

**Comment by nguyenkims** [comment]
@jeifour this error is indeed a DNS error. Usually with a small number of emails, you shouldn't have any DNS issue.
Do you receive a lot of emails on your server?

**Comment by jeifour** [comment]
> Do you receive a lot of emails on your server?

Mail volume is pretty low and the machine has plenty headroom. Maybe something similar to this happening: https://askubuntu.com/questions/38106/using-dns-lookup-in-chroot-postfix Because it breaks after a restart completely for all mails, and then is completely fixed after I take notice and manually restart postfix.

**Comment by nguyenkims** [comment]
This can be indeed the cause. I don't know much about DNS stuff unfortunately ...
