### ISSUE TITLE
(Empty) response

### ISSUE THREAD

**Issue by houtknots** [simple-login/app#517]
Please note that this is only for bug report. 

For help on your account, please reach out to us at hi[at]simplelogin.io. Please make sure to check out [our FAQ](https://simplelogin.io/faq/) that contains  frequently asked questions.

For feature request, you can use our [forum](https://github.com/simple-login/app/discussions/categories/feature-request). 

For self-hosted question/issue, please ask in [self-hosted forum](https://github.com/simple-login/app/discussions/categories/self-hosting-question)

## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported. (I saw similar issues however I couldn't come up with an answer)

## Bug report

**Describe the bug**
When I add a new custom_domain and do a DNS check I get the response: (Empty)

I've tried changing nameservers and using other domains but to no avail. The custom domains that I already had still work, but the moment I do a dns check again, it also goes wrong.

**Expected behavior**
I expect my DNS check to indicate that the DNS zone is set correctly. Unfortunately SimpleLogin gives the (Empty) response

**Screenshots**
![image](https://user-images.githubusercontent.com/31192098/123710165-8b4ccb00-d86e-11eb-9c7a-e920ebd8d7c1.png)

![image](https://user-images.githubusercontent.com/31192098/123710221-a4ee1280-d86e-11eb-940e-916f516ebbaf.png)

**Environment (If applicable):**
 - OS: Linux (SimpleLogin Server), Windows (Cliënt to access SimpleLogin)
 - Browser: Firefox, Brave, Edge
 - Version: [Simple Login - 3.4.0] - [Brave browser: 1.26.67, Firefox Version: 88.0.1, Edge Version: 91.0.864.59]

**Additional context**
N/A

**Comment by nguyenkims** [comment]
@houtknots can you send us the domain to hi[at]simplelogin.io so we can investigate? Sometimes a DNS update can take several hours.
