### ISSUE TITLE
Easy Way to Decrypt PGP Message

### ISSUE THREAD

**Issue by WaseemAhmed** [simple-login/app#518]
Is there a way to decrypt the PGP message easily, current functionality is quite difficult for normal users, need to use any online PGP decrypt website, paste PGP Message, Private Key, and Passphrase in order to decrypt the message?
Is there a way to add functionality like FlowCrypt?  FlowCrypt sends a link with an encrypted email to easily decrypt messages, the only password is required.

**Comment by nguyenkims** [comment]
@WaseemAhmed if you use a mailbox service that already supports PGP like ProtonMail or Gmail with FlowCrypt, then the decryption should happen automatically.

**Comment by WaseemAhmed** [comment]
Thanks, @nguyenkims it worked, is there any possibility of simple login release their own extension, we don't have to rely on any third-party service, simple login will going to have end to end solution.

**Comment by nguyenkims** [comment]
@WaseemAhmed currently we don't have any plan to support PGP in our Chrome/Firefox extension. Open-source extensions like FlowCrypt are actually doing a good job of making PGP accessible.

**Comment by WaseemAhmed** [comment]
@nguyenkims thanks for the prompt, it makes a sense. closing the issue.
