### ISSUE TITLE
Initiate Conversation from Alias with Re-usable Address

### ISSUE THREAD

**Issue by FrenchToucan** [simple-login/app#519]
Allow users to initiate a conversation from an alias without having to go to the web app to generate a one-time use address.

Like this functionality in AA: https://anonaddy.com/help/sending-email-from-an-alias/

**Comment by nguyenkims** [comment]
@FrenchToucan In this thread https://trello.com/c/bXxgiDBI/80-use-a-special-format-for-reverse-alias-that-can-be-created-on-the-fly, we have discussed extensively about using a special formula for the reverse-alias and in our opinion, this isn't a good idea.

**Comment by FrenchToucan** [comment]
Understood. I appreciate the follow-up.
