### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by havedill** [simple-login/app#52]
Just did a fresh rebuild. Will post my SES setup later;

After the fresh build, my activation email had a bad activate url;

![image](https://user-images.githubusercontent.com/34009509/73185466-bbc19000-40e3-11ea-8b99-9f7083c1c95f.png)

**Comment by nguyenkims** [comment]
What is your `URL` param value in the setting file? This param is used to construct the url in some emails.

**Comment by havedill** [comment]
Oh it's set to localhost:7777. That's probably it then -.- 

Sorry I didn't catch that
