### ISSUE TITLE
Support for S/MIME

### ISSUE THREAD

**Issue by tatticoder** [simple-login/app#527]
Does Simple Login support digital signatures emails to verify you as the legitimate sender of the message. 
I was able to generate `Secure/Multipurpose Internet Mail Extensions` certificate for my private domain based email but could not attach it via Mozilla Thunderbird.
I checked documentation but could not find anything relevant.

**Comment by nguyenkims** [comment]
Hi currently SimpleLogin doesn't support digital signature yet. Please feel free to create a feature request on https://github.com/simple-login/app/discussions along with additional info that might help the implementation :)

**Comment by muibusan** [comment]
This is the link to the request: https://github.com/simple-login/app/discussions/535 :) Please vote
