### ISSUE TITLE
Unknown contact visibility

### ISSUE THREAD

**Issue by selicce** [simple-login/app#537]
## Prerequisites
- [ ] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

For some reason I can see unknown accounts in my Simplelogin contact list. I've saved a screenshot of the 1st page, but for privacy purposes will not post it here. I've also emailed hi[at]simplelogin.io

**Screenshots**
Not posted for privacy reasons

**Environment (If applicable):**
 - OS: Mac
 - Browser: Firefox
 - Version [89.0.2]

**Comment by nguyenkims** [comment]
@selicce thanks for letting us know! This issue should be fixed now :)
