### ISSUE TITLE
Roadmap link points to Trello

### ISSUE THREAD

**Issue by leggomyinfo** [simple-login/app#539]
Roadmap link in the About menu links to Trello instead of GitHub. Flagging this in case it’s unintentional.

**Comment by nguyenkims** [comment]
@leggomyinfo thanks for reporting it, this is indeed an error! Do you know where is the About menu links you mentioned?

**Comment by nguyenkims** [comment]
Oh I see, @ntnhon do you think can we update the link the next app version :) ?

**Comment by ntnhon** [comment]
Hi, thank you for reporting. I'll have it updated :)
