### ISSUE TITLE
Custom aliases with random suffix don't show in custom domain trash when deleted

### ISSUE THREAD

**Issue by ppoffice** [simple-login/app#540]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**
Custom aliases that are created with random suffix, such as `simplelogin.abcde@mydomain.com`, don't end up in deleted alias (aka Trash) of the custom domain (`mydomain.com`).

**Expected behavior**
They should be in the trash. Or is it the intended behavior that they do not?

**Screenshots**

**Environment (If applicable):**
 - OS: Linux, Mac, Windows
 - Browser: Firefox, Chrome, Brave, Safari
 - Version [e.g. 78]

**Additional context**
Seems like domain ID is not consider for this kind of suffixes when creating aliases:
https://github.com/simple-login/app/blob/3.4.0/app/dashboard/views/custom_alias.py#L197

```python
# alias_suffix is something like `.abcde@mydomain.com`
try:
    alias_suffix = signer.unsign(signed_suffix, max_age=600).decode()
except SignatureExpired:
    ...

custom_domain_id = None
# get the custom_domain_id if alias is created with a custom domain
if alias_suffix.startswith("@"):
    alias_domain = alias_suffix[1:]
    domain = CustomDomain.get_by(domain=alias_domain)

    ...

# However, we do not have an `else` branch to deal with generated
# custom domain suffixes like `.abcde@mydomain.com`.

try:
    alias = Alias.create(
        user_id=current_user.id,
        email=full_alias,
        note=alias_note,
        mailbox_id=mailboxes[0].id,
        custom_domain_id=custom_domain_id,
    )
    db.session.flush()
except IntegrityError:
    ...
```

**Comment by nguyenkims** [comment]
@ppoffice Hi, I just tested with my domain and it seems to work. This is how to I tested:
- create an alias to_be_deleted@my-domain.com
- delete it on the dashboard
- I can see it on the "deleted alias" page of my-domain.com

**Comment by ppoffice** [comment]
Yes. It works when you don't have the random generated alias suffix. Can you try again with to_be_deleted.random_suffix@my-domain.com?

**Comment by nguyenkims** [comment]
@ppoffice this is indeed a bug, it is fixed now :), thanks very much for reporting it!
