### ISSUE TITLE
Some senders names are removed when forwarded to mailbox

### ISSUE THREAD

**Issue by browntownington** [simple-login/app#548]
Describe the bug
Been using simplemail for 24hrs and noticed this issue. Instead of the sender name being "John Wicks - John(at)wicks.com" some forwarded emails are only come through with "John(at)wicks.com" even when the original mail has a sender name.

Example 1
actual sender name missing: Menulog
simplelogin sender name: noreply(a)menulog.com.au <ra+noreply.at.menulog.com.au+jrpzawcwk@simplelogin.co>

Example 2
actual sender name missing: Guzman y Gomez
simplelogin sender name: hola(a)gyg.com.au <ra+hola.at.gyg.com.au+yovjxrusih@simplelogin.co>

Example 3
actual sender name missing: EnergyAustralia
simplelogin sender name: no-reply(a)news.energyaustraliaonline.com.au <ra+no-reply.at.news.energyaustraliaonline.com.au+xeepgzfm@simplelogin.co>

Example 4
actual sender name missing:  NRMA Member Experience 
simplelogin sender name:  noreply at my-voice.com.au <ra+gveuysotbrycksafwritoatcdrypcltbgcqbrcrbqk@simplelogin.co>

Expected behavior
The sender name should reflect "John Wicks - John(at)wicks.com"

**Comment by nguyenkims** [comment]
@browntownington I have investigated in the log for the case EnergyAustralia and the reason is the contact (aka reverse-alias) is created from the "Reply-To" header instead of the "From" header. The reason is Reply-To header can be different than From header and as the default reply for most email client will use the Reply-To header, SimpleLogin uses it if it's present.

For the EnergyAustralia email, the reply-to header is just `no-reply@news.energyaustraliaonline.com.au` whereas the From header is `EnergyAustralia <no-reply@news.energyaustraliaonline.com.au>`. This is a minor case IMO as setting the Reply-To header is useless here and a good email administrator wouldn't allow this to happen :).

**Comment by browntownington** [comment]
Thank you for investing @nguyenkims

I understand your logic. You are creating the contact off "reply-to" as this is where the return replies will need to be sent. 

But I don't know that I agree with this method. You are telling the mail client that the mail came "From" a different address then it actually did come from.

Correct me if I am wrong, but this is how it currently works:

Mail arrives at SimpleLogin
FROM: "newsletter" noreply@fakedomain.com
Reply-to: "" contactus@fakedomain.com
contact(reverse-alias): <ra+contactus.at.fakedomain.com+xeepgzfm@simplelogin.co>

Mail sent to the client as
FROM: "ra+contactus.at.fakedomain.com+xeepgzfm@simplelogin.co"
To: fakedomain@mydomain.com

I don't want to sound as though I am nit picking - all my feedback and suggestions are trying to be constructive :)

Wouldn't a more true and suitable method be to create a two (reverse-alias) contacts at SimpleLogin when mail arrived with a reply-to address 1)sender from and 2) sender reply-to address.
Then forward the mail to the client from the "From" contact and attach the "reply-to" contact as the reply-to.
The user can now see in their mailbox that the email headers contain a FROM and Reply-to as the original email did.

Example
Mail arrives at SimpleLogin
FROM: "newsletter" noreply@fakedomain.com
Reply-to: "" contactus@fakedomain.com
Create contact(reverse-alias): "" <ra+contactus.at.fakedomain.com+xeepgzfm@simplelogin.co>
Create contact(reverse-alias): "newsletter" <ra+noreply.at.fakedomain.com+xeepgzfm@simplelogin.co>

Send mail to the client
FROM: "newsletter" <ra+noreply.at.fakedomain.com+xeepgzfm@simplelogin.co>
To: fakedomain@mydomain.com
Reply-to: ra+contactus.at.fakedomain.com+xeepgzfm@simplelogin.co

**Comment by nguyenkims** [comment]
@browntownington your suggestion totally makes sense, I don't know why we haven't thought of this earlier ... I'll try  implement this suggestion in the next coming weeks and let you know when it's ready :).

**Comment by browntownington** [comment]
Woohoo thank you @nguyenkims I must say it's really fulfilling as community member/customer to be able to make suggestions and have them attentively accepted :)

**Comment by nguyenkims** [comment]
@browntownington the feature is now deployed :), feel free to test it out. I did some tests and the Reply-To header is now working as you described.
