### ISSUE TITLE
Error when using alias on trello

### ISSUE THREAD

**Issue by havedill** [simple-login/app#55]
I used an alias to sign up for the trello page to see your roadmap.

My server caught an error attempting to forward the email

![image](https://user-images.githubusercontent.com/34009509/73194605-106c0780-40f2-11ea-9be8-5e1c8a05f0d4.png)

**Comment by nguyenkims** [comment]
Replying from an alias can only work from your personal email. This is to make sure only you can send emails from your alias. The error you got means the reply is sent from an empty email (the `actual mail_from` variable).

**Comment by havedill** [comment]
Odd. It was supposed to be a trello "activation" or welcome email. I did not reply to this (nor did i get it due to the exception)

I dug deeper into the sentry errors. I think what happened here was Trello attempted to send me an email, the server for some reason didn't like the alias, and attempted to send an email back saying it was rejected. Then i saw these errors...


Also, is there a way to change my "from" name. I noticed in these debug logs that the from user is "Son at SimpleLogin"

![image](https://user-images.githubusercontent.com/34009509/73198166-3694a600-40f8-11ea-916d-b13eb6d82e12.png)

![image](https://user-images.githubusercontent.com/34009509/73198222-4ca26680-40f8-11ea-938c-21d103bf779d.png)

![image](https://user-images.githubusercontent.com/34009509/73198276-6479ea80-40f8-11ea-9501-9998b100f259.png)

**Comment by nguyenkims** [comment]
> Also, is there a way to change my "from" name. I noticed in these debug logs that the from user is "Son at SimpleLogin"

This is hardcoded in the code (this dated from the time when I was alone on the project :) ), I will add a setting so you could change it.

For the trello issue, I just created an account with my custom domain via SimpleLogin (SaaS version) and received the activation email. I will create a server from scratch tomorrow to test again. Will keep you posted.

**Comment by nguyenkims** [comment]
@havedill this is the PR to set another support name https://github.com/simple-login/app/pull/56

**Comment by nguyenkims** [comment]
@havedill this param is now included in version 1.0.2

**Comment by nguyenkims** [comment]
Just tested with a clean server and everything seems to work fine, I got the activation email from Trello. Could you try again with a clean install please?

**Comment by havedill** [comment]
Just got the same thing on 1.0.3 when signing up on investing.com

![image](https://user-images.githubusercontent.com/34009509/73855026-10a68a00-47f9-11ea-9943-b5671787ca61.png)

**Comment by havedill** [comment]
@nguyenkims  do you have a discord or somewhere i can DM you a share link to my Sentry exception?

**Comment by havedill** [comment]
Postfix logs

```
Feb  5 15:21:10 ip-172-31-16-197 postfix/smtpd[25396]: connect from mta3-20.mail.investing.com[185.168.113.20]
Feb  5 15:21:10 ip-172-31-16-197 postfix/smtpd[25396]: B9F304EE8E: client=mta3-20.mail.investing.com[185.168.113.20]
Feb  5 15:21:10 ip-172-31-16-197 postfix/cleanup[25403]: B9F304EE8E: message-id=<9bab45e3194ae2145dfda07e6b94dfc9@www.investing.com>
Feb  5 15:21:11 ip-172-31-16-197 postfix/qmgr[1328]: B9F304EE8E: from=<register-investing=XXXXXXX.info@forexprosmail.com>, size=21207, nrcpt=1 (queue active)
Feb  5 15:21:11 ip-172-31-16-197 postfix/smtpd[25396]: disconnect from mta3-20.mail.investing.com[185.168.113.20] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
Feb  5 15:21:11 ip-172-31-16-197 postfix/smtpd[25405]: connect from unknown[240.0.0.5]
Feb  5 15:21:12 ip-172-31-16-197 postfix/smtpd[25405]: 013D04EE94: client=unknown[240.0.0.5]
Feb  5 15:21:12 ip-172-31-16-197 postfix/cleanup[25403]: 013D04EE94: message-id=<9bab45e3194ae2145dfda07e6b94dfc9@www.investing.com>
Feb  5 15:21:12 ip-172-31-16-197 postfix/qmgr[1328]: 013D04EE94: from=<reply+akihvjkdhboozabirsysatlbsnqpyv@XXXXXXX.info>, size=21495, nrcpt=1 (queue active)
Feb  5 15:21:12 ip-172-31-16-197 postfix/smtpd[25405]: disconnect from unknown[240.0.0.5] ehlo=1 mail=1 rcpt=1 data=1 commands=4
Feb  5 15:21:12 ip-172-31-16-197 postfix/smtp[25404]: B9F304EE8E: to=<investing@XXXXXXX.info>, relay=127.0.0.1[127.0.0.1]:20381, delay=1.5, delays=0.49/0.03/0/0.97, dsn=2.0.0, status=sent (250 Message accepted for delivery)
Feb  5 15:21:12 ip-172-31-16-197 postfix/qmgr[1328]: B9F304EE8E: removed
Feb  5 15:21:12 ip-172-31-16-197 postfix/smtp[25404]: 013D04EE94: to=<XXXXXXXX@gmail.com>, relay=email-smtp.us-east-1.amazonaws.com[34.193.234.8]:587, delay=0.35, delays=0.01/0.01/0.12/0.21, dsn=5.0.0, status=bounced (host email-smtp.us-east-1.amazonaws.com[34.193.234.8] said: 554 Transaction failed: Duplicate header 'List-Unsubscribe'. (in reply to end of DATA command))
Feb  5 15:21:12 ip-172-31-16-197 postfix/cleanup[25403]: 593574EE96: message-id=<20200205152112.593574EE96@mail.XXXXXXX.info>
Feb  5 15:21:12 ip-172-31-16-197 postfix/qmgr[1328]: 593574EE96: from=<>, size=23701, nrcpt=1 (queue active)
Feb  5 15:21:12 ip-172-31-16-197 postfix/bounce[25408]: 013D04EE94: sender non-delivery notification: 593574EE96
Feb  5 15:21:12 ip-172-31-16-197 postfix/smtpd[25396]: connect from unknown[240.0.0.5]
Feb  5 15:21:12 ip-172-31-16-197 postfix/qmgr[1328]: 013D04EE94: removed
Feb  5 15:21:12 ip-172-31-16-197 postfix/smtpd[25405]: connect from unknown[240.0.0.5]
Feb  5 15:21:12 ip-172-31-16-197 postfix/smtpd[25405]: 772E94EE8E: client=unknown[240.0.0.5]
Feb  5 15:21:12 ip-172-31-16-197 postfix/cleanup[25403]: 772E94EE8E: message-id=<158091607247.1.12017587329527402881@8a433dbb1058>
Feb  5 15:21:12 ip-172-31-16-197 postfix/qmgr[1328]: 772E94EE8E: from=<support@XXXXXXX.info>, size=1860, nrcpt=1 (queue active)
Feb  5 15:21:12 ip-172-31-16-197 postfix/smtpd[25405]: disconnect from unknown[240.0.0.5] ehlo=1 mail=1 rcpt=1 data=1 commands=4
Feb  5 15:21:12 ip-172-31-16-197 postfix/smtpd[25405]: connect from unknown[240.0.0.5]
Feb  5 15:21:12 ip-172-31-16-197 postfix/smtpd[25405]: warning: Illegal address syntax from unknown[240.0.0.5] in RCPT command: <>
Feb  5 15:21:12 ip-172-31-16-197 postfix/smtp[25407]: 593574EE96: to=<reply+akihvjkdhboozabirsysatlbsnqpyv@XXXXXXX.info>, relay=127.0.0.1[127.0.0.1]:20381, delay=0.18, delays=0.01/0/0/0.17, dsn=5.0.0, status=bounced (host 127.0.0.1[127.0.0.1] said: 500 Error: (SMTPRecipientsRefused) {'<>': (501, b'5.1.3 Bad recipient address syntax')} (in reply to end of DATA command))
Feb  5 15:21:12 ip-172-31-16-197 postfix/qmgr[1328]: 593574EE96: removed
Feb  5 15:21:12 ip-172-31-16-197 postfix/smtp[25404]: 772E94EE8E: to=<XXXXXXXX@gmail.com>, relay=email-smtp.us-east-1.amazonaws.com[34.193.234.8]:587, delay=0.47, delays=0.02/0/0.13/0.32, dsn=2.0.0, status=sent (250 Ok 0100017015f0e0ca-8bbdbbbe-b2b8-49fb-92d7-44c21a991542-000000)
Feb  5 15:21:12 ip-172-31-16-197 postfix/qmgr[1328]: 772E94EE8E: removed

```

**Comment by nguyenkims** [comment]
> @nguyenkims do you have a discord or somewhere i can DM you a share link to my Sentry exception?

You can send the link to my email at son@simplelogin.io

**Comment by nguyenkims** [comment]
This issue is not obvious 🤔, I think there are actually 2 problems:
- the mysterious `<>` address: I think this one is due Postfix trying to send the bounce report. Do you know a way to reproduce this error? I have tried signing on investing.com but it requires a phone number that I don't want to give ...
- duplicated `List-Unsubscribe`: this should not happen as SimpleLogin replaces this header by SimpleLogin. This is to avoid users revealing inadvertently their real email address when clicking on this button. Same, if the problem happens again on another website than investing.com, please let me know.

**Comment by havedill** [comment]
Yeah when i sign up with email (it doens't require a phone # btw) i can reproduce it. I can also reproduce it when attempting to resend the activation email.
![image](https://user-images.githubusercontent.com/34009509/73945918-ad7d2c00-48ba-11ea-84d9-9bcc14fc86d4.png)


Maybe it has something to do with my routing through SES. I'll dig in on that side more

**Comment by havedill** [comment]
I feel like this part ofthe code from app/email_utils.py must not be throwing a value error exception, and adding a duplicate Unsubscribe header;

But i'm not sure how to test. Never worked with docker too much. Guess i'll have to see if i can make my own image

```
def add_or_replace_header(msg: Message, header: str, value: str):
    try:
        msg.add_header(header, value)
    except ValueError:
        # the header exists already
        msg.replace_header(header, value)
```

**Comment by havedill** [comment]
Ok i temporarly bypassed this issue by adding an if statement. Since it's for my own personal use i dont really care about the unsubscribe header for simplelogin anyways.

This allowed the email to go through, and maintained the investing.com unsubscribe header

```
def add_or_replace_header(msg: Message, header: str, value: str):
    try:
        if header != "List-Unsubscribe":
            msg.add_header(header, value)
    except ValueError:
        # the header exists already
        msg.replace_header(header, value)

```

**Comment by nguyenkims** [comment]
@havedill I think I found the bug. The implementation of `add_or_replace_header` is indeed incorrect in case a header appears multiple times in the email header. This PR should fix it:

https://github.com/simple-login/app/pull/77

We have tested this PR in staging and everything seems working correctly. Would be great if you could give it a try on your server.

**Comment by havedill** [comment]
Excellent! Is there a 1.0.4 image i can pull or what is the best method for me to pull it into my container?

**Comment by nguyenkims** [comment]
@havedill you can use this image `simplelogin/app-ci:email-header`.

**Comment by havedill** [comment]
@nguyenkims  looks like it is working fine! thanks for the fix :)

**Comment by nguyenkims** [comment]
@havedill the version 1.0.4 is just released, feel free to use it instead of the `simplelogin/app-ci:email-header`. They are essentially the same but the `simplelogin/app-ci:email-header` is reserved for our CI and could change.
