### ISSUE TITLE
Copyright date is wrong

### ISSUE THREAD

**Issue by TheLastProject** [simple-login/app#554]
Still says 2020, just noticed that: https://twitter.com/SylvieLorxu/status/1420822370323943427.

![image](https://user-images.githubusercontent.com/1885159/127551209-07bc7d9d-1e78-4c8f-963d-dfde270fe44b.png)

You should probably just make this grab the current year in code :P

**Comment by nguyenkims** [comment]
@TheLastProject nice catch! Fixed in https://github.com/simple-login/app/commit/383cd49f25533e1eda90979a33fe24c0ba582de8 :)
