### ISSUE TITLE
Cannot change password on account

### ISSUE THREAD

**Issue by CurrentWave** [simple-login/app#568]
As you know when requesting to change the account password there is a one hour limit to do so.

However, I do not receive the email to change password until past the one hour limit  - huge problem/Bug

In fact, this feature of simplelogin is why I almost never use the service even though I have a paid account.  
When signing up for things the simplelogin emails always take hours and even days to come into me, and some sites just time out.

**Comment by nguyenkims** [comment]
Hi can you please send us your account address to our support at hi[at]simplelogin.io so we can investigate?
