### ISSUE TITLE
Can no longer search based on partial domain name in Alias Note field

### ISSUE THREAD

**Issue by aijai9hu** [simple-login/app#571]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**
Previously I was able to search for a partial domain in order to find aliases using that domain from the `Alias Note` field (e.g. `github`). Now I have to type in the full domain (e.g. `github.com`)

**Expected behavior**
Should be able to search for alias note using any portion of text in `Alias Note` field.

**Environment (If applicable):**
 - OS: Linux
 - Browser: Chromium
 - Version: 92.0.4515.131

**Comment by nguyenkims** [comment]
@braderhart recently we have changed to use Postgres full text search (https://www.postgresql.org/docs/current/textsearch.html) which handles better human texts (e.g. can understand "house" even if "housse" is typed). This search engine is more user friendly than the substring search used previously but sometimes ignore substring search like in the case you reported.

**Comment by braderhart** [comment]
@nguyenkims Thank you for the update. Is there any chance of adding an option to search substrings. I can't remember every FQDN used in the `Alias Note` field, and often quickly need to find an alias based on a partial match. I can just used the exportable CSV for now, but having the feature built-in would be nice:

https://stackoverflow.com/questions/30252903/full-text-search-on-substring-in-postgresql

**Comment by nguyenkims** [comment]
@braderhart thanks for the link on `pg_trgm` extension! The substring has now been re-enabled :)
