### ISSUE TITLE
Sending emails via port 587

### ISSUE THREAD

**Issue by z33ma** [simple-login/app#594]
Hosting on Azure & port 25 is blocked so trying to send via 587

I made a change on my .env and added 

`POSTFIX_PORT=587`

on my /etc/postfix/master.cf

`#smtp      inet  n       -       y       -       -       smtpd
587      inet  n       -       n       -       -       smtpd
#smtp      inet  n       -       y       -       1       postscreen
#smtpd     pass  -       -       y       -       -       smtpd
#dnsblog   unix  -       -       y       -       0       dnsblog
#tlsproxy  unix  -       -       y       -       0       tlsproxy
submission inet n       -       y       -       -       smtpd
  -o syslog_name=postfix/submission
  -o smtpd_tls_security_level=encrypt
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_client_restrictions=$mua_client_restrictions
`

on my / var/log/mail/log

`Aug 20 10:18:34 SL postfix/smtp[4423]: connect to alt2.aspmx.l.google.com[74.125.200.26]:25: Connection timed out
Aug 20 10:18:34 SL postfix/smtp[4423]: connect to alt1.aspmx.l.google.com[2a00:1450:4010:c1c::1b]:25: Network is unreachable
Aug 20 10:18:49 SL postfix/smtp[4434]: connect to alt2.aspmx.l.google.com[74.125.200.26]:25: Connection timed out
Aug 20 10:18:49 SL postfix/smtp[4434]: connect to alt2.aspmx.l.google.com[2404:6800:4003:c00::1b]:25: Network is unreachable
Aug 20 10:18:49 SL postfix/smtp[4434]: connect to alt1.aspmx.l.google.com[2a00:1450:4010:c1c::1b]:25: Network is unreachable`

is there another setting I need to change?

**Comment by nguyenkims** [comment]
To use 587 as port, you need to enable `POSTFIX_SUBMISSION_TLS` too as it will use TLS when connecting to Postfix server.

**Comment by z33ma** [comment]
Hi,  thank you, would that be in the .env file?

**Comment by nguyenkims** [comment]
Yes you can put `POSTFIX_SUBMISSION_TLS=1` in your `.env` file.

**Comment by z33ma** [comment]
Perfect thank you so much, I’ll have test now.

**Comment by z33ma** [comment]
so give that ago, seems postfix wants to use port 25, I swear I'm overlooking something somewhere

mail.log
`Aug 21 16:55:30 SL postfix/smtp[2927]: connect to alt2.aspmx.l.google.com[74.125.200.26]:25: Connection timed out
Aug 21 16:55:30 SL postfix/smtp[2927]: connect to alt1.aspmx.l.google.com[2a00:1450:4010:c1c::1a]:25: Network is unreachable
Aug 21 16:55:57 SL postfix/smtp[2935]: connect to aspmx.l.google.com[142.250.145.26]:25: Connection timed out
Aug 21 16:55:57 SL postfix/smtp[2935]: connect to aspmx.l.google.com[2a00:1450:4013:c01::1b]:25: Network is unreachable
Aug 21 16:56:00 SL postfix/smtp[2927]: connect to alt1.aspmx.l.google.com[142.250.150.26]:25: Connection timed out
`

simplelogin.env

`POSTFIX_PORT=587

POSTFIX_SUBMISSION_TLS=true

LOCAL_FILE_UPLOAD=1
`

master.cf

`smtp      inet  n       -       y       -       -       smtpd
#587      inet  n       -       n       -       -       smtpd
#smtp      inet  n       -       y       -       1       postscreen
#smtpd     pass  -       -       y       -       -       smtpd
#dnsblog   unix  -       -       y       -       0       dnsblog
#tlsproxy  unix  -       -       y       -       0       tlsproxy
submission inet n       -       y       -       -       smtpd
  -o syslog_name=postfix/submission
  -o smtpd_tls_security_level=encrypt
  -o smtpd_sasl_auth_enable=yes
#  -o smtpd_reject_unlisted_recipient=no
  -o smtpd_client_restrictions=$mua_client_restrictions
`

**Comment by z33ma** [comment]
Decided to relay through SendGrid, Azure were dragging their feet to open port 25, 

all working correctly now
