### ISSUE TITLE
Connect from iOS app to self hosted

### ISSUE THREAD

**Issue by z33ma** [simple-login/app#596]
Hi, 

I have my application hosted on https://app.domain.com

but when I enter that URL in the iOS app, I get Unknown Error: Couldn't Connect to server, does the app connect on a specific port?

**Comment by prashantkamdar** [comment]
No. I have it setup exactly this way and I am able to connect to my app.domain.com from iOS without any issues.

**Comment by Rustymage** [comment]
I have this issue, I found using the API key helped.
