### ISSUE TITLE
Add an option to make it harder to delete an alias

### ISSUE THREAD

**Issue by MrSoke** [simple-login/app#613]
Deleting an alias right now is pretty easy, which is fine for stuff that's not too important, but when it comes to aliases that you use for more important things, it's a little too easy to delete. I could definitely see it happen by mistake, specially in the android app, and that's very problematic knowing there doesn't seem to be a way to recover a deleted alias. So, I think it would be great to have the option to protect specific aliases against deletion, that way you would have to go and manually disable the protection before actually deleting the alias. Another alternative solution would be adding a trash bin, send deleted aliases there and keep them for a few days or hours before completely deleting them, but I personally think the delete protection would be a better solution.

By the way, I'm loving SimpleLogin so far, thanks for all the hard work!

**Comment by nguyenkims** [comment]
@MrSoke thanks for the feedback!

@ntnhon I think it might make sense to add a confirmation before a user can delete an alias and make the deletion button less visible :).

**Comment by ntnhon** [comment]
Hello, the app does ask you for confirmation before deleting an alias, this has been the behavior since the very first version. Am I missing something?
![Screenshot_2021-09-10-19-00-42-186_io simplelogin android fdroid](https://user-images.githubusercontent.com/4153453/132890781-ad6671f8-84a6-46db-af8f-9a2224511ee3.jpg)

**Comment by MrSoke** [comment]
Hi! Yes, it already asks for confirmation, that's good enough for most things, but I think it's not secure enough for certain sensitive aliases, trying to save your phone from a drop is enough to make more than a few accidental taps, and having the option to just lock down the ability delete specific aliases would solve that problem. With that I don't mean making it a default behavior, but rather an option you activate for specific aliases you choose

**Comment by ntnhon** [comment]
I think we can add a check box to this dialog. The user has to check it before enabling the delete button. Although I personally don't delete aliases that often so such extra tiny effort doesn't bother me but I'm not sure if the majority of the user would appreciate that.

**Comment by MrMuffinIsTaken** [comment]
@ntnhon i would sure appreciate it.

**Comment by RupertEverton** [comment]
I would also find very useful to have protection against deletion. This could be as simple as requiring the password to press "delete".
You could add a global setting that users can choose to enable/disable, for those that do not require such additional protection.
