### ISSUE TITLE
Concise view 

### ISSUE THREAD

**Issue by bassplay3r** [simple-login/app#632]
Please note that this is only for bug report. 

For help on your account, please reach out to us at hi[at]simplelogin.io. Please make sure to check out [our FAQ](https://simplelogin.io/faq/) that contains  frequently asked questions.

For feature request, you can use our [forum](https://github.com/simple-login/app/discussions/categories/feature-request). 

For self-hosted question/issue, please ask in [self-hosted forum](https://github.com/simple-login/app/discussions/categories/self-hosting-question)

## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**

**Expected behavior**

**Screenshots**

**Environment (If applicable):**
 - OS: Linux, Mac, Windows
 - Browser: Firefox, Chrome, Brave, Safari
 - Version [e.g. 78]

**Additional context**

**Comment by nguyenkims** [comment]
@bassplay3r I close this issue as there's already this feature request https://github.com/simple-login/app/discussions/520
