### ISSUE TITLE
Very odd issue with daily admin emails?!

### ISSUE THREAD

**Issue by dohlin** [simple-login/app#64]
Hey guys,

Not a critical priority thing here, but I am noticing what seems to be a very odd issue and I'm not sure if it's something I did wrong or can fix or what.

So initially when setting this up to try it out, I configured postfix to send outbound email via my Gmail SMTP relay, as historically this has worked well for me for other self hosted services.

While this worked, the problem became evident when I tried to send (outbound) via one of my created aliases.  Because I'm claiming to send from 'abc@mydomain.com' via my actualgmailemail@gmail.com, Gmail sees this and doesn't like the spoofing and consequently puts a big yellow warning message saying "Be careful with this message.  This may be a spoofed message.  The message claims to have been sent from your account, but Gmail couldn't verify the actual source...".

So, I ended up reconfiguring the Postfix main config file SMTP settings so that outbound mail would be sent via a sendinblue SMTP account instead.  And like that, outbound emails from any of my aliases actually looked as though then were from that address.  So problem solved!

Until.....I now have noticed that every daily admin email sent out to my Gmail address is also showing that same exact 'possible spoof warning' notification.  So it's almost as though my initial setup with Postfix SMTP relay via Gmail is still being remembered somehow by whatever process or whatever trigger the daily admin email.  Am I crazy here?  What could I be missing and/or what steps would you recommend following to try to get more details on this and/or steps to try to fix?  Thank you!

**Comment by nguyenkims** [comment]
I think the warning comes from your domain SPF record. The SPF in the self-instructions is set to `v=spf1 mx -all` which means only your server could send emails for your domains, all other servers (Gmail, SendInBlue) are not authorized to send emails from your domain.

If you want to use an external SMTP server, I think you need to add these SMTP server to your SPF record.

**Comment by dohlin** [comment]
Good to know.  Thanks!
