### ISSUE TITLE
Alias description says "Created by catch-all option"

### ISSUE THREAD

**Issue by rowatt** [simple-login/app#649]
I noticed recently that new aliases created by the catchall option now have the description "Created by catch-all option" added automatically. Is it/would it be possible to have an option to turn this off? While I can see that this might be useful for some people, it's just noise for me (almost all my aliases are first created by the catch-all) and it makes it harder to quickly see notes that I do leave in the description.

**Comment by nguyenkims** [comment]
@rowatt Do you think having a new field, something like `automatic_note` to store how an alias is created (can be either via catch-all, directory) can be helpful?  This field is only shown up when clicking on "more" to not create noise with the current  `note`.
