### ISSUE TITLE
Reverse alias with name display not working with ProtonMail

### ISSUE THREAD

**Issue by petaglair** [simple-login/app#656]
Reverse alias w/o display name seems to work fine though. Getting the reverse alias from simple login app for iOS and pasting it in ProtonMail app for iOS. "With display name reversed alias" returns an error message in ProtonMail app such as "recipient email format is not correct/ unsupported" and it doesn't proceed. I haven't run any extensive test (with android apps or web apps) so far. As I said w/o display name returned no issue in ProtonMail app for iOS. Thanks

**Comment by ntnhon** [comment]
Hello, this is why the option "w/o display name" exists. Because some email clients don't accept email addresses with display name. That's just something we need to live with unfortunately.

**Comment by netcarver** [comment]
Does this option exist in the web app as well? Not seeing it.

**Comment by nguyenkims** [comment]
This option doesn't exist on the web app as it seems that most web email client supports email addresses with the display name part.
