### ISSUE TITLE
Tracker prevention

### ISSUE THREAD

**Issue by fredster33** [simple-login/app#682]
It would be nice if SimpleLogin could have a tracker prevention option to remove trackers from emails, similar to duck.com's email system.

**Comment by TaxingAuthority** [comment]
I came here to post this feature request and want to add another plug with this comment.

I got myself a duck.com email, but am unsure the best way to integrate it within my current email alias structure. What would be convenient is for SimpleLogin to release a similar feature for us to enable for aliases.

**Comment by nguyenkims** [comment]
We have a feature request for this feature at https://github.com/simple-login/app/discussions/542
