### ISSUE TITLE
Pagination buttons displayed when exactly at PAGE_LIMIT

### ISSUE THREAD

**Issue by timotree** [simple-login/app#691]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**
The pagination buttons on the dashboard are displayed when your alias count is exactly at the PAGE_LIMIT, which defaults to 20 items. Specifically, the "Next" button is enabled, which brings you to a blank page because there are no additional items to show.

**Expected behavior**
The buttons are hidden up to PAGE_LIMIT - 1 but should remain hidden until the count is > PAGE_LIMIT.

**Environment (If applicable):**
 - OS: Windows
 - Browser: Chrome
 - Version: 96.0.4664.45

**Additional context**
I believe this should be fixed in in dashboard/views/index.py:166, where the check should be for less than or equal to, rather than just less than: `last_page = len(alias_infos) <= PAGE_LIMIT`

**Comment by nguyenkims** [comment]
@timotree thanks for reporting this issue, it should be fixed now :)

**Comment by timotree** [comment]
Confirmed that it's fixed! Thank you!
