### ISSUE TITLE
Incorrect quota displayed in the "Delete Subdomain" section

### ISSUE THREAD

**Issue by douchesfeedboard** [simple-login/app#694]
## Prerequisites
- [X] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**
This is about the new "Subdomains" feature.
When going into the details of a subdomain, the quota displayed into the "Delete Subdomain" section is incorrect.
The number is lower than the actual quota by a value of one. Instead, it should be **higher** than the actual quota by a value of one because the sentence is "After deletion, your subdomain quota will be".
See screenshots for better understanding.

**Expected behavior**
Displaying the correct quota value in the "Delete Subdomain"

**Screenshots**
After creating two subdomains, the quota is 3
![new subdomain](https://user-images.githubusercontent.com/82176340/142701974-d4117764-3386-4828-ad85-580c8d6ef0af.JPG)
Then if we go into the details of one subdomain, the "Delete Subdomain" section should display "After deletion, your subdomain quota will be 4", not 2.
![delete subdomain](https://user-images.githubusercontent.com/82176340/142702010-fb98e23e-274b-411f-8a46-a2ca32b6e6ed.JPG)

**Comment by nguyenkims** [comment]
As subdomain is a shared resource and a deleted subdomain can't be recycled, an addition or deletion of a subdomain both counts for the subdomain quota. What you see on the dashboard is actually accurate :).

**Comment by douchesfeedboard** [comment]
I see what you mean but then I still disagree it's accurate :)

I actually have a remaining quota displayed of 3 in the dashboard because I have created two subdomains. This is accurate.
According what you're saying, if I delete one of them, my quota should not be restored. Ok, but then my quota should also not change, just staying the same.

I can create 3 remaining subdomains, I delete 1 and now I can only create 2 after deletion? Makes no sense. Active or not, this deleted subdomain still consume the same value of the quota, the deletion should not consume **more**.

By the way, I did the test yesterday. After deleting one domain, the quota was **restored** by a value of one (went from 3 to 4 in the dashboard). So your statement is also not what I see in reality. Maybe there is something to fix on this too.

I also think you should really advertise than a subdomain cannot be recycled **even** by the account who created it the first time.

And after fixing the display value (because something is really wrong there), to also advertise deleting a subdomain will **not** restore the quota. I didn't see any warning about this.

Because according what you're saying, if you create five subdomain, you're stuck forever. Even if you delete them, you cannot create any subdomain anymore because it will not restore the quota.

**Comment by nguyenkims** [comment]
> According what you're saying, if I delete one of them, my quota should not be restored. Ok, but then my quota should also not change, just staying the same.

This is indeed a bug, it has been fixed now :), thanks for reporting it!

> I also think you should really advertise than a subdomain cannot be recycled even by the account who created it the first time.


We have also made the message more clear when user is about to delete a subdomain so they know that it won't restore the quota.

> By the way, I did the test yesterday. After deleting one domain, the quota was restored by a value of one (went from 3 to 4 in the dashboard). So your statement is also not what I see in reality. Maybe there is something to fix on this too.


This should be fixed as well :)

> Because according what you're saying, if you create five subdomain, you're stuck forever. Even if you delete them, you cannot create any subdomain anymore because it will not restore the quota.

Yes unfortunately that's the case. We also recommend to not delete a subdomain but disable the catch-all instead if needed.
