### ISSUE TITLE
Custom domains not counting aliases correctly

### ISSUE THREAD

**Issue by purple-emily** [simple-login/app#695]
When opening domains page it says:

```
<domain>
created <x> days ago
<n> aliases
```

![6D7DEF5A-84C9-490E-80AE-20635E76942F](https://user-images.githubusercontent.com/93710772/142741909-6fa676ee-f640-4b87-a041-0a8419998079.jpeg)

The number of aliases is not correct, and this has a few indirect issues.

As you can see, I actually have 44 aliases using this domain name:

![29E53DF4-E1C1-45B8-B90E-E06EEF721E89](https://user-images.githubusercontent.com/93710772/142741947-5f4d3b55-cf28-48b3-a9d4-d93e5dfae6c3.jpeg)

Now this has at least one side effect:
On your domain name, you are able to set a default display name. Now when you create an alias using "create custom alias" it doesn't count to the total number of aliases, and is not receiving the default display name, and thus has a blank display name.  

![308F1F64-3DE7-4CD4-B2FD-1252D847E147](https://user-images.githubusercontent.com/93710772/142742119-6d8726e8-76f0-43de-9854-1c7f8bc6a4f5.png)

![6E60CD2C-77F4-4854-87DA-AA2F5118E23D](https://user-images.githubusercontent.com/93710772/142742046-69ad9514-0e2d-44f5-8e8f-ef82cadbd140.jpeg)

Meaning I have to type the same display name 44 times. A minor annoyance.

**Comment by nguyenkims** [comment]
> Meaning I have to type the same display name 44 times. A minor annoyance.

Hey the custom domain display name is used unless overwritten by the alias display name. So when a new alias is created, its display name isn't set and in this case, the custom domain display name will be used. I agree that it would maybe make more sense to prefill the alias display name by the custom domain display name instead but it's a bit too late to change that now as we need to find out a way to migrate existing aliases ...

About the custom domain counter, I just tested to create a new alias with my custom domain and the counter display does increase by 1. Do you know how to reproduce this issue?

**Comment by purple-emily** [comment]
@nguyenkims I can totally reproduce what I mean, and hopefully explain it in more detail. Let me begin:

For my first screenshot, I would like you to observe my dashboard.

![1](https://user-images.githubusercontent.com/93710772/142849087-674960fd-8fae-4226-8f47-51c208f3ddeb.png)

I have `45 aliases`.

![2](https://user-images.githubusercontent.com/93710772/142849142-a55c2650-bf03-429e-bb4f-e85c99d062ee.png)

My domain apparently has `3 aliases`. Let's create a new _Custom Alias_

![3](https://user-images.githubusercontent.com/93710772/142849295-374ad544-4451-4a06-8ebc-7b25b0c7acc9.png)
![4](https://user-images.githubusercontent.com/93710772/142849360-a07d42fa-2bd0-4902-8dbb-4a6e272e33de.png)

As you can see, the alias is created and has a default `Display Name` of _Emily_ as per my previous pictures from my phone, this is the expected outcome, because I configured it this way under my `Domains` settings

![5](https://user-images.githubusercontent.com/93710772/142849511-2240e0cd-bc20-4ccb-9768-9553d993623a.png)

And, as expected, the number of aliases I have created has increased from 3 to 4. Now, if we instead create the alias through the firefox extension (or possibly the iOS app -- I would need to double check this)

![6](https://user-images.githubusercontent.com/93710772/142849554-ba15a9b5-fe64-446c-9453-78040fa63226.png)
![7](https://user-images.githubusercontent.com/93710772/142849696-193a28e1-15b3-47e2-8d70-56c9463fd97a.png)
![8](https://user-images.githubusercontent.com/93710772/142849705-1bdc5d8c-cd9d-408c-bec9-8525c2534273.png)

The display name does not receive the standard default from my settings, and the counter for aliases is not increased. I beleive, this is a problem with the way the app works, and not the extension, but it may be that I am wrong and this issue needs to be migrated to the repo for the extension. This is totally reproducible on every alias created through anything other than the web app. I would expect the `From Name` box to auto populate the display name set on the app, but the counter should still increase no?

If you need any more details, please let me know.

**Comment by nguyenkims** [comment]
@purple-emily thanks for the investigation! This is indeed a bug in the API that is used by all SimpleLogin clients (mobile app, browser extension) but not by the web app. It has been fixed now, please let me know if you still see it :).
