### ISSUE TITLE
Domain auto-create regex does not match expected results achieved through regex101

### ISSUE THREAD

**Issue by argarner** [simple-login/app#715]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**
url route = https://app.simplelogin.io/dashboard/domains/:id/auto-create#debug-zone

The current regex implementation does not match the results of regex101. There's either a bug, or documentation should be uplifted to clarify the current implementation specifics.

**Expected behavior**
Given the example shown below, and the string "-ruleTrigger" is used to create a rule, users would expect any combination of email address including the "-ruleTrigger" string to trigger the given rule.

<img width="845" alt="image" src="https://user-images.githubusercontent.com/11073597/144161354-620c9f50-795d-4c53-9423-c3f5b8187371.png">

**In my testing, the actual implementation of regex in simplelogin failed to trigger all 12 of the examples given, until I updated the regex to account for 4 separate OR clauses to my rule** "-ruleTrigger|.+-ruleTrigger|-ruleTrigger.+|.+-ruleTrigger.+"

**Environment (If applicable):**
- I do not believe this is related to the client, as the page appears to be running all rule tests on the server.

**Additional context**
The page should expand on the following advice "Only the local part of the alias (i.e. @domain.tld is ignored) during the regex test. ", to clarify that the entire "@domain.tld" should be removed for all testing purposes.

It might be a good idea to uplift the playground to generate some common examples from the set regexes, to give visual feedback to the user around how their specific rules would work... e.g. create list of common email strings from each regex in a single table, then show which specific rule would have been triggered, if all current rules were enforced (in their current order) for the given input email.

**Comment by nguyenkims** [comment]
@argarner the regex must **fully** match the local part of the alias. 

For example `-ruleTrigger` won't fully match `xyz-ruleTrigger` but `.*-ruleTrigger` will. 

> it might be a good idea to uplift the playground to generate some common examples from the set regexes, to give visual feedback to the user around how their specific rules would work

We will create a new doc to explain how this feature works along with some practical examples that should cover most use cases.

**Comment by argarner** [comment]
Thanks for the quick response and clarification @nguyenkims. My problem was being a newb at regex and using `.+-ruleTrigger.+`, instead of `.*-ruleTrigger.*`, which would have covered all of my intended use cases. Though, I did not know the regex must be a _complete_ match on the alias/"local-part", as the rule page doesn't state anything about partial or complete matches. Feel free to close this now or whenever the rule page documentation is updated. Cheers!

**Comment by nguyenkims** [comment]
@argarner this is indeed a good idea, we'll add the `fully match` mention in this page :)
