### ISSUE TITLE
dkim for subdomain using Custom Domain

### ISSUE THREAD

**Issue by paulinsche** [simple-login/app#722]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**
* I have setup a domain using https://app.simplelogin.io/dashboard/custom_domain. The domain is **sub.main.tld**.
* I setup dkim as seen on https://app.simplelogin.io/dashboard/domains/_x_/dns. There: „If you are using a subdomain, e.g. subdomain.domain.com, you need to use dkim._domainkey.subdomain as domain value instead.“
* Wenn sending mails, from the subdomain **sub.main.tld** the Mail are signed, but not as from **sub.main.tld**, Instead form **main.tld**.

Example:

> DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=main.tld; s=dkim; t=number;

dkim authentication fails with dkim=none ("invalid DKIM record") header.d=main.tld header.s=dkim header.b=xxxxxxxx;

**Expected behavior**

simplelogin.io should producee valid dkim-signatures, I see at least two possible solutions.

1. Use other domain and sign with **d=sub.main.tld; s=dkim;**
2. Use other selector and sign with **d=main.tld; s=simpleloginio;**

**Workaround**

If the selector dkim is free, use dkim._domainkey.main.tld. instead of dkim._domainkey.sub.main.tld as CNAME.

**Comment by nguyenkims** [comment]
@paulinsche this is indeed a bug, thanks for reporting it! It should be fixed now :)
