### ISSUE TITLE
Response Alias does not hide my personal email

### ISSUE THREAD

**Issue by athiosh** [simple-login/app#733]
Hi, 

Just deployed simplelogin in my home server, everything works great as per instruction. Since my ISP block port 25, I am using my gmail to relay my mail, I am able to receive, forward and reply to my mails. The only issue is when i reply to the email sent to my alias, my relay email address will be visible. I am not sure if the issue is my relay configuration or in my main.cf, below are my configuration. Is there anyway i can fix this so that i can reply with the alias?

**main.cf configuration**
<img width="620" alt="Screen Shot 2021-12-27 at 11 15 42 PM" src="https://user-images.githubusercontent.com/66545547/147527404-eb6be2fd-e466-4aef-ab39-6c97947df5c9.png">
<img width="606" alt="Screen Shot 2021-12-27 at 11 15 49 PM" src="https://user-images.githubusercontent.com/66545547/147527406-e15db902-ec7d-4f98-9bbf-15c0f85dd2c9.png">

**relay_passwd config**
`[smtp.gmail.com]:587 [USER]@gmail.com:PASSWORD`

**Comment by nguyenkims** [comment]
> my relay email address will be visible

Do you mean in this case the contact can see your Gmail address in the response? Does it appear in the email content? The email relay is contributed by another user as a workaround and we don't fully support this relay method.

**Comment by athiosh** [comment]
The sender will be shown as the alias but when click onto that alias, it will show the gmail address underneath. Is there another way where i don't have to relay on gmail but still get around my ISP blocking port 25 outbound?

**Comment by nguyenkims** [comment]
Unfortunately we don't know of any workaround. There are actually some cloud services that are quite good and don't block port 25. We are using UpCloud and are quite happy with their service.

**Comment by athiosh** [comment]
Thank you, I was able to use SMTP2GO as my relay server. The reverse alias is working now. Great app, loving it so far.
