### ISSUE TITLE
When I click "create a totally random alias" <websitename>@<mydomain> gets generated 

### ISSUE THREAD

**Issue by atropos112** [simple-login/app#734]
Hello,

I am a paid customer and I must admit I really like the way this app works, great job. I do have one problem that I cannot deal with and at this point I believe it is a bug. 

When I go to a website, say simplelogin.io, and try to register i press the button (that is there because of the simple login firefox addon) it generates `simplelogin@mydomain` which I don't think it should as in my dashboard setting I have explicitly selected to generate alias "Based on random word" with appropriate domain.

As such I actually expect it to generate `randomWords@mydomain` and not the already mentioned email. In fact even if I click on the extensions icon and press "OR create a totally random alias" it STILL generates `websitename@mydomain` rather than a random alias. 

I've seen #471 and I understand that some people would like to have it work this way but I strongly disagree as it reduces security for no good reason. And the settings clearly don't agree with the actual functionality so I am guessing its a bug.

EDIT:
I found 
```
Random Prefix Generation
Add a random prefix for this domain when creating a new alias. 
```
within domain settings which I think alleviates my security concerns, the above is still a bug nevertheless.

**Comment by nguyenkims** [comment]
> "Based on random word" with appropriate domain.

This setting doesn't indeed apply for the *one-click* alias creation within the browser extension. Currently this one-click alias is created based on the domain name which help people to remember where the alias was created and there's no option to customise it. I'd recommend to create a feature request on https://github.com/simple-login/app/discussions to add a way to customise the one-click alias.

**Comment by atropos112** [comment]
I must be miss-understanding something, the one-click button thats literally stating 
![image](https://user-images.githubusercontent.com/33070637/147919661-7e923f85-a468-4081-9861-24521d32e839.png)
does not actually generate a (pseudo)-random alias, why is the word random even there surely this is misleading.

**Comment by nguyenkims** [comment]
The wording can indeed be improved. Both the icon, the right click menu and the button in the extension creates a random alias **based on the current website user is on**. A workaround while waiting for a new option to disable this behavior is to use UUID alias: a UUID alias will be created which doesn't base on the current website.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/3167780/147956811-16e14d80-6d20-4fc9-84c7-a0a84f535d8c.png">

**Comment by atropos112** [comment]
Okay, thank you. I think having `Random Prefix Generation` enabled within domain settings is a workaround I am happy to accept, just thought it was weird for the extension to give two possibilities but actually did the same thing either way.
