### ISSUE TITLE
Can't send confirmation email

### ISSUE THREAD

**Issue by LeonardoMantovani** [simple-login/app#735]
## Prerequisites
- [X] I have searched open and closed issues to make sure that the bug has not yet been reported.
*(I mean, I know there are a ton of issues with the same title, but none of them fits my case)*

## Bug report

**Describe the bug**
I set up Simplelogin and Postfix as described in the README, then I accessed the web app from `http://app.mydomain.com:81` (I set up NGINX to work on port 81) and registered a new user, but I didn't receive the confirmation email.

**Expected behavior**
Receiving the confirmation email to complete registration and start using SimpleLogin

## Additional context
Before opening a new issue, I looked at troubleshooting guide and checked if postfix installation was working, so I tried `swaks --to me@myemail.com` and it gave me the following error: 
```
<** 554 mxdhfe15.ad.aruba.it bizsmtp 46NznCdkqGBZC IP 151.61.169.108 reverse non valido / Your IP 151.61.169.108 has no valid reverse DNS (PTR)
```
Then, I tried with another email I have (even though it's not the one I wanted to use for simplelogin) and the output of `swaks --to myotheremail@protonmail.com` was this:
```
504 5.5.2 <pi@raspberrypi>: Sender address rejected: need fully-qualified address
```
But this was weird because I should be sending email from a `@mydomain.com` address and not from that `pi@raspberrypi`.
So I tried using `swaks --to myotheremail@protonmail.com --from pi@mydomain.com` and it worked properly.

After all these tests, I assume that my postfix server is working properly, and so there is a problem with simplelogin app.
I tried `telnet 240.0.0.1 25` as the troubleshooting guide suggests and what I get is:
```
Trying 240.0.0.1...
Connected to 240.0.0.1.
Escape character is '^]'.
220 app.lezmail.ml ESMTP Postfix (Ubuntu)
```
*(and then it waited for an input)* so I assumed it was working properly too.

I also tried to send an email from simplelogin (as suggested [here](https://github.com/simple-login/app/issues/319#issuecomment-725962022), even though it wasn't my same problem) and the output of the send_email command (to my _protonmail_ email) was:
```
2022-01-02 19:48:10,799 - SL - DEBUG - "/code/app/email_utils.py:250" - send_email() -  - send email to leonardo.mantovani@protonmail.com, subject Test Subject
2022-01-02 19:48:20,898 - SL - DEBUG - "/code/app/email_utils.py:262" - send_email() -  - Use plaintext as html
---------------------------------------------------------------------------
SMTPRecipientsRefused                     Traceback (most recent call last)
/code/shell.py in <module>
      2     "leonardo.mantovani@protonmail.com",
      3     "Test Subject",
----> 4     "Test Body"
      5 )

/code/app/email_utils.py in send_email(to_email, subject, plaintext, html, unsubscribe_link, unsubscribe_via_email)
    292
    293     # use a different envelope sender for each transactional email (aka VERP)
--> 294     smtp.sendmail(TRANSACTIONAL_BOUNCE_EMAIL.format(transaction.id), to_email, msg_raw)
    295
    296

/usr/local/lib/python3.7/smtplib.py in sendmail(self, from_addr, to_addrs, msg, mail_options, rcpt_options)
    879             # the server refused all our recipients
    880             self._rset()
--> 881             raise SMTPRecipientsRefused(senderrs)
    882         (code, resp) = self.data(msg)
    883         if code != 250:

SMTPRecipientsRefused: {'leonardo.mantovani@protonmail.com': (450, b'4.1.2 <leonardo.mantovani@protonmail.com>: Recipient address rejected: Domain not found')}
```

**Comment by nguyenkims** [comment]
> <** 554 mxdhfe15.ad.aruba.it bizsmtp 46NznCdkqGBZC IP 151.61.169.108 reverse non valido / Your IP 151.61.169.108 has no valid reverse DNS (PTR)

To solve this warning, you can set the reverse DNS of your server to your hostname (`app.lezmail.ml`). Some email services only accept emails sent from hosts with reverse DNS set up.

> SMTPRecipientsRefused: {'leonardo.mantovani@protonmail.com': (450, b'4.1.2 <leonardo.mantovani@protonmail.com>: Recipient address rejected: Domain not found')}

Do you have `240.0.0.0/24` when running `postconf -d mynetworks` on the host (i.e. not inside a docker container)? This error can also happen when Postfix can't connect to the Postgres database, I'd suggest to double check the `/etc/postfix/pgsql-relay-domains.cf` and `/etc/postfix/pgsql-transport-maps.cf` files.

**Comment by LeonardoMantovani** [comment]
Ok so I can't set a PTR record on my domain probably because I'm using a dynamic DNS service, so I'll stick with the protonmail address to receive emails from _simplelogin_ 😔...

I checked with `postconf -d mynetworks` outside of docker containers and I have the `240.0.0.0/24` network.
So I looked at the 2 configuration files you mentioned but I don't know if they are ok or if I need to change something (I'll attach them below)

![image](https://user-images.githubusercontent.com/36340959/147943735-a6c27902-c909-40e5-a7ad-f4180f06ba32.jpeg)

![image](https://user-images.githubusercontent.com/36340959/147943740-3e4ca0f7-bcc3-4e1e-b068-0998510b41ae.jpeg)

**Comment by nguyenkims** [comment]
In the troubleshooting doc at https://github.com/simple-login/app/blob/cbcae31288ff68c036e052fb8d04255a6e276ba5/docs/troubleshooting.md#L45-L44, there's a section to test if these postfix files are working correctly, can you try the commands in this doc?

**Comment by LeonardoMantovani** [comment]
If you mean the [B1 section,](https://github.com/simple-login/app/blob/cbcae31288ff68c036e052fb8d04255a6e276ba5/docs/troubleshooting.md#b1) I tried the 4 `postmap -q` command, and they all return what they should (`mydomain.com`, nothing, `smtp:127.0.0.1:20381`, nothing)...
So I deduce that the 2 config files are correct?

**Comment by nguyenkims** [comment]
Yes that means the 2 config files are correct. I can only think of an issue with the DNS server then but this error is quite rare and can only happen if you handle *a lot* of emails. Is the error "Domain not found" persistent or random?

**Comment by LeonardoMantovani** [comment]
It was persistent when I submitted the issue, but now it's random.
Luckily I was able to receive the confirmation email, but then I still don't receive other emails sent to my alias.
At this point I would guess it could be a problem of my hardware (Raspberry Pi 3) that isn't enough powerful to have SimpleLogin work properly (?)

**Comment by nguyenkims** [comment]
There can be a memory issue if you have less than 1GB of memory. You can check it with commands like `htop` or `docker stats`. The randomness can be a DNS issue indeed, I'd suggest to use a DNS server in this case, you can use CloudFlare or Bind9 one, for example https://developers.cloudflare.com/1.1.1.1/setup-1.1.1.1/linux#debian
