### ISSUE TITLE
A few small corrections to the self-hosting instructions

### ISSUE THREAD

**Issue by mrbluecoat** [simple-login/app#749]
Amazing project - love it! Thanks for not only providing a self-hosting option, but also the detailed instructions - they worked like a charm other than these small fixes:

- https://github.com/simple-login/app/blob/master/README.md?plain=1#L409 needs the `sl` folder to be in the root directory so I recommend adding `cd \` before https://github.com/simple-login/app/blob/master/README.md?plain=1#L60
- Similar to the item above, https://github.com/simple-login/app/blob/master/README.md?plain=1#L402 needs the `dkim.key` file to be in the root directory so the recommendation above would work for that as well or you can add `cd \` before https://github.com/simple-login/app/blob/master/README.md?plain=1#L77
- For my install on Ubuntu 20, I needed to change https://github.com/simple-login/app/blob/master/README.md?plain=1#L375 to `/simplelogin.env` for it to work since `~` pointed to `/root`
- Your certbot link at https://github.com/simple-login/app/blob/master/README.md?plain=1#L518 no longer works. Here's what I ran on Ubuntu 20:

```
sudo apt install -y snapd
sudo snap install core; sudo snap refresh core
sudo apt remove -y certbot
sudo snap install --classic certbot
sudo ln -s /snap/bin/certbot /usr/bin/certbot
sudo certbot --nginx
```

- For postgres newbies, here's how to make the edit described on https://github.com/simple-login/app/blob/master/README.md?plain=1#L525

```
docker exec -it sl-db psql -U myuser simplelogin
UPDATE users SET lifetime = TRUE WHERE id = 1;
exit
```

- After you create your desired account(s), it's important to add these lines to `simplelogin.env` so random Internet surfers don't register and use your private local installation:

```
DISABLE_REGISTRATION=1
DISABLE_ONBOARDING=true
```

Is there a better way than restarting the server to apply those settings?

**Comment by nguyenkims** [comment]
@mrbluecoat thanks for the feedbacks! Do you think you can create a PR to address these fixes in the doc? 

About Certbot, it's maybe better to link to their website instead of having the instructions here as their instructions aren't the same for different OS.

> Is there a better way than restarting the server to apply those settings?

Currently the only way to apply changes is to restart the containers indeed. The restart should be harmless though as if an email is in processing, Postfix will just retry again.

**Comment by mrbluecoat** [comment]
@nguyenkims , all set. Feel free to accept or alter if desired.

**Comment by mrbluecoat** [comment]
p.s. is SimpleLogin no longer accepting Patreon donations? The Patreon link in the ReadMe goes to a page that says `This patron isn’t supporting any creators at the moment.`

**Comment by nguyenkims** [comment]
@mrbluecoat we have replaced Patreon by Open Collective indeed. Just made an update to remove Patreon in the README :)
