### ISSUE TITLE
Can't receive mail from external Postfix if TLS is enabled

### ISSUE THREAD

**Issue by delucca** [simple-login/app#770]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**
I'm not being able to receive e-mails when I'm using an external Postfix server with TLS enabled. I've followed the steps on [Postfix TLS](https://github.com/simple-login/app/blob/master/docs/postfix-tls.md) but they are not enought.

My Postfix server has the following config:
```
smtp_tls_security_level = encrypt
```

If I use that config (instead of `may`) every time my Postfix server receives a message for one of my alias I got the following error while forwarding it:
```
Jan 26 02:52:43 mail postfix/smtp[1394]: A03633229F: to=<healthcheck@fflo.me>, relay=simplelogin_email_handler[240.0.0.4]:20381, delay=0.06, delays=0.02/0/0.03/0, dsn=4.7.4, status=deferred (TLS is required, but was not offered by host simplelogin_email_handler[240.0.0.4]
```
As you can see, for some reason it is not being able to use TLS to commucate with the e-mail handler. As I've said, I've added `POSTFIX_SUBMISSION_TLS=true` in my `.env` file.

**Expected behavior**
I would like to Postfix be able to send the e-mail to the handler with a proper TLS connection.

**Comment by nguyenkims** [comment]
The `POSTFIX_SUBMISSION_TLS` option is rather for the Postfix client so SimpleLogin will use the 587 port (instead of the 25 port) and start TTLS. https://github.com/simple-login/app/blob/master/docs/postfix-tls.md does indeed correspond to that use case.

Currently SimpleLogin email handler isn't a full SMTP server and doesn't understand encrypted incoming email. I'd recommend to run Postfix on the same server as the email handler is run instead.

**Comment by delucca** [comment]
Thanks.

I was already running Postfix on the same server. I changed a couple of Postfix options and now it accepts unencrypted connections, so Simplelogin can talk with my Postfix server unencrypted.

Thanks!

**Comment by jeifour** [comment]
@delucca I'm interested in setting up a mail relay for outgoing mail via port 465 which would require me to set `smtp_tls_security_level = encrypt` if I understand Postfix documentation correctly. However, I'm afraid this would break the communication with the SimpleLogin email handler. How did you solve your issue? Was it similar, did it involve `smtp_tls_policy_maps`? I don't know much about Postfix so before I break my mail server I thought I'd ask.

**Comment by delucca** [comment]
> @delucca I'm interested in setting up a mail relay for outgoing mail via port 465 which would require me to set `smtp_tls_security_level = encrypt` if I understand Postfix documentation correctly. However, I'm afraid this would break the communication with the SimpleLogin email handler. How did you solve your issue? Was it similar, did it involve `smtp_tls_policy_maps`? I don't know much about Postfix so before I break my mail server I thought I'd ask.

Hi! 😄

I don't know if my current setup relates with yours, but I have the following (everything is running in the same machine):
- 1 container for docker-mailserver
- 1 container for simple-login

Since my dms (short for docker-mailserver) owns my mail ports (because I have a running mail server in that machine),  I have the following Postfix config files in that container:

/etc/postfix/pgsql-transport-maps.cf
```
# postgres config
hosts = main-postgres.cznc62libauz.us-east-1.rds.amazonaws.com
user = simplelogin
password = Yr7k@Cb&L8$uuvWCZq!nZ
dbname = simplelogin

# forward to smtp:simplelogin_email_handler:20381 for custom domain AND email domain
query = SELECT 'smtp:simplelogin_email_handler:20381' FROM custom_domain WHERE domain = '%s' AND verified=true
    UNION SELECT 'smtp:simplelogin_email_handler:20381' WHERE '%s' = 'fflo.me' LIMIT 1;
```

/etc/postfix/pgsql-relay-domains.cf
```
# postgres config
hosts = main-postgres.cznc62libauz.us-east-1.rds.amazonaws.com
user = simplelogin
password = Yr7k@Cb&L8$uuvWCZq!nZ
dbname = simplelogin

query = SELECT domain FROM custom_domain WHERE domain='%s' AND verified=true
    UNION SELECT '%s' WHERE '%s' = 'fflo.me' LIMIT 1;
```

Also, I've added the following to my `postfix-main.cf`
```
relay_domains = pgsql:/etc/postfix/pgsql-relay-domains.cf
transport_maps = pgsql:/etc/postfix/pgsql-transport-maps.cf

# Disable TLS by default
smtp_tls_security_level = may
```
The dms uses that file to create the `main.cf` for Postfix

The same for `postfix-master.cf`
```
# TLS for Simplelogin
submission/inet/smtp_tls_security_level=may
```

I think that with those configs I can connect with my SMTP using SSL, but it is not mandatory 😄
So, Simple-login works
