### ISSUE TITLE
Feature Request: Create Filter in the Web App for All Custom Aliases

### ISSUE THREAD

**Issue by BeatLink** [simple-login/app#771]
Hey there. I love using simplelogin, I think its one of the best things for email.

While going through my aliases in the web interface, i noticed that there's no easy way to view custom aliases, that is ones not tied to a directory or particular domain but instead have a custom prefix and the random character suffix.

So what im proposing is a new filter option to find these custom aliases. Let me know what you think!

**Comment by nguyenkims** [comment]
@BeatLink if you want to look for a specific suffix, you can use the search right?

**Comment by BeatLink** [comment]
Not exactly. When i say suffixes i mean the randomized part when you create an alias. For example, say i create an alias like github.xyz@simplelogin.co. What i mean by prefix would be "github" while the suffix would be "xyz"

What im really asking for is a way to search for custom aliases outside a directory or domain. Searching for them as a group is impossible since the suffix is random and the prefixes are usually written differently by the user for the service its intended for (eg github prefix for github email alias or discord prefix for discord email alias)

**Comment by nguyenkims** [comment]
I see, do you know in what case you'd want to use this filter? Currently we don't store the information whether an alias is created based on a random suffix or not.

**Comment by BeatLink** [comment]
It would be helpful to sort and organize non directory aliases, for cleanup, organizing and so on. As these would be the most transient aliases, these would be the most likely to need cleaning up
