### ISSUE TITLE
Reply button of thunderbird / K9 does NOT set the senders' address to the reverse-alias

### ISSUE THREAD

**Issue by Satlinker** [simple-login/app#785]
It's not really a problem of simple-login. I tried it with thunderbird and K9: if they get a mail with TO: reverse-alias, the reply-button creates a return mail with the regular account-address as sender instead of TO: reverse-alias. I don't know why they are doing this. They do not just exchange FROM and TO.

**Comment by nguyenkims** [comment]
I wonder if we should rather create an issue/feature request on K9 and Thunderbird instead?
