### ISSUE TITLE
Upgrade to Python 3.9

### ISSUE THREAD

**Issue by FozzieHi** [simple-login/app#788]
Do we have any blockers to upgrade to Python 3.9? Python 3.7 is only receiving security updates now and Python 3.9 has been out for a while so it'd be nice to upgrade.

I think Python 3.9 is the current limit for upgrading without changing any packages as there doesn't seem to be breaking changes between Python 3.7 - 3.9 and it was released within our current package pinning window. Python 3.10 is still relatively new so we may have to update some packages past the pinned versions to be compatible with it.

**Comment by nguyenkims** [comment]
@FozzieHi as far as I know there shouldn't be any issue upgrading the code to Python 3.9. But as SimpleLogin uses some non-Python (i.e. C) packages, we need to run the new version extensively to catch any unexpected issue.
