### ISSUE TITLE
Some variant of Codneameize

### ISSUE THREAD

**Issue by Leopere** [simple-login/app#79]
https://github.com/jjmontesl/codenamize or some variant would be awesome for choosing email addresses.

**Comment by nguyenkims** [comment]
@Leopere thanks for the suggestion! Do you know how it could be useful to have other random words generator? Currently the words to create aliases are from a list of words and it's quite easy to add more words into this list.

**Comment by Leopere** [comment]
I know that discord among other companies has a system for detecting shady
signups. Any more ways to confuse these sorts of things is smart.

**Comment by nguyenkims** [comment]
@Leopere I see, I just created this ticket in our roadmap https://trello.com/c/C3MW3yM9/32-use-codneameize-to-create-random-alias. Feel free to vote on it to make happen sooner :).
