### ISSUE TITLE
Reverse alias in mail body

### ISSUE THREAD

**Issue by SibrenVasse** [simple-login/app#81]
When replying to an email received via an alias, most email clients will quote the email at the bottom.
This will contain the reverse alias:

> On DATE, NAME - local at domain.tld <ra+string@simplelogin.co> wrote:

When replying the original sender will see this in the email body and see you're using simplelogin. Might it be an idea to find and replace 'ra+string@simplelogin.co' with the corresponding destination, (and perhaps even remove the email part next to the name) in the email body?

**Comment by nguyenkims** [comment]
@SibrenVasse Nice catch! I have actually thought about this before and am not 100% sure that removing all "traces" of SimpleLogin is a good idea:

- SimpleLogin tries to never touch the email body as this is a tricky topic: email clients are famous to create messy email body.
- one can always see that the emails are coming from SimpleLogin by looking at the email header
- the reply-email can only be used by its authorised users (i.e. alias owner).

But if this feature makes sense for a lot of users, we could add an option to remove all SimpleLogin traces from the email.

**Comment by SibrenVasse** [comment]
Agreed, removing all traces from the mail body is not necessary or in any way a information / or security issue (your third point)
It's just a visual thing that in my case the email thread was confusing people as who sent what email.

I think just replacing the ra+string@simplelogin.co string would go a long way though. As this string is very unique and will never occur in an email normally, so should be safe to find and replace, no matter the messy email body?

**Comment by nguyenkims** [comment]
@SibrenVasse I have tried to replace the ra+string@simplelogin.co (the code is on the branch `staging`) and it works well :). , except for the case where emails are signed (via PGP): the signature fails as email content has been modified.
