### ISSUE TITLE
No "To" field

### ISSUE THREAD

**Issue by bx2KdaukwF** [simple-login/app#851]
I just received today at Gmail a forwarded email from an address `@fb.com` without the classic `To: "myAlias@mydomain.com" <myAlias@mydomain.com>`, which skipped my filter. Looking at the original message, it just lacks the field:

This email (everything else looks fine):
```
From: Random Name <randomname.at.fb.com_noise@simplelogin.co>
List-Unsubscribe: <mailto:unsubscribe@simplelogin.co?subject=9999999=>
X-SimpleLogin-Want-Signing: yes
```

Normal email (I received 2 of them from the same address before):
```
From: Random Name <randomname.at.fb.com_noise@simplelogin.co>
To: "myAlias@mydomain.com" <myAlias@mydomain.com>
List-Unsubscribe: <mailto:unsubscribe@simplelogin.co?subject=9999999=>
X-SimpleLogin-Want-Signing: yes
```

I'm sure it's not spam and because I already received 2 emails minutes before with everything looking fine, I don't think it's Facebook's fault. Also, I don't think I can reproduce this error again, so it's more of looking at the code/waiting if other people will have the same issue.

**Comment by nguyenkims** [comment]
@bx2KdaukwF can you send me the alias and the sender to son[at]simplelogin.io that has this issue so we can investigate?

**Comment by nguyenkims** [comment]
@bx2KdaukwF the email might have been sent with your alias in BCC field and that's why you don't see the alias in the To field. We have added a feature recently that'll add the alias to the TO: field in this case and this feature should be deployed soon.

**Comment by bx2KdaukwF** [comment]
Just checked and there wasn't any BCC field. I think it's solved, thank you :)
