### ISSUE TITLE
Migrating from existing custom solution / domain

### ISSUE THREAD

**Issue by Indigo744** [simple-login/app#88]
Hello,

I just discovered your website from a recent post you made on DEV (_Why we left AWS_).

I must say, I am happy someone finally took the time to build a proper solution around the idea of "alias-per-website" email. I am even more glad you are French. So big kuddos to you!

It is actually something I have been doing for quite some time (5+ years), albeit more manually.

I have a domain registered at OVH, which comes with a basic MX Plan with up to 1000 [aliases](https://docs.ovh.com/fr/emails/guide-des-redirections-emails/).

Right now, I have 438 aliases (yeah, I don't really clean up unused one, unless I start receiving spam through them).

I manage my aliases using the OVH API and a Python script (see [Indigo744/ovh-manage-email-alias-python](https://github.com/Indigo744/ovh-manage-email-alias-python)).

It works quite well. Alias creation is (usually) fast and I never missed an email. 

However, the biggest downside is that I can't send mail from these aliases. So when I need to have a discussion with, let's say, a technical support for an online service, my original email is disclosed.

So your solution would allow me to continue as before, but with the added benefits of keeping my original email secure!

**Now I'm wondering how I would migrate from OVH to your solution?** With that amount of existing aliases, I really don't want to do it by hand.

I see two approaches:
1. Using a custom-made Python script as a bridge between the OVH API and your API
1. Using an import feature
   Like from a text file (one address per line, or CSV even)
   => this would be a feature request

**Additionally, do you offer an export feature?** I am always thinking for the long term (and the sustainability of a solution). So while I really wish you success, I want to be able to easily get all my current aliases from SimpleLogin (a CSV would suffice).

Thank your for your insight.

**Comment by nguyenkims** [comment]
Thanks for your kind words! "Batch import" could be an interesting feature indeed!

If you don't want to wait, you can use SimpleLogin API to create aliases in batch. You first need to create an `api key` in the "API Key" tab on SimpleLogin webapp.
Then use the `POST /api/alias/custom/new` endpoint (https://github.com/simple-login/app#post-apialiascustomnew) to create new alias with:
- `alias_prefix`: the part before "@" in your email address
- `alias_suffix`: your domain.

The endpoint doc is maybe not detailed enough as this is only used by our extension and mobile apps for now, please don't hesitate to ask me if you have any question!

This works if your domain has been validated in SimpleLogin. To begin, I suggest you add a subdomain that you don't use into SimpleLogin, run the script for a couple of email addresses to see if everything runs fine and only in this case, move the main domain to SimpleLogin and run the big script.

> Additionally, do you offer an export feature? 

Yes in the settings tab, you can export your data.

Btw just checked out your repo to interact with OVH, looks neat 👍

**Comment by Indigo744** [comment]
Thank you for your answer.

I'll look into the API and play around a bit. This is exactly what I need.
Of course I'll publish the migration script on GitHub (could help future people).

In any case, the batch import will be great for less tech-savvy people.

I'll keep you posted 😸 

Have a nice day!

**Comment by Indigo744** [comment]
By the way, if anyone is looking for the Batch import feature, it is tracked on Trello here:
https://trello.com/c/MPl4opLW/38-batch-import

**Comment by nguyenkims** [comment]
Yes I just added it onto the roadmap, feel free to "vote" on it to make it happen sooner :).
