### ISSUE TITLE
Disabling alias using unsubscribe Link does not work

### ISSUE THREAD

**Issue by mpldr** [simple-login/app#887]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**
Using the Unsubscribe function to disable an alias does not work.

**Expected behavior**
It is disabled

**Screenshots**

![2022-04-11-20-01-46](https://user-images.githubusercontent.com/33086936/162801390-e1e79749-3114-4d0f-8a29-038c0be77f7b.png)
![2022-04-11-20-02-45](https://user-images.githubusercontent.com/33086936/162801780-9a724aba-6247-4203-844b-6c51c0b6ec92.png)
![2022-04-11-20-04-05](https://user-images.githubusercontent.com/33086936/162801698-a198f876-55d8-4562-81a2-6090682368e2.png)

**Comment by nguyenkims** [comment]
The one click unsubscribe must be used from the alias mailbox (or one of the authorised mailboxes). The error you have indicates that the button has been used from unknown mailbox.

**Comment by mpldr** [comment]
The Mail is for ***@***.*** and the from header is also
***@***.***

**Comment by mpldr** [comment]
awesome…

moritz@my-domain.de (both) the sending email matches the receiving address.
