### ISSUE TITLE
Webauthn: Client authentication flow defaults to USB security key

### ISSUE THREAD

**Issue by moppman** [simple-login/app#929]
## Prerequisites
- [x ] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**
User has registered an Android phone as  roaming authenticator in the SimpleLogin settings menu:
![register](https://user-images.githubusercontent.com/10085380/165126083-9390901a-99ca-46fa-8dab-c3a020b8594b.png)

**Expected behavior**
On login, the user should be prompted  to pick an authenticator, in this case the Android phone.
Instead, the user only sees this:
![login](https://user-images.githubusercontent.com/10085380/165126602-d3bef4cb-830d-4573-8d50-729649c6b689.png)
That means there's no way for the user to pick the "correct" authenticator because the browser prompt defaults to USB key.

**Environment (If applicable):**
 - OS: Linux
 - Browser: Chrome 100
 
**Additional context**
If I were to guess, there's probably some misconfiguration in SimpleLogin's [Webauthn Client Authentication](https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/WebAuthn_Client_Authentication.html) flow. 

edit: this is the only authenticator I have registered.
edit2: The phone acts as roaming authenticator. Communication between the authenticator (phone) and the client I try to log in with (linux chrome) happens via [caBLE protocol](https://blog.millerti.me/2021/06/18/previewing-chromes-cable-v2-support-for-webauthn/).

**Also, thanks for your great product :smile:**

**Comment by nguyenkims** [comment]
@acasajus @cquintana92 I wonder if you guys can reproduce the issue on Android?

**Comment by moppman** [comment]
> @acasajus @cquintana92 I wonder if you guys can reproduce the issue on Android?

For what it's worth: if I login into the dashboard on my  phone's browser (Android Chrome), meaning the phone which is also the authenticator, I'm getting the prompt to identify via fingerprint sensor as expected and login works as expected.

**Comment by acasajus** [comment]
@moppman have you more than one device registered?

**Comment by moppman** [comment]
> @moppman have you more than one device registered?

@acasajus Ah sorry, should have mentioned that. No, that is my only device.

**Comment by acasajus** [comment]
There's something I'm not following from your report. You've registered your android phone as an authenticator and you are trying afterwards to login with your browser with linux?

**Comment by moppman** [comment]
> There's something I'm not following from your report. You've registered your android phone as an authenticator and you are trying afterwards to login with your browser with linux?

Exactly.  The phone acts as roaming authenticator. Communication between the authenticator (phone) and the client I try to log in with (linux chrome) happens via [caBLE protocol](https://blog.millerti.me/2021/06/18/previewing-chromes-cable-v2-support-for-webauthn/).
