### ISSUE TITLE
Remove exception for deleted temp emails

### ISSUE THREAD

**Issue by rivalsystems** [simple-login/app#93]
Can we not throw an exception for when someone attempts to send an email to an alias we've previously deleted? 

![image](https://user-images.githubusercontent.com/40866195/75160338-6fb43c00-56df-11ea-8f2d-64c991223c29.png)

**Comment by nguyenkims** [comment]
You can use the latest image (1.0.5) that will not raise an error for this scenario.

**Comment by nguyenkims** [comment]
@rivalsystems have you had a chance to try out the new image ?

**Comment by nguyenkims** [comment]
@rivalsystems this error should not show up any more, I'll go ahead and close this issue then.
