### ISSUE TITLE
Comment about SPF record

### ISSUE THREAD

**Issue by aexerces** [simple-login/app#944]
Hello,

This is a comment about the SPF record set: it is written in the guide to selfhost simple-login to set "~all" and explained it means that only server owner can deliver emails.
But, what I know is that this policy will deliverer the email, marked it as an SPF failure. Is it what you mean?
If the email isn't mean to be deliver, "-all" has to be used.

This is some relevant links:
[RFC 7208: Softfail](https://datatracker.ietf.org/doc/html/rfc7208#section-2.6.4)
[RFC 7208: Qualifiers](https://www.rfc-editor.org/rfc/rfc7208.html#section-4.6.2)

Thanks.

**Comment by nguyenkims** [comment]
@aexerces the `-all` is rarely used as some emails can be sent via a "classic" email forwarding and will fail SPF. That's why as a convention, we usually use `~all` instead.

**Comment by aexerces** [comment]
Thanks @nguyenkims for your reply. I had to be sure. It's been a long time since I wanted to use self-hosted mail services. But it's a sensitive task, and I don't want to fail in anyway.
I think that your explanation about the "~all" qualifier can be misleading. But it's probably due to my ignorance.

**Comment by nguyenkims** [comment]
@aexerces 

> I think that your explanation about the "~all" qualifier can be misleading. But it's probably due to my ignorance.

I'm not sure to understand why you think it's misleading. There's not much of difference between ~ and - anyway if you don't have a lot of email volume so you can pick either one.
