### ISSUE TITLE
API to create aliases?

### ISSUE THREAD

**Issue by AquiGorka** [simple-login/app#98]
Hello there, I'm looking at simple login and it looks solid, I would like to be able to create aliases programmatically and for this I was looking for such an API. Could you point me in the right direction?

**Comment by nguyenkims** [comment]
Hey SimpleLogin API doc is at https://github.com/simple-login/app#api. The endpoints are currently used by browser extensions and (work-in-progress) mobile apps. 

To create aliases, you can use this endpoint 
[POST /api/alias/custom/new](https://github.com/simple-login/app#post-apialiascustomnew) for custom alias or [POST /api/alias/random/new](https://github.com/simple-login/app#post-apialiasrandomnew) for random alias.

Btw what scenario do you want to create?

**Comment by AquiGorka** [comment]
Hey @nguyenkims thanks for the quick reply, I'm looking at being able to create aliases programmatically and give them to end-users from within my own app.

**Comment by AquiGorka** [comment]
Come to think about it, I have another question @nguyenkims: is there a way to link an alias to a webhook? Meaning, any incoming email to the alias triggers a request to the webhook with the email data as payload?

**Comment by nguyenkims** [comment]
@leshokunin @AquiGorka sounds interesting, feel free to drop me an email at partner@simplelogin.io so we can discuss more in details!

**Comment by nguyenkims** [comment]
@leshokunin @AquiGorka should I close this issue?

**Comment by AquiGorka** [comment]
@nguyenkims thanks for the info, I have a follow-up question: is there an API to programmatically create new namespaces for aliases?
eg -> @namespace.mydomain.com

**Comment by nguyenkims** [comment]
@AquiGorka We don't have an api to create namespace/directory yet. This endpoint is in our todo list as it's necessary for our browser extension or mobile apps.

**Comment by AquiGorka** [comment]
@nguyenkims
I'm running into a blocker in my current work: I'm trying to set up a way to avoid having to create aliases by hand every time.
A very convenient way would be to set up wild card aliases, for example, `*.namespace@mydomain.com` -> `catch-all@address.com`
Ideally, the wild card would point to an email address but I can also set specific aliases to point to other addresses: `specific.namespace@mydomain.com` -> `other@address.com`

**Comment by nguyenkims** [comment]
@AquiGorka should I close this issue?

**Comment by AquiGorka** [comment]
Yes, thank you very much for all the follow-up.
